/** @type {import('tailwindcss').Config} */
export default {
  content: ["./public/**/*.html"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed-variant": "#8e004b",
        "surface-dim": "#d9dadb",
        "surface-container": "#edeeef",
        "on-surface-variant": "#3d2a31",
        "surface-container-high": "#e7e8e9",
        "surface-bright": "#f8f9fa",
        "on-error-container": "#93000a",
        "surface-variant": "#e1e3e4",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bcc7dd",
        "inverse-surface": "#2e3132",
        "on-secondary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#3c475a",
        tertiary: "#3c475a",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e2bdc7",
        "on-error": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed": "#3e001e",
        "surface-container-low": "#f3f4f5",
        "surface-tint": "#b90064",
        "inverse-primary": "#ffb0c9",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed": "#111c2c",
        "surface-container-highest": "#e1e3e4",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#474746",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary": "#ffffff",
        "primary-fixed": "#ffd9e2",
        "primary-fixed-dim": "#ffb0c9",
        "on-secondary-container": "#636262",
        "error-container": "#ffdad6",
        "primary-container": "#e6007e",
        "on-tertiary-container": "#ffffff",
        "on-surface": "#191c1d",
        "secondary-container": "#e2dfde",
        "on-background": "#191c1d",
        primary: "#b90064",
        "tertiary-container": "#6c778b",
        background: "#f8f9fa",
        secondary: "#5f5e5e",
        "tertiary-fixed": "#d8e3fa",
        outline: "#8e6f77",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter-lg": "2rem",
        "gutter-sm": "1rem",
        margin: "2rem",
        "margin-desktop": "3rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        "body-sm": ["Hanken Grotesk"],
        "headline-sm": ["Montserrat"],
        "display-lg": ["Montserrat"],
        "headline-xl-mobile": ["Montserrat"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["Montserrat"],
        "label-technical": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-xl": ["Montserrat"],
        "display-lg-mobile": ["Montserrat"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "0.03em", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-technical": ["11px", { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
};
