export const contact = {
  email: "proyectos@vexil.es",
  phoneDisplay: "616 048 109",
  phoneTel: "+34616048109",
  whatsapp: "https://wa.me/34616048109",
};

export const homeFaqH2 = "Preguntas frecuentes";
export const homeFaqs = [
  { q: "¿Qué servicios de rotulación ofrece Vexil?", a: "Hacemos trabajos llave en mano: diseño, fabricación y montaje de rótulos, fachadas comerciales, rotulación de vehículos, impresión digital, decoración de interiores, lámina solar y vinilos ácidos, señalética, stands para eventos e iluminación decorativa. También cortamos y grabamos a medida con CNC y láser." },
  { q: "¿En qué zonas trabajáis?", a: "Nuestra base está en El Campello y trabajamos en Alicante, San Juan, San Vicente, El Campello, Mutxamel, Jijona, Villajoyosa y Benidorm. Si tu proyecto está fuera de esta zona, cuéntanoslo y lo estudiamos." },
  { q: "¿Cómo puedo pedir presupuesto?", a: "Escríbenos por WhatsApp o por email con lo que necesitas: qué quieres rotular, dónde y, si puedes, unas fotos y medidas aproximadas. Con eso te preparamos una propuesta y, si hace falta, pasamos a tomar medidas." },
  { q: "¿Hacéis también el diseño del rótulo o solo la fabricación?", a: "Hacemos las dos cosas. Puedes traernos tu logotipo y diseño listos para producción, o diseñamos el rótulo contigo antes de fabricarlo y montarlo." },
  { q: "¿Me ayudáis con los permisos municipales?", a: "Los permisos y licencias los gestiona normalmente el cliente ante su ayuntamiento. Si tu caso lo requiere, contamos con un arquitecto que puede encargarse de la tramitación." },
  { q: "¿Trabajáis con particulares o solo con empresas?", a: "Con ambos. Rotulamos negocios y también hacemos trabajos para particulares, desde un vinilo decorativo hasta un rótulo terminado que quieras colgar tú mismo." },
];

export const navServices = [
  { slug: "fachadas", name: "Fachadas comerciales", short: "Revestimientos", icon: "apartment" },
  { slug: "rotulos", name: "Rótulos", short: "Corpóreos, neón, luminosos", icon: "signpost" },
  { slug: "impresion-digital", name: "Impresión digital", short: "Gran formato", icon: "print" },
  { slug: "vehiculos", name: "Rotulación de vehículos", short: "Vinilo fundido", icon: "local_shipping" },
  { slug: "interiores", name: "Decoración de interiores", short: "Murales y vinilos", icon: "chair" },
  { slug: "lamina-solar", name: "Lámina solar y vinilos ácidos", short: "Arquitectura y privacidad", icon: "wb_sunny" },
  { slug: "corte", name: "Corte a medida", short: "CNC y láser", icon: "precision_manufacturing" },
  { slug: "stands", name: "Stands para eventos", short: "Ferias y congresos", icon: "view_quilt" },
  { slug: "iluminacion-decorativa", name: "Iluminación decorativa", short: "Ambiente y marca", icon: "light" },
  { slug: "senaletica", name: "Señalética y placas", short: "Directorios y avisos", icon: "alt_route" },
];

const processDefault = [
  { n: "01", icon: "add_a_photo", title: "Envías foto o nos visitas", text: "Una foto, un boceto o una llamada basta para empezar. Si hace falta, medimos en tu local con distanciómetro láser.", meta: "Día 1 · Requerimientos" },
  { n: "02", icon: "draw", title: "Fotomontaje y presupuesto", text: "En menos de 24 horas recibes una simulación y un precio cerrado, desglosado por partidas, sin costes ocultos.", meta: "Día 2 · Propuesta" },
  { n: "03", icon: "precision_manufacturing", title: "Fabricación en taller propio", text: "Producimos en nuestras instalaciones con CNC, láser y luminotecnia LED. Control de calidad sin intermediarios.", meta: "Días 3-7 · Producción" },
  { n: "04", icon: "handyman", title: "Instalación limpia y rápida", text: "Montadores profesionales, horarios coordinados y entrega llave en mano para no parar tu negocio.", meta: "Entrega llave en mano" },
];

export const services = {
  fachadas: {
    slug: "fachadas",
    breadcrumb: "Fachadas comerciales y revestimientos",
    eyebrow: "Publicidad exterior y renovación integral de imagen comercial",
    h1Before: "Rotulación de Fachadas: Transforma la Entrada de tu Negocio en un",
    h1Accent: "Imán de Clientes",
    lead: "Diseñamos, fabricamos e instalamos revestimientos de fachada, paneles de composite de aluminio (Dibond / Alucobond), rotulación de gran formato y letras corpóreas 3D para que tu local, nave o franquicia destaque a cientos de metros.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "storefront", title: "Sin cierre comercial", sub: "Montaje por fases" },
      { icon: "shield", title: "Alta resistencia", sub: "Sol, viento y lluvia" },
      { icon: "verified", title: "Materiales de taller", sub: "Acabado a medida" },
    ],
    ctaPrimary: "Pedir presupuesto gratis para mi fachada",
    ctaSecondary: "Ver soluciones y materiales",
    trust: "Diseño, fabricación y montaje de fachadas comerciales. Taller en El Campello.",
    heroImg: "fachada-hero.jpg",
    heroBadge: "Renovación integral: Alupanel + 3D LED",
    heroTitle: "Clínica & Retail Centro",
    heroSub: "Panel composite negro satinado + iluminación indirecta",
    heroStat: "+180%",
    heroStatLabel: "Visibilidad diurna",
    whyEyebrow: "Impacto comercial directo en tu negocio",
    whyH2: "¿Por qué renovar la fachada de tu negocio? Beneficios reales de retorno inmediato",
    whyLead: "La fachada no es un gasto decorativo: es el vendedor que trabaja para tu empresa las 24 horas del día.",
    benefits: [
      { icon: "groups", kicker: "01 / Entrada de clientes", title: "Primera impresión inolvidable", text: "El 70% de los clientes potenciales decide entrar o preguntar por el aspecto exterior. Una fachada cuidada proyecta solvencia y confianza.", tag: "Multiplica el tráfico peatonal" },
      { icon: "light_mode", kicker: "02 / Notoriedad 24/7", title: "Aumento inmediato de visibilidad", text: "Rótulos de alto contraste y LED de alta eficiencia para que peatones y conductores te localicen de día y de noche.", tag: "Visibilidad día y noche" },
      { icon: "layers", kicker: "03 / Protección técnica", title: "Aislamiento y estética duradera", text: "El composite oculta grietas, cableados y cajas de persiana. Crea una barrera limpia, sin pinturas anuales.", tag: "Cero grietas ni pintura anual" },
      { icon: "trending_up", kicker: "04 / Plusvalía de activo", title: "Revalorización del local", text: "Una imagen contemporánea eleva el posicionamiento de marca y el valor patrimonial del establecimiento.", tag: "Mayor valor de marca" },
    ],
    solutionsEyebrow: "Catálogo modular Vexil",
    solutionsH2: "Tipos de soluciones y acabados para tu fachada",
    solutionsLead: "Combinamos revestimientos estructurales con iluminación y tipografía para conjuntos duraderos.",
    solutions: [
      { tag: "Solución 01 · Revestimiento total", tech: "Alucobond / Dibond", title: "Revestimiento en panel composite de aluminio", text: "Bandejas mecanizadas con núcleo de alta densidad y aluminio lacado al horno. La solución más usada por clínicas, concesionarios y grandes marcas.", a: "Acabados", av: "Mate, brillo, metalizado o madera", b: "Instalación", bv: "Subestructura de fijación oculta", img: "fachada-01.jpg", cap: "Grosor 3 mm / 4 mm con garantía UV" },
      { tag: "Solución 02 · Máximo alcance", tech: "Luminotecnia LED 12V", title: "Rótulos luminosos y cajas de luz LED gran formato", text: "Cajas estancas de aluminio con frontal de metacrilato o lona backlight. LED IP67 de bajo consumo y encendido automático.", a: "Consumo", av: "LED A++ alta intensidad", b: "Protección", bv: "IP67 contra polvo y lluvia", img: "fachada-02.jpg", cap: "Frontales de una pieza hasta 50 m" },
      { tag: "Solución 03 · Elevada distinción", tech: "Relieve arquitectónico", title: "Letras corpóreas 3D en relieve", text: "Corte CNC y láser en acero, aluminio, latón o PVC. Con o sin retroiluminación halo para un acabado premium.", a: "Materiales", av: "Acero AISI-316, aluminio, metacrilato", b: "Iluminación", bv: "Frontal, halo o sin luz", img: "fachada-03.jpg", cap: "Corte CNC de máxima precisión" },
      { tag: "Solución 04 · Escaparate", tech: "Poliméricos cast", title: "Vinilos de fachada y cristaleras comerciales", text: "Microperforados, efecto arenado y vinilo de corte para lunas y accesos, con privacidad y branding a la vez.", a: "Tipo de vinilo", av: "Polimérico fundición con filtro UV", b: "Función", bv: "Filtro solar, intimidad y marca", img: "fachada-04.jpg", cap: "Garantía antidescoloración 7 años" },
    ],
    processH2: "Cómo trabajamos: de tu fachada actual a un resultado impecable en 4 pasos",
    processLead: "Coordinamos el proyecto para que no pierdas clientes por obras. Fabricación propia, sin intermediarios.",
    process: processDefault,
    casesH2: "Transformaciones de fachada recientes",
    cases: [
      { img: "caso-01.jpg", tag: "Centro urbano", title: "Boutique retail", sub: "Composite negro + letras halo" },
      { img: "caso-02.jpg", tag: "Polígono", title: "Nave industrial", sub: "Gran formato + totem" },
      { img: "caso-03.jpg", tag: "Salud", title: "Clínica dental", sub: "Alupanel blanco + LED" },
      { img: "caso-04.jpg", tag: "Hostelería", title: "Cadena de cafeterías", sub: "Imagen uniforme multi-local" },
    ],
    faqH2: "Preguntas frecuentes sobre la renovación de fachadas",
    faqs: [
      { q: "¿Qué incluye la rotulación de una fachada comercial?", a: "Puede incluir el rótulo principal, banderolas, rotulación de escaparates y puerta, revestimientos de fachada y la iluminación. Lo diseñamos como un conjunto para que el local tenga una imagen coherente y se vea bien de día y de noche." },
      { q: "¿Podéis hacerlo todo, del diseño al montaje?", a: "Sí. Nos ocupamos del diseño, la fabricación y el montaje, para que no tengas que coordinar a varios proveedores." },
      { q: "¿Necesito licencia o permiso para cambiar la fachada de mi local?", a: "En la mayoría de municipios, rotular o modificar una fachada requiere comunicación o licencia municipal, y los requisitos cambian según el ayuntamiento y el tipo de actuación. El trámite lo gestiona normalmente el cliente; si lo necesitas, tenemos un arquitecto que puede encargarse. Si el local está en un edificio comunitario, conviene consultar también a la comunidad de propietarios." },
      { q: "¿Puedo combinar varios materiales en la fachada?", a: "Sí. Es habitual combinar, por ejemplo, letras corpóreas, paneles composite, vinilo en cristales e iluminación. Te proponemos la combinación que mejor encaje con tu marca y tu presupuesto." },
      { q: "¿Qué necesito para que me hagáis un presupuesto?", a: "Fotos de la fachada actual con el entorno, medidas aproximadas y tu logotipo. Si nos cuentas qué quieres cambiar, te decimos si hace falta visita para tomar medidas." },
      { q: "¿Cuánto se tarda en renovar una fachada?", a: "Depende del alcance del trabajo y de los trámites necesarios. Te damos un plazo concreto en el presupuesto, una vez vista la fachada y definido el proyecto." },
    ],
    contactH2: "¿Quieres saber cómo quedaría la fachada de tu negocio?",
    contactLead: "Envíanos una foto del frontal y tu logotipo. En menos de 24 horas laborables te preparamos fotomontaje y presupuesto llave en mano.",
  },

  rotulos: {
    slug: "rotulos",
    variant: "types",
    breadcrumb: "Rótulos",
    eyebrow: "Familia de producto · todos los tipos de rótulo",
    h1Before: "Rótulos a medida: corpóreos, neón, luminosos y",
    h1Accent: "sin iluminación",
    lead: "Una sola página para todo el catálogo de rótulos. Fabricamos en taller propio letras 3D, cajas de luz LED, neón y rotulación sin luz. También hacemos mantenimiento y reparación de rótulos existentes, los hayamos fabricado nosotros o no.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "light", title: "Con o sin luz", sub: "Cuatro familias" },
      { icon: "build", title: "Mantenimiento", sub: "Reparación de rótulos" },
      { icon: "verified", title: "Garantía LED", sub: "Hasta 5 años" },
    ],
    ctaPrimary: "Pedir presupuesto de rótulos",
    ctaSecondary: "Ver tipos de rótulo",
    trust: "Diseño, fabricación, instalación, mantenimiento y reparación de rótulos.",
    heroImg: "fachada-03.jpg",
    heroBadge: "Catálogo completo de rótulos",
    heroTitle: "Un proveedor, todos los tipos",
    heroSub: "Corpóreos · Neón · Luminosos · Sin luz · Mantenimiento",
    heroStat: "4",
    heroStatLabel: "Familias + taller de reparación",
    whyEyebrow: "Por qué unificar el rótulo en un solo proyecto",
    whyH2: "El rótulo correcto se elige por distancia, luz y material, no por catálogo suelto",
    whyLead: "Te asesoramos para combinar tipos si hace falta: una corpórea en fachada, un neón en interior y una caja de luz en el testero. Si el rótulo ya está instalado y ha fallado, lo diagnosticamos y lo reparamos.",
    benefits: [
      { icon: "hub", kicker: "01 / Un solo interlocutor", title: "Todos los tipos, un taller", text: "No encadenas proveedores. Corpóreas, neón, luminosos y vinilo salen del mismo control de calidad.", tag: "Fabricación directa" },
      { icon: "visibility", kicker: "02 / Legibilidad", title: "Se lee de día y de noche", text: "Calculamos tamaño, contraste y temperatura de color según la calle, el tráfico y la normativa local.", tag: "Visibilidad real" },
      { icon: "architecture", kicker: "03 / Encaje en fachada", title: "Integrado en tu local", text: "El rótulo no flota: se ancla a composite, ladrillo, sandwich o cristalera con planimetría.", tag: "Montaje técnico" },
      { icon: "savings", kicker: "04 / Precio de taller", title: "Sin intermediarios", text: "Presupuesto desglosado por tipo de rótulo, iluminación y estructura.", tag: "Precio cerrado" },
    ],
    typesH2Intro: "Tipos de rótulos y servicio de taller",
    typesLead: "Cuatro familias de producto y, además, mantenimiento y reparación de rótulos ya instalados.",
    types: [
      { id: "corporeos", h2: "Rótulos corpóreos", kicker: "Relieve 3D", text: "Letras y logos en volumen, recortados una a una, que se colocan sobre la fachada o sobre un panel. Con o sin iluminación.", specs: ["PVC, metacrilato, aluminio o composite", "Con luz o sin luz", "Sobre fachada o sobre panel"], img: "fachada-03.jpg", faqs: [
        { q: "¿Qué es un rótulo corpóreo?", a: "Es un rótulo formado por letras o formas con volumen, recortadas una a una, que se colocan directamente sobre la fachada o sobre un panel. Se pueden hacer con o sin iluminación." },
        { q: "¿De qué materiales se hacen?", a: "Habitualmente en PVC, metacrilato, aluminio o composite, según el acabado, la resistencia y el presupuesto. Te proponemos el material que mejor encaje con tu fachada y con tu marca." },
        { q: "¿Se pueden iluminar?", a: "Sí. Pueden llevar iluminación LED, por ejemplo retroiluminada (efecto halo) o frontal, o ir sin luz." },
      ] },
      { id: "neon", h2: "Rótulos neón", kicker: "Neón LED flexible", text: "Neón LED flexible a medida con tu logotipo, una frase o un dibujo sencillo. Cuanto más simple es el trazo, mejor se ve el resultado.", specs: ["Neón LED flexible", "Logotipo, frase o dibujo", "Interior o exterior, según modelo"], img: "fachada-02.jpg", faqs: [
        { q: "¿El neón es de cristal o de LED?", a: "Hoy lo habitual es el neón LED flexible, que imita el aspecto del neón clásico con menos consumo y más resistencia. Dinos qué efecto buscas y te orientamos." },
        { q: "¿Sirven para exterior?", a: "Depende del modelo y de la protección del conjunto. Los hay pensados para interior y otros preparados para exterior; te indicamos cuál usar según dónde lo vayas a colocar." },
        { q: "¿Puedo pedir mi logotipo o una frase en neón?", a: "Sí. Fabricamos neón a medida con tu logotipo, una frase o un dibujo sencillo. Cuanto más simple es el trazo, mejor se ve el resultado." },
      ] },
      { id: "luminosos", h2: "Rótulos luminosos", kicker: "Cajas de luz LED", text: "Rótulos luminosos con iluminación LED: cajones con cara iluminada, banderolas y letras iluminadas. Te decimos cuál encaja según tu fachada y tu presupuesto.", specs: ["Cajones, banderolas y letras iluminadas", "Iluminación LED", "Según fachada y presupuesto"], img: "fachada-02.jpg", faqs: [
        { q: "¿Qué tipos de rótulos luminosos hacéis?", a: "Hacemos rótulos luminosos con iluminación LED, como cajones con cara iluminada, banderolas y letras iluminadas. Te decimos cuál encaja según tu fachada y tu presupuesto." },
        { q: "¿Consumen mucho?", a: "La iluminación LED consume bastante menos que las tecnologías antiguas. El consumo concreto depende del tamaño y de las horas de encendido." },
        { q: "¿Se pueden programar para que se enciendan solos?", a: "Sí, se pueden conectar a un temporizador o un sistema de control para que se enciendan y apaguen a las horas que elijas." },
      ] },
      { id: "sin-iluminacion", h2: "Rótulos sin iluminación", kicker: "Corte, dibond y vinilo", text: "La opción más sencilla cuando el local abre sobre todo de día o no quieres instalación eléctrica. Composite, PVC, aluminio, metacrilato o vinilo sobre soporte rígido.", specs: ["Composite, PVC, aluminio, metacrilato o vinilo", "Sin instalación eléctrica", "Imagen cuidada y duradera"], img: "fachada-04.jpg", faqs: [
        { q: "¿Cuándo compensa un rótulo sin luz?", a: "Cuando tu local abre sobre todo de día, cuando no quieres instalación eléctrica o cuando buscas la opción más sencilla y económica. Sigue siendo una imagen cuidada y duradera." },
        { q: "¿Qué materiales se usan?", a: "Composite, PVC, aluminio, metacrilato o vinilo sobre soporte rígido, según el estilo y el lugar de colocación." },
        { q: "¿Se puede añadir luz más adelante?", a: "Depende del diseño. Si lo sabes desde el principio, lo preparamos para poder ampliarlo; si no, consulta con nosotros qué es posible." },
      ] },
      { id: "mantenimiento", h2: "Mantenimiento y reparación", kicker: "Rótulos existentes", text: "Revisamos y reparamos rótulos, los hayamos instalado nosotros o no. LED, transformadores, piezas sueltas, cableado y desgaste por sol o humedad.", specs: ["Revisión y reparación", "También si no es nuestro", "Fotos y descripción de la avería"], img: "hero-taller.jpg", faqs: [
        { q: "¿Reparáis rótulos que no habéis instalado vosotros?", a: "Sí, en la mayoría de casos podemos revisarlos y repararlos. Envíanos fotos del rótulo y una descripción de la avería y te decimos qué se puede hacer." },
        { q: "¿Qué averías suelen tener los rótulos?", a: "Las más habituales son LED o transformadores fundidos, letras o piezas sueltas, cableado deteriorado y desgaste por el sol o la humedad." },
        { q: "¿Es mejor reparar o cambiar el rótulo?", a: "Depende del estado del rótulo y del coste. Si la reparación no compensa, te lo decimos y te planteamos una alternativa." },
      ] },
    ],
    processH2: "Cómo encargar un rótulo en 4 pasos",
    processLead: "Del archivo vectorial o una foto del local al rótulo instalado.",
    process: processDefault,
    casesH2: "Rótulos instalados recientemente",
    cases: [
      { img: "caso-01.jpg", tag: "Corpóreas", title: "Letras halo en retail", sub: "Acero + LED indirecto" },
      { img: "caso-02.jpg", tag: "Luminoso", title: "Caja de luz de nave", sub: "Gran formato LED" },
      { img: "caso-03.jpg", tag: "Neón", title: "Neón de interior", sub: "Logo en neón LED" },
      { img: "caso-04.jpg", tag: "Sin luz", title: "Placa composite", sub: "Corte CNC + vinilo" },
    ],
    faqH2: "Preguntas frecuentes sobre rótulos",
    faqs: [
      { q: "¿Qué tipo de rótulo me conviene?", a: "Depende de tu local, de si necesitas que se vea de noche y del estilo de tu marca. Como referencia: los corpóreos dan un acabado con volumen y aspecto premium, el neón aporta personalidad, los luminosos destacan de noche y los rótulos sin iluminación son la opción más sencilla. Cuéntanos tu caso y te recomendamos." },
      { q: "¿Podéis fabricar el rótulo y montarlo?", a: "Sí. Nos ocupamos del diseño, la fabricación y el montaje. También podemos entregarte el rótulo terminado si prefieres colgarlo tú o con tu propio montador." },
      { q: "¿Puedo usar mi propio logotipo?", a: "Sí. Lo ideal es un archivo vectorial (PDF, AI o SVG). Si solo tienes una imagen, lo revisamos y vemos si se puede rehacer para producción." },
      { q: "¿Necesito licencia para colocar un rótulo?", a: "En general sí: rotular una fachada suele requerir comunicación o licencia municipal, y los requisitos cambian según el ayuntamiento. Lo gestiona normalmente el cliente; si lo necesitas, contamos con un arquitecto que puede encargarse." },
      { q: "¿Cómo se calcula el precio de un rótulo?", a: "Depende del tipo, del tamaño, de los materiales, de la iluminación y de si incluye montaje. Por eso trabajamos con presupuesto a medida: envíanos fotos y medidas aproximadas y te lo preparamos." },
    ],
    contactH2: "¿Qué tipo de rótulo necesita tu negocio?",
    contactLead: "Cuéntanos si buscas corpóreas, neón, caja de luz, rotulación sin iluminación, o mantenimiento y reparación de un rótulo que ya está instalado. Te respondemos en 24 h con propuesta y precio.",
  },

  "impresion-digital": {
    slug: "impresion-digital",
    breadcrumb: "Impresión digital y gran formato",
    eyebrow: "Vinilo, lona y gran formato de alta durabilidad",
    h1Before: "Impresión digital: color fiel, gran formato y",
    h1Accent: "resistencia a la intemperie",
    lead: "Imprimimos vinilos adhesivos, lonas, canvas y gráficos de gran formato para fachadas, vehículos, interiores y eventos. Tinta de exterior, laminados de protección y color corporativo controlado.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "palette", title: "Color fiel", sub: "Perfilado de marca" },
      { icon: "wb_sunny", title: "Exterior", sub: "UV y laminado" },
      { icon: "square_foot", title: "Gran formato", sub: "Sin límite práctico" },
    ],
    ctaPrimary: "Pedir presupuesto de impresión",
    ctaSecondary: "Ver soportes",
    trust: "Impresión y aplicación por el mismo taller que fabrica tus rótulos.",
    heroImg: "hero-taller.jpg",
    heroBadge: "Gran formato de producción propia",
    heroTitle: "De archivo a pared",
    heroSub: "Vinilo, lona, canvas y microperforado",
    heroStat: "7+",
    heroStatLabel: "Años de garantía UV",
    whyEyebrow: "Por qué imprimir con quien también instala",
    whyH2: "La impresión solo funciona si el soporte, el laminado y el montaje están pensados juntos",
    whyLead: "No entregamos un rollo y desaparecemos: calibramos, laminamos y, si quieres, lo instalamos.",
    benefits: [
      { icon: "palette", kicker: "01 / Color", title: "Tu marca, no una aproximación", text: "Perfiles de color y pruebas para acercarnos a Pantone y artes finales.", tag: "Control de color" },
      { icon: "water_drop", kicker: "02 / Exterior", title: "Aguanta sol y lluvia", text: "Vinilos poliméricos, fundición y laminados antigrafiti o de suelo según uso.", tag: "Material de exterior" },
      { icon: "photo_size_select_large", kicker: "03 / Escala", title: "Del A3 a la lona de nave", text: "Gran formato continuo para testeros, andamios, eventos y escaparates.", tag: "Sin parches visibles" },
      { icon: "handyman", kicker: "04 / Instalación", title: "Aplicación profesional", text: "El mismo equipo que rotula vehículos y fachadas aplica el vinilo en obra.", tag: "Llave en mano" },
    ],
    solutionsH2: "Soportes de impresión que trabajamos",
    solutionsLead: "Elegimos el material según si va a pared, cristal, vehículo o suelo.",
    solutions: [
      { tag: "01 · Fachada y pared", tech: "Vinilo polimérico", title: "Vinilos adhesivos de interior y exterior", text: "Corte y recorte, fondos impresos y laminados mate o brillo para durar en calle.", a: "Uso", av: "Paredes, composite, aluminio", b: "Protección", bv: "Laminado UV / antigrafiti", img: "fachada-04.jpg", cap: "Aplicación sin burbujas" },
      { tag: "02 · Lona", tech: "Backlight / frontlit", title: "Lonas publicitarias y de andamio", text: "Gran formato soldado, ollados y refuerzos para viento. También backlight para cajas de luz.", a: "Acabado", av: "Ollados, caras, soldadura", b: "Formato", bv: "Fachadas y vallas", img: "fachada-02.jpg", cap: "Impresión de gran formato" },
      { tag: "03 · Cristal", tech: "Microperforado", title: "Vinilo de luna y microperforado", text: "Se ve desde dentro hacia la calle, con publicidad por fuera. Homologado para vehículos y escaparates.", a: "Visión", av: "One-way vision", b: "Uso", bv: "Escaparates y flotas", img: "fachada-01.jpg", cap: "Privacidad + marca" },
      { tag: "04 · Interior", tech: "Canvas / rígido", title: "Canvas, foam y paneles rígidos", text: "Cuadros, fotomurales y soportes rígidos para oficinas, retail y stands.", a: "Base", av: "Foam, dibond, canvas", b: "Acabado", bv: "Corte a medida", img: "caso-01.jpg", cap: "Listo para colgar" },
    ],
    processH2: "De tu archivo al soporte instalado",
    processLead: "Revisamos artes, sangrados y resoluciones antes de imprimir.",
    process: processDefault,
    casesH2: "Trabajos de gran formato",
    cases: [
      { img: "caso-01.jpg", tag: "Retail", title: "Escaparate integral", sub: "Vinilo + microperforado" },
      { img: "caso-02.jpg", tag: "Industrial", title: "Lona de nave", sub: "Gran formato exterior" },
      { img: "caso-03.jpg", tag: "Oficina", title: "Fotomural", sub: "Canvas y rígido" },
      { img: "caso-04.jpg", tag: "Evento", title: "Photocall", sub: "Lona tensada" },
    ],
    faqH2: "Preguntas frecuentes de impresión digital",
    faqs: [
      { q: "¿Qué puedo imprimir?", a: "Adhesivos y pegatinas, vinilos para escaparates y paredes, rotulación para vehículos, cartelería, carteles y otros soportes de gran formato. Si tienes una idea que no encaja en esta lista, pregúntanos." },
      { q: "¿Qué tipos de vinilo utilizáis?", a: "Trabajamos varios: monomérico (una opción económica para uso promocional y de corta o media duración), polimérico (pensado para larga duración), transparente y de alta adherencia para superficies difíciles. Te recomendamos el más adecuado según dónde vaya a ir colocado." },
      { q: "¿Los adhesivos se pueden laminar?", a: "Sí. El laminado protege la impresión y alarga su vida, y se ofrece en acabado brillo o mate." },
      { q: "¿Puedo pedir adhesivos con la forma de mi diseño?", a: "Sí, se pueden cortar por la silueta del dibujo, además de con formas sencillas como recta, redondeada, circular u ovalada." },
      { q: "¿Hay un pedido mínimo?", a: "En adhesivos, el pedido mínimo es de 1 m². Cuantos más metros pides, mayor es el descuento por volumen." },
      { q: "¿Qué archivo tengo que enviaros?", a: "Lo ideal es un PDF o un archivo vectorial (AI o SVG) con los textos convertidos a curvas. Si solo tienes una imagen, cuéntanoslo y te decimos si tiene calidad suficiente para el tamaño que necesitas." },
      { q: "¿Los precios incluyen IVA?", a: "Nuestras tarifas se indican sin IVA; a ellas se aplica el 21 % de IVA." },
    ],
    contactH2: "¿Tienes un arte o una medida y quieres precio?",
    contactLead: "Envía el archivo o las medidas aproximadas a proyectos@vexil.es. Presupuesto en 24 h.",
  },

  vehiculos: {
    slug: "vehiculos",
    breadcrumb: "Rotulación de vehículos",
    eyebrow: "Decoración y personalización con vinilo fundido",
    h1Before: "Rotulación de vehículos: tu diseño,",
    h1Accent: "en vinilo fundido",
    lead: "Nos centramos en la decoración y personalización de vehículos para particulares: franjas, logotipos, textos, dibujos y detalles en puertas, laterales, capó o luneta. Vinilo fundido, pensado para adaptarse a las formas del vehículo.",
    pills: [
      { icon: "timer", title: "Presupuesto a medida", sub: "Sin compromiso" },
      { icon: "directions_car", title: "Particulares", sub: "Tu vehículo, tu diseño" },
      { icon: "verified", title: "Vinilo fundido", sub: "Se adapta a la carrocería" },
      { icon: "design_services", title: "Tu diseño o el nuestro", sub: "Lo revisamos contigo" },
    ],
    ctaPrimary: "Pedir presupuesto de rotulación",
    ctaSecondary: "Ver qué se puede rotular",
    trust: "Vinilo fundido para franjas, logos, textos y detalles. Duración según sol y cuidado del vehículo.",
    heroImg: "hero-taller.jpg",
    heroBadge: "Vinilo fundido",
    heroTitle: "Decoración de vehículo",
    heroSub: "Franjas, logos y textos",
    heroStat: "A medida",
    heroStatLabel: "Según tu idea",
    whyEyebrow: "Personalización, no cambio de color",
    whyH2: "Franjas, logos y detalles que se leen en tu vehículo",
    whyLead: "Cuéntanos qué vehículo tienes y qué idea tienes en mente. Revisamos el diseño y te proponemos cómo llevarlo a cabo.",
    benefits: [
      { icon: "brush", kicker: "01 / Diseño", title: "Tu idea o la nuestra", text: "Puedes traer tu diseño o lo creamos contigo. Lo ideal es un archivo vectorial o una imagen con buena resolución.", tag: "Lo revisamos antes" },
      { icon: "layers", kicker: "02 / Material", title: "Vinilo fundido", text: "Un material pensado para adaptarse bien a las formas del vehículo y con buena durabilidad, según la exposición al sol y el cuidado.", tag: "Se adapta a la carrocería" },
      { icon: "format_paint", kicker: "03 / Pintura", title: "Retirada cuidadosa", text: "Si la pintura está en buen estado y el vinilo se retira correctamente, no debería dañarse. Si hay repintados o golpes, lo revisamos antes.", tag: "Lo vemos en el vehículo" },
      { icon: "local_car_wash", kicker: "04 / Cuidado", title: "Cómo mantenerlo", text: "Evita el agua a presión muy cerca de los bordes y usa productos neutros. Un lavado regular ayuda a que dure más al sol.", tag: "Consejos al entregar" },
    ],
    solutionsH2: "Qué rotulamos en el vehículo",
    solutionsLead: "Decoración y personalización por zonas. Cuéntanos el modelo y la idea.",
    solutions: [
      { tag: "01 · Franjas", tech: "Vinilo fundido", title: "Franjas y detalles", text: "Líneas, formas y acentos en laterales, capó o zócalo, recortados a medida de tu vehículo.", a: "Uso", av: "Turismos y furgones", b: "Material", bv: "Vinilo fundido", img: "caso-02.jpg", cap: "Detalle de corte" },
      { tag: "02 · Logo", tech: "Corte o impresión", title: "Logotipos y textos", text: "Nombre, teléfono, web o el dibujo que quieras, en puertas, laterales o luna.", a: "Archivo", av: "Vector o imagen nítida", b: "Colocación", bv: "Donde mejor se lea", img: "hero-taller.jpg", cap: "Tu marca en el vehículo" },
      { tag: "03 · Puertas", tech: "Zonas", title: "Puertas, laterales y capó", text: "Rotulamos las piezas que elijas, no hace falta cubrir el vehículo entero.", a: "Alcance", av: "La zona que pidas", b: "Acabado", bv: "Corte limpio", img: "caso-01.jpg", cap: "Por piezas" },
      { tag: "04 · Luneta", tech: "Luna", title: "Detalles en luneta", text: "Textos o gráficos en la luna, cuando el diseño y la visibilidad lo permiten. Lo revisamos en tu vehículo.", a: "Visibilidad", av: "La valoramos antes", b: "Diseño", bv: "A medida", img: "fachada-04.jpg", cap: "Luneta y laterales" },
    ],
    processH2: "Cómo rotulamos tu vehículo",
    processLead: "Nos enseñas el vehículo y la idea. Revisamos pintura y diseño, y te presupuestamos.",
    process: processDefault,
    casesH2: "Vehículos rotulados",
    cases: [
      { img: "caso-02.jpg", tag: "Laterales", title: "Furgoneta", sub: "Logo y textos" },
      { img: "caso-01.jpg", tag: "Puertas", title: "Turismo", sub: "Franjas y detalle" },
      { img: "caso-04.jpg", tag: "Capó", title: "Personalización", sub: "Vinilo fundido" },
      { img: "hero-taller.jpg", tag: "Diseño", title: "A medida", sub: "Tu archivo o el nuestro" },
    ],
    faqH2: "Preguntas frecuentes de rotulación de vehículos",
    faqs: [
      { q: "¿Qué tipo de rotulación de vehículos hacéis?", a: "Nos centramos en la decoración y personalización de vehículos para particulares: franjas, logotipos, textos, dibujos y detalles en puertas, laterales, capó o luneta. Cuéntanos qué vehículo tienes y qué idea tienes en mente." },
      { q: "¿Qué vinilo utilizáis?", a: "Usamos vinilo fundido, un material pensado para adaptarse bien a las formas del vehículo y con buena durabilidad. Su duración depende de la exposición al sol y de cómo cuides el vehículo." },
      { q: "¿Puedo llevar mi propio diseño?", a: "Sí. Puedes traer tu diseño o lo creamos contigo. Lo ideal es un archivo vectorial o una imagen con buena resolución; si tienes dudas, enséñanoslo y lo revisamos." },
      { q: "¿Se estropea la pintura al quitar el vinilo?", a: "Si la pintura está en buen estado y el vinilo se retira correctamente, no debería dañarse. Si el vehículo tiene repintados, golpes o pintura deteriorada, puede haber diferencias; lo revisamos antes de empezar." },
      { q: "¿Cómo cuido un vehículo rotulado?", a: "Evita lavarlo a presión muy cerca de los bordes del vinilo y utiliza productos neutros. Si lo tienes muy expuesto al sol, un lavado y cuidado regulares ayudan a que dure más." },
    ],
    contactH2: "¿Quieres rotular tu vehículo?",
    contactLead: "Envía modelo del vehículo, fotos y la idea o el archivo. Te preparamos presupuesto.",
  },

  interiores: {
    slug: "interiores",
    breadcrumb: "Decoración de interiores",
    eyebrow: "Murales, vinilos y marca en el espacio",
    h1Before: "Decoración de interiores: espacios que",
    h1Accent: "hablan de tu marca",
    lead: "Vinilos texturizados, fotomurales, lettering y paneles para oficinas, tiendas, clínicas y hostelería. El mismo lenguaje visual que tu fachada, aplicado al interior.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "apartment", title: "A medida", sub: "Pared a pared" },
      { icon: "volume_off", title: "Acústicos", sub: "Paneles opcionales" },
      { icon: "brush", title: "Marca", sub: "Manual de identidad" },
    ],
    ctaPrimary: "Pedir presupuesto de interiores",
    ctaSecondary: "Ver aplicaciones",
    trust: "Interiorismo de marca para locales que ya tienen (o van a tener) fachada Vexil.",
    heroImg: "caso-01.jpg",
    heroBadge: "Marca aplicada al espacio",
    heroTitle: "Recepción y sala",
    heroSub: "Mural + lettering + vinilo de corte",
    heroStat: "360°",
    heroStatLabel: "Experiencia de marca",
    whyEyebrow: "El interior también vende",
    whyH2: "Quien entra debe reconocer la misma marca que ha visto en la calle",
    whyLead: "Coherencia entre rótulo, fachada y pared interior: un solo criterio gráfico.",
    benefits: [
      { icon: "storefront", kicker: "01 / Retail", title: "Tiendas que se recuerdan", text: "Muros de producto, lettering y vinilos de suelo o cristalera interior.", tag: "Experiencia de compra" },
      { icon: "corporate_fare", kicker: "02 / Oficinas", title: "Cultura visible", text: "Logos, frases y gráficos de marca en recepciones y salas.", tag: "Branding interno" },
      { icon: "medical_services", kicker: "03 / Clínicas", title: "Confianza y calma", text: "Materiales lavables, lettering discreto y color controlado.", tag: "Espacios sanitarios" },
      { icon: "restaurant", kicker: "04 / Hostelería", title: "Ambiente con identidad", text: "Neón de interior, murales y cartas en pared sin saturación visual.", tag: "Local con carácter" },
    ],
    solutionsH2: "Aplicaciones de interior",
    solutionsLead: "Del vinilo de corte al mural impreso a pared completa.",
    solutions: [
      { tag: "01 · Pared", tech: "Gran formato", title: "Fotomurales y vinilos de pared", text: "Impresión a medida, juntas controladas y aplicación profesional.", a: "Soporte", av: "Vinilo mural / canvas", b: "Uso", bv: "Salas, tiendas, pasillos", img: "caso-01.jpg", cap: "Pared a pared" },
      { tag: "02 · Lettering", tech: "Corte", title: "Vinilo de corte y letras interiores", text: "Tipografías de marca en recepción, cristales y puertas.", a: "Material", av: "Vinilo de corte mate/brillo", b: "Relieve", bv: "Opción corpóreas interiores", img: "fachada-03.jpg", cap: "Marca a escala humana" },
      { tag: "03 · Cristal", tech: "Arenado / lamas", title: "Privacidad en cristaleras", text: "Efecto ácido, lamas y logos para salas. La lámina solar y el vinilo ácido a fondo están en su propia página de servicio.", a: "Función", av: "Intimidad + marca", b: "Ver también", bv: "Lámina solar y vinilos ácidos", img: "fachada-04.jpg", cap: "Vidrio con identidad" },
      { tag: "04 · Relieves", tech: "CNC", title: "Logos y paneles en relieve", text: "Corpóreas de interior, logos fresados y paneles decorativos.", a: "Material", av: "PVC, madera, metacrilato", b: "Luz", bv: "Opcional LED o neón", img: "fachada-01.jpg", cap: "Punto focal de recepción" },
    ],
    processH2: "Cómo vestimos un interior",
    processLead: "Medimos, proponemos y instalamos con el local en funcionamiento.",
    process: processDefault,
    casesH2: "Interiores resueltos",
    cases: [
      { img: "caso-01.jpg", tag: "Retail", title: "Tienda de marca", sub: "Mural + lettering" },
      { img: "caso-03.jpg", tag: "Clínica", title: "Recepción", sub: "Vinilo + logo relieve" },
      { img: "caso-04.jpg", tag: "Oficina", title: "Sala de reuniones", sub: "Cristal arenado" },
      { img: "fachada-hero.jpg", tag: "Hostelería", title: "Barra y sala", sub: "Neón + mural" },
    ],
    faqH2: "Preguntas frecuentes de interiores",
    faqs: [
      { q: "¿Qué se puede decorar con vinilo o impresión?", a: "Paredes, cristales, mamparas, mostradores, puertas y mobiliario, entre otros. Sirve tanto para dar imagen de marca a un negocio como para decorar una vivienda." },
      { q: "¿Podéis poner mi logotipo o un mural en la pared?", a: "Sí. Imprimimos tu diseño en el material adecuado y lo instalamos, o te lo entregamos listo para que lo coloques tú." },
      { q: "¿Qué superficies admiten el vinilo?", a: "Cuanto más lisa, limpia y firme es la superficie, mejor se adhiere. Las paredes con textura marcada, humedad o pintura suelta pueden necesitar preparación o un material distinto; lo revisamos antes de proponerte una solución." },
      { q: "¿Se puede quitar sin dañar la pared?", a: "Depende de la superficie y del vinilo utilizado. Sobre paredes pintadas en buen estado suele poder retirarse, pero no podemos asegurarlo en todos los casos, así que lo valoramos contigo antes de empezar." },
      { q: "¿Hacéis trabajos para oficinas, tiendas y restaurantes?", a: "Sí. Trabajamos con negocios de distintos sectores: oficinas, comercios, hostelería y otros espacios de atención al público." },
      { q: "¿Cómo empiezo?", a: "Envíanos fotos del espacio, medidas aproximadas y una idea de lo que quieres conseguir. Con eso te proponemos soluciones y un presupuesto." },
    ],
    contactH2: "¿Quieres que el interior coincida con tu fachada?",
    contactLead: "Envía fotos del espacio y el logo. Te proponemos materiales y un precio cerrado.",
  },

  "lamina-solar": {
    slug: "lamina-solar",
    variant: "types",
    breadcrumb: "Lámina solar y vinilos ácidos",
    eyebrow: "Cristal arquitectónico · control solar, privacidad y efecto ácido",
    h1Before: "Lámina solar y vinilos ácidos: arquitectura,",
    h1Accent: "privacidad y confort",
    lead: "Instalamos lámina solar en fachadas acristaladas, oficinas y locales, lámina de privacidad y vinilos de efecto ácido. Menos calor y deslumbramiento, más intimidad y un acabado de arquitectura, sin cambiar el vidrio.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "wb_sunny", title: "Control solar", sub: "Calor y UV" },
      { icon: "visibility_off", title: "Privacidad", sub: "Sin perder luz" },
      { icon: "window", title: "Efecto ácido", sub: "Arenado a medida" },
    ],
    ctaPrimary: "Pedir presupuesto de lámina solar",
    ctaSecondary: "Ver tipos de lámina y vinilo",
    trust: "Aplicación profesional en obra, oficinas, clínicas, retail y vivienda.",
    heroImg: "fachada-04.jpg",
    heroBadge: "Cristal tratado, no sustituido",
    heroTitle: "Fachada y cristalera",
    heroSub: "Solar + privacidad + ácido",
    heroStat: "UV",
    heroStatLabel: "Filtro y confort",
    whyEyebrow: "Por qué tratar el cristal y no cambiarlo",
    whyH2: "La lámina resuelve calor, vis-à-vis y estética sobre el vidrio que ya tienes",
    whyLead: "En arquitectura nueva o reforma: control solar, intimidad y grafismo de efecto ácido, instalados en seco y reversibles si el proyecto lo pide.",
    benefits: [
      { icon: "thermostat", kicker: "01 / Confort", title: "Menos calor y deslumbramiento", text: "La lámina solar arquitectónica recorta radiación infrarroja y UV. Oficinas y locales más habitables, con menos carga de climatización.", tag: "Control térmico" },
      { icon: "visibility_off", kicker: "02 / Privacidad", title: "Se ve sin ser visto", text: "Láminas de privacidad diurna, mirror y degradados para clínicas, despachos y plantas bajas. Luz natural, sin escaparate a la calle.", tag: "Intimidad" },
      { icon: "architecture", kicker: "03 / Arquitectura", title: "El alzado no cambia de carpintería", text: "Actuamos sobre el vidrio existente: fachadas curtain wall, lucernarios, mamparas y escaparates, coordinados con el estudio o la obra.", tag: "Sin obra de vidrio" },
      { icon: "design_services", kicker: "04 / Marca", title: "Ácido, lamas y logos", text: "Vinilo de efecto arenado a medida: franjas, tramas y tipografía. Privacidad con el mismo criterio gráfico que el resto del local.", tag: "Vinilos ácidos" },
    ],
    typesH2Intro: "Tipos de lámina y vinilo para cristal",
    typesLead: "Tres soluciones sobre vidrio. Elige por confort, vis-à-vis o estética; a menudo se combinan en la misma fachada.",
    types: [
      { id: "arquitectura", h2: "Lámina solar arquitectónica", kicker: "Control solar en edificio", text: "Ayuda a reducir el calor y el deslumbramiento en el interior, y a proteger del sol el mobiliario y las superficies. Habitual en oficinas, comercios y viviendas con mucha exposición solar.", specs: ["Calor y deslumbramiento", "Oficinas, comercios y viviendas", "Modelos más claros o más oscuros"], img: "fachada-hero.jpg", faqs: [
        { q: "¿Qué ventajas tiene en un edificio o local?", a: "Ayuda a reducir el calor y el deslumbramiento en el interior, y a proteger del sol el mobiliario y las superficies. Es una opción habitual en oficinas, comercios y viviendas con mucha exposición solar." },
        { q: "¿Oscurece mucho el interior?", a: "Depende del modelo: los hay más claros y más oscuros. Te ayudamos a elegir el equilibrio entre control del sol y luz natural." },
        { q: "¿Protege de los rayos UV?", a: "Muchas láminas reducen también la radiación UV, aunque el porcentaje depende de cada modelo. Te informamos de las características del que elijamos." },
      ] },
      { id: "privacidad", h2: "Lámina solar de privacidad", kicker: "Intimidad con luz natural", text: "Privacidad en despachos, salas de reuniones y consultas. El efecto depende del modelo y de la luz: de día, de noche o a cualquier hora, según la lámina.", specs: ["Espejo, esmerilada o translúcida", "Despachos, reuniones y consultas", "Luz natural sin miradas directas"], img: "caso-03.jpg", faqs: [
        { q: "¿Se puede ver desde fuera?", a: "Depende del modelo y de la luz. Algunas láminas de espejo o reflectantes limitan la visión desde fuera durante el día, pero de noche con luz interior el efecto puede invertirse. Otras opciones, como las esmeriladas, dan privacidad a cualquier hora." },
        { q: "¿Qué opciones hay para dar privacidad sin oscurecer?", a: "Las láminas esmeriladas o translúcidas dejan pasar la luz y evitan las miradas directas. También se pueden hacer diseños o bandas para mantener parte del cristal despejada." },
        { q: "¿Sirve para despachos, salas de reuniones y consultas?", a: "Sí. Es una solución habitual para espacios donde interesa cuidar la intimidad sin perder la luz natural." },
      ] },
      { id: "vinilos-acidos", h2: "Vinilos ácidos", kicker: "Efecto arenado a medida", text: "Vinilo que imita el cristal grabado al ácido: acabado esmerilado, elegante y translúcido, sin tratar el vidrio. Logotipos, textos, bandas y patrones a medida.", specs: ["Imita el grabado al ácido", "Logos, textos y bandas", "Se coloca y se puede retirar"], img: "fachada-04.jpg", faqs: [
        { q: "¿Qué es un vinilo ácido?", a: "Es un vinilo que imita el aspecto del cristal grabado al ácido: da un acabado esmerilado, elegante y translúcido, sin necesidad de tratar el vidrio." },
        { q: "¿Puedo poner mi logotipo o un diseño?", a: "Sí. Lo cortamos con la forma que quieras: logotipos, textos, bandas, patrones y diseños a medida." },
        { q: "¿Es lo mismo que grabar el cristal?", a: "No. El vinilo ácido imita el aspecto del grabado, pero se coloca sobre el cristal y puede retirarse o cambiarse. Es una alternativa más rápida y económica que tratar el vidrio." },
      ] },
    ],
    processH2: "Cómo instalamos lámina y vinilo en cristal",
    processLead: "Medimos el vidrio, elegimos film y diseño, y aplicamos en húmedo con el local en uso cuando es posible.",
    process: processDefault,
    casesH2: "Cristales tratados recientemente",
    cases: [
      { img: "fachada-hero.jpg", tag: "Arquitectura", title: "Fachada de oficinas", sub: "Lámina solar neutra" },
      { img: "caso-03.jpg", tag: "Privacidad", title: "Clínica", sub: "Mirror + ácido en consultas" },
      { img: "fachada-04.jpg", tag: "Ácido", title: "Escaparate retail", sub: "Lamas y logo arenado" },
      { img: "caso-04.jpg", tag: "Oficina", title: "Sala de reuniones", sub: "Vinilo ácido a medida" },
    ],
    faqH2: "Preguntas frecuentes de lámina solar y vinilos ácidos",
    faqs: [
      { q: "¿Qué es la lámina solar?", a: "Es una lámina que se adhiere al cristal para reducir el calor y el deslumbramiento que entran por las ventanas. También puede aportar privacidad, según el modelo." },
      { q: "¿Se puede colocar en cualquier cristal?", a: "En la mayoría de cristales sí, pero algunos tipos de vidrio pueden sufrir tensiones térmicas con determinadas láminas. Revisamos tu cristal antes de proponerte un modelo." },
      { q: "¿Se coloca por dentro o por fuera?", a: "Depende del tipo de lámina y del cristal. Lo más habitual es colocarla por el interior, pero te indicamos la mejor opción en cada caso." },
      { q: "¿Se puede quitar?", a: "Sí, se puede retirar. Con el tiempo el adhesivo puede dejar restos, que se eliminan con el producto adecuado." },
      { q: "¿Cómo se limpia un cristal con lámina?", a: "Con un paño suave y un producto neutro, sin estropajos ni productos abrasivos. Se recomienda esperar unos días tras la colocación antes de la primera limpieza; te indicamos el plazo exacto al terminar." },
    ],
    contactH2: "¿Fachada acristalada, vis-à-vis o efecto ácido?",
    contactLead: "Envía fotos del cristal y la orientación (si la sabes) a proyectos@vexil.es. Te decimos lámina solar, privacidad, vinilo ácido o la combinación, con precio.",
  },

  corte: {
    slug: "corte",
    breadcrumb: "Corte a medida · CNC y láser",
    eyebrow: "Mecanizado propio: CNC y láser en el mismo taller",
    h1Before: "Corte a medida: CNC y láser para piezas",
    h1Accent: "que no salen de catálogo",
    lead: "Fresado CNC y corte láser de aluminio, PVC, madera, metacrilato y composite. Unimos ambas tecnologías en un solo servicio: de la silueta fina al mecanizado estructural.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "precision_manufacturing", title: "CNC", sub: "Fresado y 2.5D" },
      { icon: "flare", title: "Láser", sub: "Corte y grabado" },
      { icon: "category", title: "A medida", sub: "Sin series mínimas" },
    ],
    ctaPrimary: "Pedir presupuesto de corte",
    ctaSecondary: "Ver materiales",
    trust: "La misma maquinaria que fabrica letras corpóreas y paneles de fachada.",
    heroImg: "hero-taller.jpg",
    heroBadge: "Taller CNC + láser",
    heroTitle: "Pieza única o serie corta",
    heroSub: "Metacrilato, PVC, aluminio, madera",
    heroStat: "A medida",
    heroStatLabel: "CNC y láser",
    whyEyebrow: "Por qué unir CNC y láser",
    whyH2: "Cada material y cada espesor pide una máquina distinta. Nosotros tenemos las dos.",
    whyLead: "El láser da canto vivo y detalle. El CNC da ranuras, espesor y piezas estructurales.",
    benefits: [
      { icon: "flare", kicker: "01 / Láser", title: "Detalle y canto pulido", text: "Logos finos, placas, metacrilato y grabado con borde limpio.", tag: "Alta precisión" },
      { icon: "precision_manufacturing", kicker: "02 / CNC", title: "Volumen y ranurado", text: "Bandejas de fachada, letras gruesas, cajeados y 2.5D.", tag: "Mecanizado propio" },
      { icon: "inventory_2", kicker: "03 / Materiales", title: "De un mismo almacén", text: "PVC, dibond, aluminio, madera, DM, metacrilato y más.", tag: "Stock de placa" },
      { icon: "handyman", kicker: "04 / Acabado", title: "Listo para instalar", text: "No solo cortamos: lacamos, montamos LED y entregamos pieza fina.", tag: "Pieza terminada" },
    ],
    solutionsH2: "Qué cortamos y fresamos",
    solutionsLead: "Un servicio, dos tecnologías, el material que pida el proyecto.",
    solutions: [
      { tag: "01 · Láser", tech: "Corte y grabado", title: "Corte láser de alta precisión", text: "Metacrilato, madera fina, cartón y grabado de placas. Bordes limpios para logos y señalética.", a: "Ideal para", av: "Placas, logos, maquetas", b: "Acabado", bv: "Canto pulido / grabado", img: "plano-totem.jpg", cap: "Detalle de canto" },
      { tag: "02 · CNC", tech: "Fresado", title: "Fresado CNC a medida", text: "Composite, PVC, aluminio y maderas para letras, bandejas y piezas de stand.", a: "Ideal para", av: "Corpóreas, bandejas, 2.5D", b: "Espesor", bv: "Según material", img: "hero-taller.jpg", cap: "Mecanizado de taller" },
      { tag: "03 · Series", tech: "Repetición", title: "Series cortas y recambios", text: "La misma herramienta para 1 pieza o 200 de franquicia.", a: "Repetibilidad", av: "Archivo CNC guardado", b: "Plazo", bv: "Según cola de taller", img: "fachada-01.jpg", cap: "Misma pieza, N veces" },
      { tag: "04 · Conjunto", tech: "Montaje", title: "Corte + luz + instalación", text: "La pieza no se queda en el palé: la integramos en rótulo, stand o fachada.", a: "Siguiente paso", av: "LED, lacado, anclaje", b: "Entrega", bv: "Llave en mano", img: "fachada-03.jpg", cap: "De máquina a obra" },
    ],
    processH2: "De tu DXF o idea a la pieza cortada",
    processLead: "Aceptamos vectores, planos o un croquis. Nosotros preparamos la máquina.",
    process: processDefault,
    casesH2: "Piezas de corte recientes",
    cases: [
      { img: "hero-taller.jpg", tag: "CNC", title: "Letras fresadas", sub: "PVC + lacado" },
      { img: "plano-totem.jpg", tag: "Láser", title: "Placa técnica", sub: "Grabado + corte" },
      { img: "fachada-03.jpg", tag: "Combo", title: "Logo mixto", sub: "CNC + metacrilato" },
      { img: "caso-02.jpg", tag: "Stand", title: "Estructura ligera", sub: "Composite fresado" },
    ],
    faqH2: "Preguntas frecuentes de corte CNC y láser",
    faqs: [
      { q: "¿Qué diferencia hay entre corte CNC y corte láser?", a: "La fresadora CNC corta y talla materiales robustos y de mayor grosor, y es la que usamos para piezas grandes, letras y revestimientos. El láser es más fino y preciso, ideal para grabar y cortar metacrilato y detalles pequeños." },
      { q: "¿Qué materiales podéis cortar?", a: "El CNC trabaja materiales como composite, PVC o madera; el láser corta y graba metacrilato. Si tienes un material concreto en mente, dinos cuál y te confirmamos si podemos trabajarlo." },
      { q: "¿Cuál es el tamaño máximo de pieza?", a: "Podemos fabricar piezas de gran formato, y con solape o uniones llegamos a tamaños mayores. Dinos las medidas que necesitas y te confirmamos cómo lo haríamos." },
      { q: "¿Qué archivo necesito enviar?", a: "Un archivo vectorial (DXF, SVG, AI o PDF vectorial) con las medidas reales y los textos convertidos a curvas. Si solo tienes un boceto o una imagen, podemos ayudarte a prepararlo." },
      { q: "¿Hacéis una sola pieza o solo series?", a: "Hacemos desde una única pieza hasta series. Cuéntanos qué necesitas y te presupuestamos." },
      { q: "¿Podéis fabricar letras corpóreas, composites o revestimientos?", a: "Sí. Fabricamos nosotros mismos letras y formas, composites para revestimientos y otras piezas a medida, para uso propio o para profesionales que necesitan producción." },
      { q: "¿Cómo se calcula el precio?", a: "Depende del material, del tamaño, de la complejidad del corte y de la cantidad. Envía tu archivo o tu idea y te preparamos un presupuesto." },
    ],
    contactH2: "¿Tienes un DXF, un logo o una medida?",
    contactLead: "Escríbenos a proyectos@vexil.es con el material deseado. Te decimos CNC, láser o ambos, y el precio.",
  },

  stands: {
    slug: "stands",
    breadcrumb: "Stands para ferias y eventos",
    eyebrow: "Ferias, congresos y activaciones de marca",
    h1Before: "Stands y eventos: una marca que se",
    h1Accent: "ocupa el espacio",
    lead: "Photocalls, tótems, backdrops, letras de suelo y estructuras para ferias. Diseñamos, cortamos, imprimimos e instalamos el conjunto para que el stand se monte rápido y se lea de lejos.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "event", title: "Plazos feria", sub: "Montaje coordinado" },
      { icon: "inventory_2", title: "Reutilizable", sub: "Guarda y reestrena" },
      { icon: "photo_camera", title: "Photocall", sub: "Listo para foto" },
    ],
    ctaPrimary: "Pedir presupuesto de stand",
    ctaSecondary: "Ver elementos",
    trust: "Producción propia: impresión, corte y rótulos en el mismo pedido de feria.",
    heroImg: "caso-04.jpg",
    heroBadge: "Montaje de feria",
    heroTitle: "Stand modular",
    heroSub: "Backdrop + tótem + letras 3D",
    heroStat: "48h",
    heroStatLabel: "Ventana típica de montaje",
    whyEyebrow: "Un stand no es solo una lona",
    whyH2: "En feria gana quien se lee a 20 metros y se fotografía bien de cerca",
    whyLead: "Combinamos gran formato, corpóreas, iluminación y almacenamiento del kit.",
    benefits: [
      { icon: "visibility", kicker: "01 / Distancia", title: "Se ve desde el pasillo", text: "Tipografía, contraste y altura calculados para recinto ferial.", tag: "Lectura lejana" },
      { icon: "photo_camera", kicker: "02 / Foto", title: "Photocall de verdad", text: "Fondos tensados, iluminación y logo para redes.", tag: "Contenido de marca" },
      { icon: "schedule", kicker: "03 / Tiempo", title: "Montaje en ventana corta", text: "Sistemas pensados para las pocas horas que da el recinto.", tag: "Logística de feria" },
      { icon: "savings", kicker: "04 / Reuso", title: "El kit viaja al siguiente evento", text: "Estructuras desmontables y recambios de lona o vinilo.", tag: "Inversión repetible" },
    ],
    solutionsH2: "Elementos de stand que fabricamos",
    solutionsLead: "Puedes pedir el conjunto o solo el photocall.",
    solutions: [
      { tag: "01 · Fondo", tech: "Tensado", title: "Photocalls y backdrops", text: "Estructura + lona o textil tensado a medida de tu hueco.", a: "Formato", av: "Recto, curvo, modular", b: "Gráfico", bv: "Gran formato propio", img: "caso-04.jpg", cap: "Listo para foto" },
      { tag: "02 · Vertical", tech: "Tótem", title: "Tótems y portabanners", text: "De la pieza ligera al tótem iluminado de producción propia.", a: "Altura", av: "Según recinto", b: "Luz", bv: "Opción LED", img: "plano-totem.jpg", cap: "Señal en pasillo" },
      { tag: "03 · Volumen", tech: "3D", title: "Letras de suelo y logos XL", text: "Corpóreas de feria, corcho, PVC o madera para foto y presencia.", a: "Escala", av: "De mostrador a metro y medio", b: "Acabado", bv: "Lacado / vinilo", img: "fachada-03.jpg", cap: "Marca ocupando el suelo" },
      { tag: "04 · Kit", tech: "Llave en mano", title: "Stand completo de producción propia", text: "Gráfico, corte, rótulo e instalación en el recinto.", a: "Incluye", av: "Diseño + producción + montaje", b: "Extra", bv: "Almacenaje del kit", img: "caso-02.jpg", cap: "Un solo proveedor" },
    ],
    processH2: "Cómo preparamos un evento",
    processLead: "Fecha de feria primero. Hacia atrás, diseño, producción y montaje.",
    process: processDefault,
    casesH2: "Eventos y stands recientes",
    cases: [
      { img: "caso-04.jpg", tag: "Feria", title: "Photocall textil", sub: "Tensado + iluminación" },
      { img: "plano-totem.jpg", tag: "Congreso", title: "Tótems de pasillo", sub: "Serie corta" },
      { img: "fachada-03.jpg", tag: "Activación", title: "Letras de suelo", sub: "PVC lacado" },
      { img: "caso-01.jpg", tag: "Retail", title: "Pop-up", sub: "Kit reutilizable" },
    ],
    faqH2: "Preguntas frecuentes de stands",
    faqs: [
      { q: "¿Qué tipos de stands hacéis?", a: "Diseñamos y fabricamos stands a medida para ferias, congresos y eventos: desde un pequeño espacio con mostrador y cartel hasta un stand con estructura, gráficas de gran formato e iluminación." },
      { q: "¿Se encarga todo, del diseño al montaje?", a: "Sí, nos ocupamos del diseño, la producción de los elementos y la impresión de las gráficas. Cuéntanos qué necesitas para el evento y te decimos qué incluye la propuesta." },
      { q: "¿Puedo reutilizar el stand en otros eventos?", a: "Sí. Podemos diseñarlo con elementos modulares o desmontables para que puedas adaptarlo y reutilizarlo en distintas ferias." },
      { q: "¿Con cuánta antelación tengo que encargarlo?", a: "Cuanto antes, mejor: hay que diseñar, producir y, en su caso, montar el stand antes de la fecha del evento. Cuéntanos la fecha de la feria y te decimos cuál es la antelación que necesitas según el proyecto." },
      { q: "¿Qué información necesitáis para presupuestar?", a: "Las medidas del espacio, la normativa de la feria si la hay, tu logotipo y una idea de qué quieres mostrar, con el número de personas y los elementos que necesitas (mostrador, vitrinas, pantallas, iluminación)." },
      { q: "¿Podéis hacer gráficas y cartelería para el stand?", a: "Sí. Imprimimos las gráficas, los paneles y la cartelería con tu imagen de marca." },
    ],
    contactH2: "¿Tienes fecha de feria?",
    contactLead: "Dinos recinto, metros y fecha. Te proponemos kit y precio para llegar a tiempo.",
  },

  "iluminacion-decorativa": {
    slug: "iluminacion-decorativa",
    breadcrumb: "Iluminación decorativa",
    eyebrow: "Luz de ambiente y de marca, no de rótulo",
    h1Before: "Iluminación decorativa: ambiente, acento y",
    h1Accent: "presencia de marca",
    lead: "Líneas LED, perfiles, backlights de interior, iluminación de producto y de arquitectura ligera. Esta página es luz ambiental y decorativa. El neón de logotipo y las cajas de luz van en Rótulos.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "light", title: "LED", sub: "Bajo consumo" },
      { icon: "tune", title: "A medida", sub: "Perfiles y tiras" },
      { icon: "home", title: "Interior", sub: "Y terrazas cubiertas" },
    ],
    ctaPrimary: "Pedir presupuesto de iluminación",
    ctaSecondary: "Ver aplicaciones",
    trust: "Si lo que quieres es un logo en neón o una caja de luz, ve a Rótulos. Aquí resolvemos la luz del espacio.",
    heroImg: "fachada-hero.jpg",
    heroBadge: "Luz de espacio, no de cartel",
    heroTitle: "Interior comercial",
    heroSub: "Perfil LED + acento de producto",
    heroStat: "LED",
    heroStatLabel: "Temperatura a medida",
    whyEyebrow: "Por qué separar iluminación y rótulos",
    whyH2: "Un rótulo se lee. La iluminación decorativa se siente.",
    whyLead: "Usamos la luz para destacar producto, recorrer una barra o dar calor a una recepción, sin confundirlo con el cartel.",
    benefits: [
      { icon: "light_mode", kicker: "01 / Ambiente", title: "El local se percibe mejor", text: "Temperatura de color y capas de luz para retail, clínicas y hostelería.", tag: "Confort visual" },
      { icon: "highlight", kicker: "02 / Producto", title: "Acento donde vende", text: "Bañadores, tiras y perfiles para lineal de producto o barra.", tag: "Luz de acento" },
      { icon: "architecture", kicker: "03 / Arquitectura", title: "Subraya el espacio", text: "Tiras en cornisa, huecos y estantes, integradas en el mueble o el pladur.", tag: "Luz lineal" },
      { icon: "bolt", kicker: "04 / LED", title: "Bajo consumo, controlable", text: "Drivers de calidad, regulación y encendidos programables.", tag: "Eficiencia" },
    ],
    solutionsH2: "Aplicaciones de iluminación decorativa",
    solutionsLead: "Todo esto es luz de espacio. El neón de marca está en la página de rótulos.",
    solutions: [
      { tag: "01 · Lineal", tech: "Perfil LED", title: "Perfiles y tiras LED a medida", text: "Cortes a longitud, esquinas y difusión homogénea para mueble o techo.", a: "Uso", av: "Cornisas, estantes, barras", b: "Control", bv: "On/off o regulación", img: "fachada-hero.jpg", cap: "Línea continua" },
      { tag: "02 · Acento", tech: "Foco / bañador", title: "Iluminación de producto y arte", text: "Destacar lineal, escaparate interior o una pieza de marca.", a: "Efecto", av: "Acento dirigido", b: "Interior", bv: "Retail y exposiciones", img: "caso-01.jpg", cap: "El producto brilla" },
      { tag: "03 · Backlight", tech: "Superficie", title: "Paneles y cajas de ambiente", text: "Superficies luminosas de interior, distintas de un rótulo de fachada.", a: "Uso", av: "Recepciones y pasillos", b: "Nota", bv: "El rótulo luminoso está en /rotulos", img: "fachada-02.jpg", cap: "Pared que emite luz" },
      { tag: "04 · Conjunto", tech: "Proyecto", title: "Luz + interior + rótulo, coordinados", text: "Podemos diseñar la luz del espacio y fabricar el neón o la corpórea en paralelo.", a: "Rótulos", av: "Neón y cajas de luz en /rotulos", b: "Interior", bv: "Página de interiores", img: "caso-03.jpg", cap: "Un solo taller" },
    ],
    processH2: "Cómo planteamos la luz de un local",
    processLead: "Fotos del espacio, uso (tienda, sala, barra) y si ya hay rótulo o se fabrica a la vez.",
    process: processDefault,
    casesH2: "Espacios con iluminación decorativa",
    cases: [
      { img: "fachada-hero.jpg", tag: "Retail", title: "Lineal de producto", sub: "Perfil LED" },
      { img: "caso-03.jpg", tag: "Clínica", title: "Recepción", sub: "Luz cálida lineal" },
      { img: "caso-01.jpg", tag: "Hostelería", title: "Barra", sub: "Acento + ambiente" },
      { img: "caso-04.jpg", tag: "Oficina", title: "Sala", sub: "Cornisa LED" },
    ],
    faqH2: "Preguntas frecuentes de iluminación decorativa",
    faqs: [
      { q: "¿Qué es la iluminación decorativa?", a: "Es la iluminación pensada para crear ambiente y dar identidad a un espacio: logotipos y letras iluminadas, neón, paneles retroiluminados o formas a medida para negocios y viviendas." },
      { q: "¿Para qué espacios sirve?", a: "Para locales comerciales, restaurantes, bares, tiendas, oficinas, eventos y también para el hogar, por ejemplo en salones, habitaciones o zonas de ocio." },
      { q: "¿Podéis hacer un diseño personalizado?", a: "Sí. Fabricamos piezas a medida con tu logotipo, una frase o el dibujo que quieras. Cuéntanos la idea y te proponemos cómo llevarla a cabo." },
      { q: "¿Se puede controlar la luz (encender, atenuar, cambiar de color)?", a: "Depende de la pieza y de la tecnología de iluminación. Muchas soluciones LED admiten regulación, temporizador o mando; te indicamos qué opciones tiene la que elijas." },
      { q: "¿Necesito instalación eléctrica especial?", a: "La mayoría de piezas LED funcionan con un transformador que se conecta a una toma de corriente convencional. Si el montaje requiere una instalación específica, te lo indicamos en el presupuesto." },
      { q: "¿Se puede usar en exterior?", a: "Depende del diseño y de la protección de la pieza. Te indicamos cuáles son adecuadas para exterior y cuáles es mejor reservar para interior." },
    ],
    contactH2: "¿Quieres iluminar el espacio (no el cartel)?",
    contactLead: "Envía fotos del local y dinos si ya tienes rótulo. Te proponemos perfiles, temperatura de color y precio.",
  },

  senaletica: {
    slug: "senaletica",
    breadcrumb: "Señalética y placas",
    eyebrow: "Directorios, placas y orientación",
    h1Before: "Señalética: orientar, identificar y",
    h1Accent: "cumplir sin perder marca",
    lead: "Placas de despacho, directorios de planta, pictogramas y señalética de evacuación o de marca. Corte, grabado e impresión para que el visitante sepa dónde está — con la misma tipografía que tu rótulo.",
    pills: [
      { icon: "timer", title: "Presupuesto 24h", sub: "Sin compromiso" },
      { icon: "domain", title: "Edificios", sub: "Plantas y directorios" },
      { icon: "badge", title: "Placas", sub: "Despachos y salas" },
      { icon: "alt_route", title: "Recorridos", sub: "Wayfinding" },
    ],
    ctaPrimary: "Pedir presupuesto de señalética",
    ctaSecondary: "Ver sistemas",
    trust: "Señalética de marca para el mismo edificio que ya tiene fachada o rótulo Vexil.",
    heroImg: "plano-totem.jpg",
    heroBadge: "Wayfinding de marca",
    heroTitle: "Directorio de planta",
    heroSub: "Placas + directorio + pictogramas",
    heroStat: "N",
    heroStatLabel: "Plantas y salas",
    whyEyebrow: "Orientar también es imagen",
    whyH2: "Una placa mal hecha rompe la fachada que acabas de renovar",
    whyLead: "Unificamos materiales, tipografía y pictogramas con tu identidad.",
    benefits: [
      { icon: "explore", kicker: "01 / Orientación", title: "El visitante no se pierde", text: "Recorridos claros en oficinas, clínicas, hoteles e industriales.", tag: "Wayfinding" },
      { icon: "badge", kicker: "02 / Identidad", title: "Placas que parecen de la casa", text: "Mismo material y tipo que el rótulo principal.", tag: "Familia gráfica" },
      { icon: "update", kicker: "03 / Cambio", title: "Nombres que se actualizan", text: "Sistemas intercambiables para despachos y organigramas.", tag: "Modulares" },
      { icon: "gavel", kicker: "04 / Norma", title: "Lo obligatorio, bien resuelto", text: "Señalética normativa sin estética de ferretería.", tag: "Cumplimiento" },
    ],
    solutionsH2: "Sistemas de señalética",
    solutionsLead: "Del pictograma suelto al directorio de edificio.",
    solutions: [
      { tag: "01 · Placas", tech: "Grabado / impresión", title: "Placas de despacho y sala", text: "Metacrilato, aluminio, dibond o latón. Fijas o con inserto intercambiable.", a: "Uso", av: "Despachos, consultas, salas", b: "Cambio", bv: "Inserto o QR", img: "plano-totem.jpg", cap: "Identificación de sala" },
      { tag: "02 · Directorio", tech: "Modular", title: "Directorios de planta y edificio", text: "Listados de empresas o departamentos, actualizables.", a: "Formato", av: "Pared o tótem", b: "Marca", bv: "Tipografía del manual", img: "fachada-01.jpg", cap: "Quién está en cada planta" },
      { tag: "03 · Recorrido", tech: "Pictogramas", title: "Wayfinding y flechas de recorrido", text: "Conjuntos coherentes para pasillos, parkings y naves.", a: "Lectura", av: "A distancia de pasillo", b: "Soporte", bv: "Pared, bandera, suelo", img: "caso-03.jpg", cap: "Siguiente paso, claro" },
      { tag: "04 · Norma", tech: "Obligatoria", title: "Señalética normativa y de evacuación", text: "Cuando hay que cumplir, lo integramos al resto de la familia gráfica.", a: "Tipo", av: "Evacuación, EPI, zonas", b: "Estética", bv: "Sin romper la marca", img: "caso-02.jpg", cap: "Norma + identidad" },
    ],
    processH2: "Cómo señalizamos un edificio",
    processLead: "Inventario de salas, recorrido y manual de marca. Luego producción e instalación.",
    process: processDefault,
    casesH2: "Señalética instalada",
    cases: [
      { img: "plano-totem.jpg", tag: "Oficinas", title: "Directorio", sub: "Planta + empresas" },
      { img: "caso-03.jpg", tag: "Clínica", title: "Consultas", sub: "Placas intercambiables" },
      { img: "fachada-01.jpg", tag: "Industrial", title: "Nave", sub: "Pictogramas de recorrido" },
      { img: "caso-04.jpg", tag: "Hotel", title: "Plantas", sub: "Familia completa" },
    ],
    faqH2: "Preguntas frecuentes de señalética",
    faqs: [
      { q: "¿Qué tipos de señalética podéis hacer?", a: "Señales de orientación, placas de puerta y despacho, directorios, carteles informativos, placas de comunidad y de profesional, y señales de aviso, entre otras. Se hacen a medida en los materiales y formatos que necesites." },
      { q: "¿En qué materiales se fabrican las placas?", a: "Metacrilato, aluminio, PVC, composite y otros soportes, con impresión, corte o grabado según el diseño. Te proponemos el material que mejor encaje con el uso y el lugar." },
      { q: "¿Podéis fabricar una sola placa?", a: "Sí. Hacemos desde una placa individual hasta la señalética completa de un edificio, un local o un centro." },
      { q: "¿Sirve para exterior?", a: "Sí, con materiales y acabados adecuados para la intemperie. Dinos dónde va a colocarse y te indicamos la mejor opción." },
      { q: "¿Las señales de seguridad y evacuación cumplen normativa?", a: "La señalización de seguridad tiene requisitos específicos (tamaño, color, pictograma). Si necesitas señales de este tipo, indícanoslo desde el principio y confirma con tu técnico o mantenedor qué exige la normativa en tu caso." },
      { q: "¿Se pueden colocar sin taladrar?", a: "En muchas superficies sí, con adhesivo de montaje o soportes discretos. Depende del peso de la placa y de la superficie, y te indicamos la opción más adecuada." },
    ],
    contactH2: "¿Necesitas placas, directorio o un recorrido entero?",
    contactLead: "Envía plano o listado de salas a proyectos@vexil.es. Te proponemos sistema y precio.",
  },
};

export const profesionales = {
  slug: "profesionales",
  breadcrumb: "Profesionales",
  eyebrow: "Empresas de rotulación, montadores, agencias, estudios y constructoras",
  h1Before: "Producimos para quien vende, instala o",
  h1Accent: "especifica el rótulo",
  lead: "Somos taller de apoyo para empresas de rotulación que no tienen medios para un tipo de rótulo, montadores que necesitan pieza lista para instalar, agencias de publicidad y estudios o constructoras. También hacemos mantenimiento y reparación. Asesoramos siempre. Cumplimos plazos.",
  pills: [
    { icon: "precision_manufacturing", title: "Taller de apoyo", sub: "Lo que no cubre tu medio" },
    { icon: "support_agent", title: "Asesoramos siempre", sub: "Técnica y materiales" },
    { icon: "schedule", title: "Cumplimos plazos", sub: "Fecha de entrega real" },
    { icon: "handshake", title: "Marca blanca", sub: "Si el encargo lo pide" },
  ],
  ctaPrimary: "Solicitar producción o colaboración",
  ctaSecondary: "Ver para quién producimos",
  trust: "Producción propia para empresas de rotulación, montadores, agencias y estudios. Un interlocutor técnico, plazos que se cumplen.",
  heroImg: "plano-totem.jpg",
  heroBadge: "Taller para profesionales",
  heroTitle: "De encargo a pieza en plazo",
  heroSub: "Rótulos, fachada, corte e iluminación",
  heroStat: "B2B",
  heroStatLabel: "Producción y asesoramiento",
  whyEyebrow: "Para quién producimos",
  whyH2: "Tu cliente, tu marca. Nuestra fabricación y nuestro criterio técnico",
  whyLead: "Cuando falta maquinaria, un tipo de rótulo, una reparación o un taller que cumpla la fecha, encajamos como producción de apoyo. Asesoramos en cada encargo.",
  benefits: [
    { icon: "signpost", kicker: "01 / Rotulación", title: "El rótulo que tu taller no cubre", text: "Corpóreos, neón, luminosos, corte o iluminación: producimos la partida para la que no tienes medios y te la entregamos lista.", tag: "Taller de apoyo" },
    { icon: "handyman", kicker: "02 / Montadores", title: "Pieza lista para instalar", text: "Fabricamos con despiece, anclajes y acabado de taller. Tú montas. Si lo necesitas, también coordinamos la instalación.", tag: "Entrega a obra o almacén" },
    { icon: "campaign", kicker: "03 / Agencias", title: "Producción con asesoramiento", text: "Campañas, identity y puntos de venta: traducimos el arte a material, medida y plazo. Siempre con criterio técnico, no solo con plotter.", tag: "Agencia + taller" },
    { icon: "architecture", kicker: "04 / Estudios y obra", title: "Planos, RAL y fecha de apertura", text: "Arquitectos, interioristas y constructoras: leemos alzados, respetamos el manual y encajamos en la ventana de montaje.", tag: "Gremio de proyecto" },
  ],
  solutionsH2: "Cómo encajamos en tu trabajo",
  solutionsLead: "Puedes pedirnos solo la fabricación, el asesoramiento de un tipo de rótulo, o el paquete hasta instalación.",
  solutions: [
    { tag: "01 · Empresa de rotulación", tech: "Producción", title: "Cuando no tienes medios para ese rótulo", text: "Te fabricamos corpóreos, cajas de luz, neón, corte CNC o láser y te lo enviamos o lo dejas recoger. Marca blanca si lo pides.", a: "Rol", av: "Taller de apoyo", b: "Entrega", bv: "A tu almacén o a obra", img: "hero-taller.jpg", cap: "Tu cliente no tiene por qué saberlo" },
    { tag: "02 · Montador", tech: "Fabricación", title: "Tú instalas, nosotros producimos", text: "Despiece, herrajes y acabado listos para el montaje. Asesoramos anclaje y peso. Cumplimos la fecha que tú le has dado al cliente.", a: "Entregable", av: "Pieza + ficha de montaje", b: "Plazo", bv: "El que acordamos", img: "plano-totem.jpg", cap: "Sin improvisar en altura" },
    { tag: "03 · Agencia", tech: "Campaña", title: "Del arte final a la pieza física", text: "Presupuesto rápido, muestras y producción de vinilo, gran formato, rótulo o stand. Te decimos qué aguanta exterior y qué no.", a: "Asesoramiento", av: "Siempre, en cada briefing", b: "Factura", bv: "A agencia o a anunciante", img: "caso-04.jpg", cap: "Criterio técnico incluido" },
    { tag: "04 · Estudio", tech: "Proyecto", title: "Del detalle al despiece de taller", text: "DWG o PDF, muestras RAL, subestructura y montaje coordinado con la obra. Un interlocutor para rótulo, fachada, corte y luz.", a: "Partidas", av: "Las que el proyecto pida", b: "Obra", bv: "Ventana real de montaje", img: "fachada-hero.jpg", cap: "Respetamos plano y fecha" },
  ],
  processH2: "Cómo arrancamos un encargo profesional",
  processLead: "Un correo con medidas, fotos o plano y la fecha que tienes que cumplir basta para cotizar.",
  process: [
    { n: "01", icon: "mail", title: "Nos pasas el encargo", text: "Medidas, fotos, PDF, DWG o un WhatsApp. Da igual si eres empresa de rotulación, montador, agencia o estudio: cotizamos la partida.", meta: "Día 1 · Encargo" },
    { n: "02", icon: "support_agent", title: "Asesoramos y cerramos precio", text: "Te decimos material, sistema y lo que sí o no conviene. Presupuesto cerrado y fecha de entrega real, no orientativa.", meta: "Asesoramiento incluido" },
    { n: "03", icon: "precision_manufacturing", title: "Fabricamos en plazo", text: "Taller propio: CNC, láser, luminotecnia y gran formato. Control de calidad antes de salir. La fecha acordada se cumple.", meta: "Producción" },
    { n: "04", icon: "local_shipping", title: "Entrega o instalación", text: "Recoges, te lo enviamos o lo instalamos. Si el montaje es tuyo, la pieza sale lista para colocar.", meta: "Como lo necesites" },
  ],
  casesH2: "Encargos con profesionales",
  cases: [
    { img: "plano-totem.jpg", tag: "Rotulación", title: "Corpóreo de apoyo", sub: "Fabricado para otro taller" },
    { img: "fachada-hero.jpg", tag: "Montaje", title: "Fachada comercial", sub: "Pieza lista para instalar" },
    { img: "caso-04.jpg", tag: "Agencia", title: "Campaña Punto de venta", sub: "Arte a material" },
    { img: "caso-03.jpg", tag: "Estudio", title: "Clínica", sub: "Rótulo + interior + luz" },
  ],
  faqH2: "Preguntas frecuentes para profesionales",
  faqs: [
    { q: "¿Qué puedo encargaros si soy rotulista, montador o instalador?", a: "Fabricamos por encargo piezas y rótulos terminados para que tú los montes: cortes CNC y láser, letras y logotipos, composites para revestimientos, impresión digital y vinilos. Tú te ocupas del cliente y del montaje; nosotros, de la producción." },
    { q: "¿Tenéis una tarifa distinta para profesionales?", a: "Sí. Los profesionales trabajan con una tarifa propia, diferente a la de cliente final. Escríbenos indicando tu actividad y qué sueles necesitar y te la enviamos." },
    { q: "¿Qué archivos necesitáis para producir mi pedido?", a: "Lo ideal son archivos vectoriales (PDF, AI, SVG o DXF) con los textos convertidos a curvas y las medidas reales. Si solo tienes un JPG o un PNG, dinos y vemos si podemos vectorizarlo." },
    { q: "¿Podéis fabricar piezas según mis planos o diseños?", a: "Sí. Fabricamos a medida a partir de tus archivos o planos. Antes de producir revisamos que el fichero sea viable y te avisamos si hay algo que ajustar." },
    { q: "¿Hacéis trabajos grandes o de varias piezas?", a: "Sí. Trabajamos piezas de gran formato y series de varias unidades. Cuéntanos qué necesitas y te confirmamos cómo lo haríamos." },
    { q: "¿Entregáis en mi taller o instalación?", a: "Depende de la zona y del volumen del pedido. Consulta con nosotros la recogida en nuestro taller de El Campello o la entrega y te indicamos la mejor opción." },
  ],
  contactH2: "¿Necesitas producción, un plazo o un criterio técnico?",
  contactLead: "Escríbenos a proyectos@vexil.es o llama al 616 048 109. Empresas de rotulación, montadores, agencias y estudios: producción, mantenimiento o reparación, a la fecha acordada.",
};

export const nosotros = {
  slug: "nosotros",
  breadcrumb: "Nosotros",
  eyebrow: "Taller de rotulación comercial",
  h1Before: "Producimos rotulación con",
  h1Accent: "medios propios",
  lead: "Vexil es un taller de rotulación comercial y publicidad visual. Diseñamos, producimos e instalamos para negocios y para profesionales del sector. Lo que marca la diferencia es lo que sale de nuestras máquinas: CNC, láser, gran formato y luminotecnia LED. Asesoramos siempre. Cumplimos plazos.",
  pills: [
    { icon: "precision_manufacturing", title: "CNC", sub: "Corte y mecanizado" },
    { icon: "blur_on", title: "Láser", sub: "Detalle y grabado" },
    { icon: "print", title: "Gran formato", sub: "Vinilo y lona" },
    { icon: "light", title: "Luminotecnia LED", sub: "Cajas de luz y neón LED" },
  ],
  ctaPrimary: "Hablar con el taller",
  ctaSecondary: "Ver medios de producción",
  trust: "Taller propio. Asesoramiento técnico. Fecha de entrega real.",
  heroImg: "hero-taller.jpg",
  heroBadge: "Medios de producción",
  heroTitle: "Lo que sale de nuestras máquinas",
  heroSub: "CNC · Láser · Gran formato · LED",
  heroStat: "Taller",
  heroStatLabel: "Producción propia",
  whyEyebrow: "Quiénes somos",
  whyH2: "Un taller que produce, asesora y entrega a fecha",
  whyLead: "No vendemos catálogo suelto. Valoramos el encargo, proponemos el sistema que conviene y lo producimos en nuestras instalaciones. El criterio técnico va con cada presupuesto.",
  benefits: [
    { icon: "precision_manufacturing", kicker: "01 / Taller", title: "Máquinas en casa", text: "CNC, láser, impresión de gran formato y luminotecnia LED. Controlamos corte, gráfico e iluminación desde el mismo taller.", tag: "Medios propios" },
    { icon: "support_agent", kicker: "02 / Criterio", title: "Asesoramos siempre", text: "Material, tamaño, luz y plazo. Te decimos qué conviene al local, a la calle y a la fecha que tienes que cumplir.", tag: "Técnica incluida" },
    { icon: "schedule", kicker: "03 / Plazos", title: "La fecha se cumple", text: "Damos una entrega real. Si no es viable, lo decimos al cotizar, no a mitad de producción.", tag: "Planning de taller" },
    { icon: "handshake", kicker: "04 / Para quién", title: "Negocios y profesionales", text: "Trabajamos el encargo del comercio y la producción de apoyo para empresas de rotulación, montadores, agencias y estudios.", tag: "Cliente final y B2B" },
  ],
  solutionsH2: "Con qué producimos",
  solutionsLead: "Estas son las líneas de taller con las que resolvemos la mayoría de encargos de rotulación, fachada, gráfico e iluminación.",
  solutions: [
    { tag: "01 · CNC", tech: "Corte y mecanizado", title: "Mesa CNC para piezas de rotulación", text: "Corte y mecanizado de composite, PVC, dibond y metacrilato. Despieces, bandejas, placas y piezas a medida con cota de taller.", a: "Materiales", av: "Composite, PVC, dibond, PMMA", b: "Uso", bv: "Fachada, placa, pieza a medida", img: "hero-taller.jpg", cap: "Cota y repetición fiel" },
    { tag: "02 · Láser", tech: "Corte y grabado", title: "Láser de detalle", text: "Corte fino y grabado para logos, placas, metacrilato y series cortas donde el canto y la precisión importan.", a: "Ideal para", av: "Placas, logos, series cortas", b: "Acabado", bv: "Canto limpio / grabado", img: "plano-totem.jpg", cap: "Detalle de taller" },
    { tag: "03 · Gran formato", tech: "Impresión y vinilo", title: "Impresión de gran formato", text: "Vinilos de interior y exterior, lonas y gráficos a escala de fachada, vehículo o stand. Color de marca y laminados de protección.", a: "Soportes", av: "Vinilo, lona, rígido", b: "Uso", bv: "Fachada, flota, evento", img: "fachada-04.jpg", cap: "Gráfico de taller" },
    { tag: "04 · LED", tech: "Luminotecnia", title: "Iluminación de rótulo y espacio", text: "Cajas de luz, módulos LED, neón LED y perfiles. Calculamos consumo, estanqueidad y temperatura de color según el encargo.", a: "Sistemas", av: "Caja de luz, neón LED, perfil", b: "Servicio", bv: "Nuevo y reparación", img: "fachada-02.jpg", cap: "Luz de taller" },
  ],
  processH2: "Cómo entra un encargo en el taller",
  processLead: "Una foto, un plano o un archivo basta para cotizar. Luego asesoramos, producimos y entregamos o instalamos.",
  process: [
    { n: "01", icon: "mail", title: "Nos cuentas el encargo", text: "Medidas, fotos, logo o DWG. Da igual si es un local, una flota o una partida para otro profesional.", meta: "Día 1 · Encargo" },
    { n: "02", icon: "support_agent", title: "Asesoramos y cerramos precio", text: "Proponemos material, sistema y fecha de entrega real. Presupuesto cerrado, desglosado por partidas.", meta: "Criterio técnico" },
    { n: "03", icon: "precision_manufacturing", title: "Producción en taller", text: "CNC, láser, gran formato y LED según el encargo. Control de calidad antes de salir.", meta: "Medios propios" },
    { n: "04", icon: "local_shipping", title: "Entrega o instalación", text: "Recoges, te lo enviamos o lo instalamos. Mantenimiento y reparación de rótulos ya puestos, también.", meta: "Como lo necesites" },
  ],
  casesH2: "Trabajo de taller",
  cases: [
    { img: "hero-taller.jpg", tag: "Taller", title: "Producción propia", sub: "CNC, láser y LED" },
    { img: "fachada-hero.jpg", tag: "Fachada", title: "Imagen comercial", sub: "Revestimiento + gráfico" },
    { img: "fachada-03.jpg", tag: "Rótulo", title: "Pieza iluminada", sub: "Luminotecnia LED" },
    { img: "caso-02.jpg", tag: "Gran formato", title: "Gráfico de exterior", sub: "Vinilo y lona" },
  ],
  faqH2: "Preguntas frecuentes sobre Vexil",
  faqs: [
    { q: "¿Qué es Vexil?", a: "Un taller de rotulación comercial: diseñamos, producimos e instalamos fachadas, rótulos, gráfico, vehículos, corte e iluminación." },
    { q: "¿Qué producís en taller?", a: "Corte CNC, láser, impresión de gran formato, vinilo, cajas de luz, neón LED e iluminación. El presupuesto te dice el sistema concreto." },
    { q: "¿Trabajáis con otros profesionales del sector?", a: "Sí. Empresas de rotulación, montadores, agencias y estudios. Producción, mantenimiento y reparación. Marca blanca si lo pides." },
    { q: "¿Cumplís plazos?", a: "Sí. Fecha real al cotizar. Si no es viable, te lo decimos antes de producir." },
    { q: "¿Cómo se pide presupuesto?", a: "proyectos@vexil.es o 616 048 109. Con fotos, medidas o archivo basta." },
  ],
  contactH2: "¿Quieres que el taller valore tu encargo?",
  contactLead: "Escríbenos a proyectos@vexil.es o llama al 616 048 109. Te decimos sistema, material y fecha.",
};

export const homeCatalog = navServices.map((s, i) => ({
  ...s,
  code: String(i + 1).padStart(2, "0"),
}));
