export const site = {
  name: "Vexil",
  origin: "https://waltersele.github.io/vexil",
  // Web3Forms: si está vacío, el formulario abre WhatsApp con los campos.
  formAccessKey: "",
  // GA4: si está vacío no se carga analítica ni el banner de cookies.
  gaId: "",
};

export const contact = {
  name: "Vexil",
  email: "proyectos@vexil.es",
  phoneDisplay: "616 048 109",
  phoneTel: "+34616048109",
  whatsappNumber: "34616048109",
  addressLocality: "El Campello",
  addressRegion: "Alicante",
  addressCountry: "ES",
  streetAddress: "Avda Pla de Messell, 1, Nave D2",
  postalCode: "03560",
  nif: "48564088W",
  areaServed: ["El Campello", "Alicante", "San Juan", "San Vicente", "Mutxamel", "Jijona", "Villajoyosa", "Benidorm"],
};

export const nextStepText =
  "Mándanos fotos, medidas o planos. Te decimos qué tiene sentido y te pasamos presupuesto: del proyecto entero o de una sola pieza.";

export const navServices = [
  { slug: "fachadas", name: "Fachadas comerciales", short: "Rótulo y revestimiento", icon: "apartment" },
  { slug: "rotulos", name: "Letras corpóreas y rótulos", short: "Corpóreos, luminosos y neón", icon: "letter_a" },
  { slug: "impresion-digital", name: "Impresión digital", short: "Lonas y vinilos", icon: "print" },
  { slug: "vehiculos", name: "Rotulación de vehículos", short: "Furgonetas y coches", icon: "local_shipping" },
  { slug: "interiorismo-comercial", name: "Interiorismo comercial", short: "Murales, letras e interiores", icon: "chair" },
  { slug: "laminas-solares", name: "Láminas solares", short: "Control solar y privacidad", icon: "wb_sunny" },
  { slug: "corte", name: "Corte a medida", short: "Láser y CNC", icon: "content_cut" },
  { slug: "stands", name: "Stands para ferias", short: "Photocalls y gráfica", icon: "view_quilt" },
  { slug: "iluminacion-decorativa", name: "Iluminación decorativa", short: "LED para locales", icon: "light" },
  { slug: "senaletica", name: "Señalética y placas", short: "Metacrilato y orientación", icon: "plaque" },
];

export const redirects = [
  { from: "servicios/lamina-solar", to: "servicios/laminas-solares/" },
  { from: "servicios/interiores", to: "servicios/interiorismo-comercial/" },
];

export const home = {
  title: "Rotulación en Alicante: rótulos y fachadas | Vexil",
  description: "Empresa de rotulación en El Campello: rótulos, fachadas, interiores y señalética. Diseño, fabricación e instalación. Pide tu presupuesto.",
  eyebrow: "Empresa de rotulación en Alicante",
  h1: "Rotulación comercial en Alicante y El Campello",
  lead: "Diseñamos, fabricamos e instalamos. Puedes pedirnos el proyecto entero o solo una pieza: letras, fachada, vinilos, láminas o señalética.",
  ctaPrimary: "Pide tu propuesta",
  ctaSecondary: "Ver lo que hacemos",
  trust: "Diseño, taller e instalación",
  heroImg: "hero-taller.jpg",
  heroAlt: "Taller de Vexil en El Campello: fabricación de rótulos y rotulación",
  servicesEyebrow: "Qué hacemos",
  servicesH2: "Rótulos, fachadas, interiores y más",
  servicesLead:
    "Desde una letra corpórea hasta una fachada completa o las partidas gráficas de un proyecto. Nos ocupamos de que cada pieza encaje con el resto. Mira nuestras <a href=\"servicios/rotulos/\">letras corpóreas y rótulos luminosos</a>, la <a href=\"servicios/fachadas/\">rotulación de fachadas</a>, las <a href=\"servicios/laminas-solares/\">láminas de control solar</a> o cómo ejecutamos <a href=\"servicios/interiorismo-comercial/\">proyectos de interiorismo comercial</a>.",
  whyEyebrow: "Cómo trabajamos",
  whyH2: "Diseño, fabricación e instalación",
  whyLead: "Si quieres que lo llevemos todo, lo hacemos. Si solo necesitas que fabriquemos, también. En los dos casos hablas con el mismo taller.",
  whyImg: "plano-totem.jpg",
  whyImgAlt: "Plano de tótem y señalética preparado en el taller de Vexil",
  whyCta: "Conoce el taller",
  whyCtaHref: "nosotros/",
  benefits: [
    { icon: "precision_manufacturing", title: "Todo o una pieza", text: "Diseño, fabricación e instalación. O solo lo que te falte." },
    { icon: "verified", title: "Te orientamos", text: "Material, tamaño y luz: te explicamos qué encaja en tu local y por qué." },
    { icon: "support_agent", title: "Hablas con el taller", text: "Quien te atiende es quien fabrica y monta." },
    { icon: "handyman", title: "Montamos o te lo entregamos", text: "Instalamos en el local o te dejamos la pieza lista." },
  ],
  contactEyebrow: "Presupuesto sin compromiso",
  contactH2: "Cuéntanos tu proyecto",
  contactLead: "Una foto del local, un logotipo, unos planos o una idea a medias. Con eso te preparamos una propuesta.",
  faqH2: "Preguntas frecuentes",
  faqs: [
    { q: "¿Qué servicios de rotulación ofrece Vexil?", a: "Diseñamos, fabricamos e instalamos rótulos, fachadas comerciales, vinilos, impresión digital, señalética, stands e iluminación decorativa. También cortamos y grabamos piezas a medida con CNC y láser." },
    { q: "¿Podéis hacer solo una parte del trabajo?", a: "Sí. El proyecto entero o solo una parte: fabricación, montaje o un servicio concreto." },
    { q: "¿En qué zonas trabajáis?", a: "Nuestra base está en El Campello y trabajamos en Alicante, San Juan, San Vicente, El Campello, Mutxamel, Jijona, Villajoyosa y Benidorm. Si tu proyecto está fuera de esta zona, cuéntanoslo y lo estudiamos." },
    { q: "¿Cómo puedo pedir presupuesto?", a: "Escríbenos por WhatsApp o por el formulario: qué quieres rotular, dónde y, si puedes, fotos y medidas. Con eso te preparamos una propuesta." },
    { q: "¿Hacéis también el diseño del rótulo o solo la fabricación?", a: "Las dos cosas. Trae el diseño listo o lo hacemos contigo antes de fabricar e instalar." },
    { q: "¿Cuánto cuesta un rótulo para un negocio?", a: "Depende del tipo, el tamaño, los materiales, si lleva luz y si incluye montaje. Envíanos fotos y medidas y te lo presupuestamos sin compromiso." },
    { q: "¿Trabajáis con particulares o solo con empresas?", a: "Con ambos. Negocios y particulares: desde un vinilo hasta un rótulo con o sin instalación." },
  ],
  related: [
    { href: "servicios/rotulos/", anchor: "letras corpóreas y rótulos luminosos" },
    { href: "servicios/fachadas/", anchor: "rotulación de fachadas" },
    { href: "servicios/laminas-solares/", anchor: "láminas de control solar" },
    { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiorismo comercial" },
    { href: "profesionales/", anchor: "trabajamos con estudios, constructoras y rotulistas" },
  ],
  waMessage: "Hola, os escribo para pedir presupuesto de rotulación.",
};

export const services = {
  fachadas: {
    slug: "fachadas",
    breadcrumb: "Fachadas comerciales",
    title: "Rotulación de fachadas en Alicante | Vexil",
    description: "Renovamos fachadas comerciales en Alicante: composite, letras corpóreas, iluminación y escaparate. Todo el proyecto o solo una parte.",
    eyebrow: "Fachadas comerciales",
    h1: "Rotulación de fachadas comerciales en Alicante",
    lead: "Revestimiento, rótulo, iluminación y escaparate juntos, o solo lo que necesites. Diseñamos, fabricamos e instalamos.",
    pills: [
      { icon: "storefront", title: "Proyecto completo", sub: "O solo una parte" },
      { icon: "layers", title: "Composite", sub: "Aluminio a medida" },
      { icon: "light", title: "Iluminación", sub: "Si el local lo pide" },
      { icon: "handyman", title: "Montamos o entregamos", sub: "Como te convenga" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver qué incluye",
    trust: "Diseño, fabricación e instalación de fachadas.",
    heroImg: "fachada-hero.jpg",
    heroAlt: "Fachada comercial rotulada por Vexil con revestimiento y letras corpóreas",
    whyEyebrow: "Beneficios",
    whyH2: "Qué aporta una fachada bien resuelta",
    whyLead: "La fachada es lo primero que ve quien pasa por tu calle. La diseñamos como conjunto: rótulo, revestimiento y escaparate.",
    benefits: [
      { icon: "visibility", title: "Más visibilidad", text: "Una fachada coherente se distingue mejor entre otros rótulos de la calle.", tag: "Visibilidad" },
      { icon: "verified", title: "Imagen cuidada", text: "El aspecto del local influye en si el cliente decide entrar.", tag: "Imagen" },
      { icon: "layers", title: "Acabado limpio", text: "Cajas de persiana, cableado o paredes deterioradas quedan integrados o cubiertos.", tag: "Acabado limpio" },
      { icon: "architecture", title: "Un solo criterio", text: "Rótulo, revestimiento y escaparate se diseñan juntos desde el principio.", tag: "Un solo criterio" },
    ],
    solutionsH2: "Qué podemos hacer en tu fachada",
    solutionsLead: "Combinamos revestimiento, letras y vinilos según el local. También <a data-rel=\"servicios/rotulos/\">letras corpóreas</a>, <a data-rel=\"servicios/laminas-solares/\">láminas solares en escaparates y cristaleras</a> y <a data-rel=\"servicios/impresion-digital/\">vinilos de escaparate</a>.",
    solutions: [
      { tech: "Composite de aluminio", title: "Revestimiento de composite", text: "Un frente limpio y uniforme que sirve de base al rótulo y a la marca.", specs: ["Mate, brillo o metalizado", "Fachadas de local y nave"], img: "fachada-01.jpg", cap: "Revestimiento de composite", alt: "Revestimiento de fachada en composite de aluminio" },
      { tech: "Letras e iluminación", title: "Letras corpóreas y rótulo", text: "Con luz o sin ella, integrado en el revestimiento.", specs: ["Con luz o sin luz", "Integrado en el revestimiento"], img: "fachada-02.jpg", cap: "Rótulo y fachada juntos", alt: "Rótulo luminoso integrado en una fachada comercial" },
      { tech: "Luz", title: "Iluminación", text: "Iluminación para que la fachada se lea también de noche.", specs: ["Aluminio, PVC o metacrilato", "Frontal, halo o sin luz"], img: "fachada-03.jpg", cap: "Fachada iluminada", alt: "Fachada comercial con iluminación" },
      { tech: "Cristalera", title: "Escaparate", text: "Vinilos de escaparate y <a data-rel=\"servicios/laminas-solares/\">láminas solares en escaparates y cristaleras</a>.", specs: ["Marca y privacidad", "Producción e instalación"], img: "fachada-04.jpg", cap: "Vinilo en cristalera", alt: "Vinilo de escaparate en la cristalera de un local" },
    ],
    faqH2: "Preguntas frecuentes sobre la renovación de fachadas",
    faqs: [
      { q: "¿Qué incluye la rotulación de una fachada comercial?", a: "Puede incluir el rótulo principal, banderolas, rotulación de escaparates y puerta, revestimientos de fachada y la iluminación. Lo diseñamos como un conjunto para que el local tenga una imagen coherente y se vea bien de día y de noche." },
      { q: "¿Podéis hacerlo todo, del diseño al montaje?", a: "Sí. Podemos llevar diseño, fabricación e instalación de punta a punta, o encargarnos solo de una partida si el resto ya está resuelto con otro proveedor o con tu obra." },
      { q: "¿Puedo combinar varios materiales en la fachada?", a: "Sí. Es habitual combinar, por ejemplo, letras corpóreas, paneles composite, vinilo en cristales e iluminación. Te proponemos la combinación que mejor encaje con tu marca y tu presupuesto." },
      { q: "¿Qué necesito para que me hagáis un presupuesto?", a: "Fotos de la fachada actual con el entorno, medidas aproximadas y tu logotipo. Si nos cuentas qué quieres cambiar, te decimos si hace falta visita para tomar medidas." },
      { q: "¿Cuánto se tarda en renovar una fachada?", a: "Depende del alcance del trabajo. Te damos un plazo concreto en el presupuesto, una vez vista la fachada y definido el proyecto." },
    ],
    contactH2: "Mándanos una foto de tu fachada",
    contactLead: "Con una foto frontal y unas medidas aproximadas te preparamos una propuesta para toda la fachada.",
    related: [
      { href: "servicios/rotulos/", anchor: "letras corpóreas" },
      { href: "servicios/laminas-solares/", anchor: "láminas solares en escaparates y cristaleras" },
      { href: "servicios/impresion-digital/", anchor: "vinilos de escaparate" },
      { href: "profesionales/", anchor: "proyectos de obra" },
      { href: "franquicias/", anchor: "rotulación para franquicias" },
    ],
    waMessage: "Hola, os escribo por rotulación de fachadas.",
  },

  rotulos: {
    slug: "rotulos",
    variant: "types",
    breadcrumb: "Letras corpóreas y rótulos",
    title: "Letras corpóreas y rótulos luminosos | Vexil Alicante",
    description: "Letras corpóreas, rótulos luminosos y neón LED. Diseño, fabricación e instalación, o solo producción. También reparamos rótulos.",
    eyebrow: "Rótulos para negocios",
    h1: "Letras corpóreas y rótulos luminosos en Alicante",
    lead: "Diseñamos, fabricamos e instalamos rótulos: corpóreos, luminosos, neón LED o sin luz. Si solo quieres la pieza, te la fabricamos. Si el que tienes falla, también lo reparamos.",
    pills: [
      { icon: "light", title: "Con luz o sin luz", sub: "Luminosos y neón LED" },
      { icon: "design_services", title: "Diseño y taller", sub: "Y montaje si lo pides" },
      { icon: "build", title: "Reparación", sub: "También de los que ya tienes" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver tipos de rótulo",
    trust: "Diseño, fabricación e instalación",
    heroImg: "fachada-03.jpg",
    heroAlt: "Letras corpóreas fabricadas en el taller de Vexil",
    whyEyebrow: "Por qué",
    whyH2: "El rótulo adecuado para cada fachada",
    whyLead: "El tipo depende de tu calle, tu horario y tu marca. A veces conviene combinar: letras corpóreas en fachada, un neón dentro y una banderola para peatones. Si también renovamos el frente, mira <a data-rel=\"servicios/fachadas/\">rótulo y revestimiento de fachada</a>.",
    benefits: [
      { icon: "hub", title: "Todos los tipos, un taller", text: "Corpóreas, neón, luminosos y vinilo se producen aquí.", tag: "Fabricación propia" },
      { icon: "visibility", title: "Se lee bien", text: "Tamaño, contraste y luz según la distancia y el entorno de tu local.", tag: "Visibilidad" },
      { icon: "architecture", title: "Montaje o entrega", text: "Lo fijamos a composite, ladrillo, panel o cristal, o te dejamos la pieza lista.", tag: "Montaje" },
      { icon: "savings", title: "Presupuesto claro", text: "Te detallamos diseño, fabricación, luz e instalación según lo que encargues.", tag: "Propuesta" },
    ],
    typesH2Intro: "Tipos de rótulo",
    typesLead: "Corpóreos, neón LED, luminosos, sin iluminación y reparación del que ya tienes.",
    types: [
      {
        id: "corporeos",
        h2: "Letras corpóreas",
        kicker: "Relieve",
        text: "Letras y logotipos recortados pieza a pieza, montados sobre la fachada o sobre un panel. Con luz o sin ella, dan volumen y se leen bien de cerca y de lejos.",
        specs: ["PVC, metacrilato, aluminio, composite o madera", "Con luz o sin luz", "Sobre fachada o sobre panel"],
        img: "fachada-03.jpg",
        alt: "Letras corpóreas en relieve para fachada de negocio",
        faqs: [
          { q: "¿Qué son las letras corpóreas?", a: "Son letras y logos en volumen, cortados a medida y fijados a la fachada o a un panel. Dan relieve y se leen bien de cerca y de lejos." },
          { q: "¿Pueden llevar luz?", a: "Sí. Pueden ir sin luz, con luz frontal o con halo. Te proponemos la opción que mejor se lea en tu calle." },
        ],
      },
      {
        id: "neon",
        h2: "Neón LED",
        kicker: "Neón LED flexible",
        text: "Logotipo, frase o dibujo en neón LED flexible. Los trazos simples se leen mejor.",
        specs: ["Neón LED flexible", "Logotipo, frase o dibujo", "Interior o exterior, según modelo"],
        img: "fachada-02.jpg",
        alt: "Rótulo de neón LED con logotipo",
        faqs: [
          { q: "¿Hacéis neón con el logo de mi negocio?", a: "Sí. Recortamos el trazo de tu logotipo o de una frase. Los trazos simples se leen mejor." },
          { q: "¿Vale para interior y exterior?", a: "Según el modelo. Te decimos cuál encaja en tu local." },
        ],
      },
      {
        id: "luminosos",
        h2: "Rótulos luminosos",
        kicker: "Iluminación LED",
        text: "Cajones con cara iluminada, banderolas y letras con luz LED. Te ayudamos a elegir según tu fachada y tu presupuesto.",
        specs: ["Cajones, banderolas y letras iluminadas", "Iluminación LED", "Según fachada y presupuesto"],
        img: "fachada-02.jpg",
        alt: "Rótulo luminoso LED en fachada comercial",
        faqs: [
          { q: "¿Qué tipos de rótulo luminoso hacéis?", a: "Cajones de luz, banderolas y letras iluminadas. Proponemos el sistema según el tamaño de la fachada y cómo quieres que se vea de noche." },
          { q: "¿Consumen mucho?", a: "Usamos iluminación LED. En el presupuesto te indicamos el sistema concreto para tu pieza." },
        ],
      },
      {
        id: "sin-iluminacion",
        h2: "Sin iluminación",
        kicker: "Sin instalación eléctrica",
        text: "Composite, PVC, aluminio, metacrilato o vinilo sobre soporte rígido. Opción directa cuando el negocio abre de día o no quieres obra eléctrica.",
        specs: ["Composite, PVC, aluminio, metacrilato o vinilo", "Sin instalación eléctrica", "Imagen cuidada y duradera"],
        img: "fachada-04.jpg",
        alt: "Rótulo sin iluminación en composite y vinilo",
        faqs: [
          { q: "¿Cuándo conviene un rótulo sin luz?", a: "Cuando el local abre de día, cuando no quieres obra eléctrica o cuando el presupuesto pide una pieza clara y bien cortada." },
        ],
      },
      {
        id: "mantenimiento",
        h2: "Mantenimiento y reparación",
        kicker: "Rótulos ya instalados",
        text: "Revisamos y reparamos rótulos, los hayamos hecho nosotros o no: LED y transformadores fundidos, piezas sueltas, cableado o desgaste por sol y humedad. Mándanos fotos y te decimos qué tiene arreglo.",
        specs: ["Revisión y reparación", "También si no es nuestro", "Fotos y descripción de la avería"],
        img: "hero-taller.jpg",
        alt: "Reparación de rótulos en el taller de Vexil",
        faqs: [
          { q: "¿Reparáis rótulos que no habéis fabricado vosotros?", a: "Sí. Con fotos y una descripción de la avería te decimos qué se puede hacer." },
        ],
      },
    ],
    faqH2: "Preguntas frecuentes de rótulos",
    faqs: [
      { q: "¿Qué tipo de rótulo me conviene?", a: "Depende de la fachada, de si abres de noche y de cómo quieres que se lea tu marca. Te proponemos letras corpóreas, un luminoso, neón LED o una pieza sin luz." },
      { q: "¿También hacéis el montaje?", a: "Sí. Podemos fabricar e instalar el rótulo, o entregar solo la pieza si el montaje lo hace tu equipo u otra partida de obra." },
      { q: "¿Podéis cortar las letras en el taller?", a: "Sí. El <a data-rel=\"servicios/corte/\">corte láser y CNC</a> es el mismo con el que fabricamos letras y placas." },
    ],
    contactH2: "¿Qué rótulo necesita tu negocio?",
    contactLead: "Cuéntanos qué buscas o qué le pasa al que ya tienes. Con una foto de la fachada y unas medidas aproximadas te preparamos una propuesta.",
    related: [
      { href: "servicios/fachadas/", anchor: "rótulo y revestimiento de fachada" },
      { href: "servicios/iluminacion-decorativa/", anchor: "iluminación decorativa del local" },
      { href: "servicios/corte/", anchor: "corte láser y CNC" },
      { href: "franquicias/", anchor: "rotulación para franquicias" },
    ],
    waMessage: "Hola, os escribo por letras corpóreas y rótulos.",
  },

  "impresion-digital": {
    slug: "impresion-digital",
    breadcrumb: "Impresión digital",
    title: "Impresión de gran formato y lonas | Vexil Alicante",
    description: "Lonas, vinilos, microperforado, murales y paneles. Los imprimimos y, si lo quieres, los colocamos. Pide tu propuesta.",
    eyebrow: "Impresión digital",
    h1: "Impresión de gran formato en Alicante: lonas y vinilos",
    lead: "Imprimimos lonas, vinilos, murales y paneles en nuestro taller. Puedes llevarte solo la producción o pedirnos también la colocación.",
    pills: [
      { icon: "print", title: "Taller propio", sub: "Gran formato" },
      { icon: "wb_sunny", title: "Interior y exterior", sub: "El soporte adecuado" },
      { icon: "layers", title: "Vinilos y lonas", sub: "A la medida" },
      { icon: "handyman", title: "También colocamos", sub: "Si lo necesitas" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver materiales",
    trust: "Impresión de gran formato. Colocación si la necesitas.",
    heroImg: "fachada-04.jpg",
    heroAlt: "Impresión de gran formato y vinilos en el taller de Vexil",
    whyEyebrow: "Material",
    whyH2: "El soporte adecuado según dónde va",
    whyLead: "Un vinilo de escaparate, una lona de valla y un mural de pared no piden el mismo material. Si el trabajo forma parte de un <a data-rel=\"servicios/interiorismo-comercial/\">proyecto de interiorismo</a>, de <a data-rel=\"servicios/stands/\">gráfica para stands</a> o de <a data-rel=\"servicios/vehiculos/\">vinilos para coche y furgoneta</a>, lo encajamos. ¿Necesitas <a data-rel=\"obra-nueva/\">carteles de obra</a>? Tenemos una página para promotoras.",
    benefits: [
      { icon: "wb_sunny", title: "El material correcto", text: "Vinilo, lona o rígido según exterior, interior, cristal o pared.", tag: "Material" },
      { icon: "palette", title: "Color de marca", text: "Ajustamos la impresión para que los colores salgan como en tu manual.", tag: "Color" },
      { icon: "handyman", title: "Del taller a la pared", text: "Imprimimos, cortamos y colocamos. O te entregamos la gráfica lista.", tag: "Montaje" },
    ],
    solutionsH2: "Vinilos decorativos y murales a medida",
    solutionsLead: "Imprimimos vinilos decorativos y murales para negocios y viviendas, a la medida de la pared. Elegimos el vinilo según la superficie y, si lo quieres, lo colocamos. ¿Es para un proyecto de interiorismo? <a data-rel=\"servicios/interiorismo-comercial/\">Mira cómo trabajamos con estudios</a>.",
    solutions: [
      { tech: "Vinilo adhesivo", title: "Vinilos adhesivos de interior y exterior", text: "Corte, fondos impresos y laminados mate o brillo según el uso.", specs: ["Paredes, composite o aluminio", "Acabado mate o brillo"], img: "fachada-04.jpg", cap: "Vinilo adhesivo", alt: "Vinilo adhesivo impreso para pared y escaparate" },
      { tech: "Lona", title: "Lonas publicitarias", text: "Gran formato con ollados y refuerzos para fachadas y vallas. También backlight para cajas de luz.", specs: ["Ollados y soldadura", "Fachadas, vallas y eventos", "También backlight"], img: "caso-02.jpg", cap: "Lona de gran formato", alt: "Lona publicitaria de gran formato" },
      { tech: "Microperforado", title: "Vinilo de luna y microperforado", text: "Se ve desde dentro hacia la calle, con gráfica por fuera. Para escaparates y lunas.", specs: ["Se ve desde dentro hacia fuera", "Escaparates y lunas"], img: "fachada-04.jpg", cap: "Microperforado", alt: "Vinilo microperforado en luna o escaparate" },
      { tech: "Rígido", title: "Paneles rígidos y carteles", text: "Foam, composite y canvas cortados a medida, listos para colgar o instalar.", specs: ["Foam, composite o canvas", "Corte a medida"], img: "caso-01.jpg", cap: "Panel rígido", alt: "Panel rígido impreso para interior" },
      { tech: "Pared", title: "Vinilos decorativos y murales impresos a medida", text: "Vinilos decorativos y murales a medida para negocios y viviendas. Los imprimimos y, si lo quieres, los colocamos.", specs: ["A medida de la pared", "Vinilo o papel mural", "Colocación si la pides"], img: "caso-01.jpg", cap: "Mural a medida", alt: "Mural de vinilo decorativo impreso a medida" },
    ],
    faqH2: "Preguntas frecuentes de impresión digital",
    faqs: [
      { q: "¿Qué puedo imprimir?", a: "Adhesivos y pegatinas, vinilos para escaparates y paredes, cartelería y otros soportes de gran formato. Si tienes una idea que no encaja en esta lista, pregúntanos." },
      { q: "¿Qué tipos de vinilo utilizáis?", a: "Trabajamos varios: monomérico (una opción económica para uso promocional y de corta o media duración), polimérico (pensado para larga duración), transparente y de alta adherencia para superficies difíciles. Te recomendamos el más adecuado según dónde vaya a ir colocado." },
      { q: "¿Los adhesivos se pueden laminar?", a: "Sí. El laminado protege la impresión y alarga su vida, y se ofrece en acabado brillo o mate." },
      { q: "¿Puedo pedir adhesivos con la forma de mi diseño?", a: "Sí, se pueden cortar por la silueta del dibujo, además de con formas sencillas como recta, redondeada, circular u ovalada." },
      { q: "¿Hay un pedido mínimo?", a: "En adhesivos, el pedido mínimo es de 1 m². Cuantos más metros pides, mayor es el descuento por volumen." },
      { q: "¿Los precios incluyen IVA?", a: "Nuestras tarifas se indican sin IVA; a ellas se aplica el 21 % de IVA." },
      { q: "¿Se puede quitar el vinilo sin dañar la pared?", a: "Depende de la superficie y del vinilo utilizado. Sobre paredes pintadas en buen estado suele poder retirarse, pero no podemos asegurarlo en todos los casos, así que lo valoramos contigo antes de empezar." },
      { q: "¿Servís para decorar una vivienda?", a: "Sí. Imprimimos vinilos decorativos y murales a medida también para particulares. Si es un <a data-rel=\"servicios/interiorismo-comercial/\">proyecto de interiorismo</a> de un estudio, mira cómo trabajamos con planos." },
      { q: "¿Qué archivo tengo que enviaros?", a: "Lo ideal es un PDF o un archivo vectorial (AI o SVG) con los textos convertidos a curvas. Si solo tienes una imagen, cuéntanoslo y te decimos si tiene calidad suficiente para el tamaño que necesitas." },
    ],
    contactH2: "¿Qué necesitas imprimir?",
    contactLead: "Dinos qué es, dónde va y qué medidas tiene. Si tienes el archivo, mándalo; si no, lo diseñamos contigo.",
    related: [
      { href: "servicios/interiorismo-comercial/", anchor: "proyecto de interiorismo" },
      { href: "servicios/stands/", anchor: "gráfica para stands" },
      { href: "servicios/vehiculos/", anchor: "vinilos para coche y furgoneta" },
      { href: "obra-nueva/", anchor: "carteles de obra" },
    ],
    waMessage: "Hola, os escribo por lonas e impresión de gran formato.",
  },

  vehiculos: {
    slug: "vehiculos",
    breadcrumb: "Rotulación de vehículos",
    title: "Vinilos para coche y furgoneta | Vexil Alicante",
    description: "Franjas, logotipos y textos en vinilo fundido para coche o furgoneta. Diseño y colocación en nuestro taller. Pide tu propuesta.",
    eyebrow: "Rotulación de vehículos",
    h1: "Vinilos para coche y furgoneta en Alicante",
    lead: "Franjas, logotipos, textos y detalles en puertas, laterales, capó o luneta. Trabajamos con vinilo fundido, que se adapta a las curvas de la carrocería. Personalizamos por zonas: no hacemos forrado completo ni cambio de color.",
    pills: [
      { icon: "directions_car", title: "Franjas", sub: "Y detalles a medida" },
      { icon: "brush", title: "Logotipos y textos", sub: "Donde mejor se lean" },
      { icon: "verified", title: "Vinilo fundido", sub: "Se adapta a la carrocería" },
      { icon: "design_services", title: "Tu diseño o el nuestro", sub: "Lo revisamos contigo" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver qué personalizamos",
    trust: "Vinilo fundido para personalizar tu coche o furgoneta. Colocación en taller.",
    heroImg: "hero-taller.jpg",
    heroAlt: "Personalización de vehículo con vinilo fundido en el taller de Vexil",
    whyEyebrow: "Personalización",
    whyH2: "Personalización parcial en vinilo fundido",
    whyLead: "Cuéntanos el modelo y qué quieres poner. El <a data-rel=\"servicios/impresion-digital/\">vinilo impreso</a> sale del mismo taller.",
    benefits: [
      { icon: "brush", title: "Tu idea o la nuestra", text: "Puedes traer tu diseño o lo creamos contigo. Lo ideal es un archivo vectorial o una imagen nítida.", tag: "Diseño" },
      { icon: "layers", title: "Vinilo fundido", text: "Se adapta a las formas del vehículo. La duración depende del sol y del cuidado.", tag: "Material" },
      { icon: "format_paint", title: "Retirada cuidadosa", text: "Si la pintura está en buen estado y el vinilo se retira bien, no debería dañarse. Lo revisamos antes.", tag: "Pintura" },
      { icon: "local_car_wash", title: "Cómo mantenerlo", text: "Evita el agua a presión muy cerca de los bordes y usa productos neutros.", tag: "Cuidado" },
    ],
    solutionsH2: "Qué personalizamos en el vehículo",
    solutionsLead: "Franjas, logos y textos por zonas. No cubrimos el vehículo entero ni cambiamos el color.",
    solutions: [
      { tech: "Corte o impresión", title: "Logotipos y textos", text: "Nombre, teléfono, web o el dibujo que quieras, en puertas, laterales o luna.", specs: ["Archivo vectorial o imagen nítida", "Puertas, laterales o luneta"], img: "hero-taller.jpg", cap: "Logo y textos", alt: "Logotipo en vinilo sobre puerta de vehículo" },
      { tech: "Detalle", title: "Franjas y acentos", text: "Líneas, formas y acentos en laterales, capó o zócalo, recortados a medida.", specs: ["Turismos y furgones", "Vinilo fundido"], img: "caso-01.jpg", cap: "Franjas a medida", alt: "Franjas de vinilo en el lateral de un coche" },
      { tech: "Luna", title: "Detalles en luneta", text: "Textos o gráficos en la luna cuando el diseño y la visibilidad lo permiten.", specs: ["Visibilidad valorada antes", "Diseño a medida"], img: "fachada-04.jpg", cap: "Luneta", alt: "Texto en vinilo sobre luneta de vehículo" },
    ],
    faqH2: "Preguntas frecuentes de rotulación de vehículos",
    faqs: [
      { q: "¿Hacéis forrado completo o cambio de color?", a: "No. Nos centramos en personalización parcial: franjas, logos y textos." },
      { q: "¿Qué vinilo utilizáis?", a: "Vinilo fundido, pensado para adaptarse a las formas del vehículo. Su duración depende de la exposición al sol y de cómo lo cuides." },
      { q: "¿Puedo llevar mi propio diseño?", a: "Sí. Puedes traer tu diseño o lo creamos contigo." },
      { q: "¿Se estropea la pintura al quitar el vinilo?", a: "Si la pintura está en buen estado y el vinilo se retira correctamente, no debería dañarse. Si hay repintados o golpes, lo revisamos antes." },
    ],
    contactH2: "¿Qué le quieres poner?",
    contactLead: "Mándanos una foto del vehículo y tu idea. Te proponemos diseño y colocación.",
    related: [{ href: "servicios/impresion-digital/", anchor: "impresión de vinilo" }],
    waMessage: "Hola, os escribo por vinilos para coche y furgoneta.",
  },

  "interiorismo-comercial": {
    slug: "interiorismo-comercial",
    breadcrumb: "Interiorismo comercial",
    title: "Interiorismo comercial: murales y letras de interior | Vexil Alicante",
    description: "Murales, letras corpóreas de interior, vinilo al ácido, señalética e iluminación para locales, oficinas y clínicas. También para estudios. Pide tu propuesta.",
    eyebrow: "Interiores comerciales",
    h1: "Interiorismo comercial: murales, letras y gráfica de interior",
    lead: "Letras corpóreas de recepción, murales, vinilo en cristal, señalética e iluminación. Lo pedimos un negocio directo o un estudio con planos: fabricamos e instalamos.",
    pills: [
      { icon: "letter_a", title: "Letras de interior", sub: "Corpóreas y logos" },
      { icon: "print", title: "Murales", sub: "A medida de la pared" },
      { icon: "window", title: "Cristales", sub: "Vinilo al ácido" },
      { icon: "architecture", title: "Estudios", sub: "Desde planos" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver qué hacemos",
    trust: "Para negocios y para estudios de interiorismo.",
    heroImg: "caso-01.jpg",
    heroAlt: "Interior comercial con mural y lettering ejecutado por Vexil",
    whyEyebrow: "Cómo trabajamos",
    whyH2: "Tu local o el proyecto de un estudio",
    whyLead: "Si tienes un negocio, cuéntanos qué quieres en la recepción, la pared o el cristal. Si eres estudio, partimos de planos, alzados o renders y nos coordinamos con la obra. Mira también <a data-rel=\"profesionales/\">cómo trabajamos con estudios</a>.",
    benefits: [
      { icon: "print", title: "Murales y revestimientos gráficos", text: "Impresión a medida de la pared, en vinilo o papel mural, colocada por nosotros.", tag: "Murales" },
      { icon: "window", title: "Vinilo al ácido para mamparas y cristaleras", text: "Bandas, tramas, logotipos y privacidad para salas, despachos y consultas. Dejan pasar la luz y reducen la visión desde fuera.", tag: "Cristal" },
      { icon: "letter_a", title: "Letras y logos corpóreos de interior", text: "Recepciones y paredes de marca, con o sin luz, en PVC, metacrilato, composite o madera.", tag: "Relieve" },
      { icon: "plaque", title: "Señalética e iluminación", text: "Placas, directorios y luz decorativa alineados con el resto del espacio.", tag: "Conjunto" },
    ],
    solutionsH2: "Qué hacemos en interiores",
    solutionsLead: "Una sola pieza o el conjunto: murales, letras, cristales, <a data-rel=\"servicios/laminas-solares/\">láminas de control solar</a>, <a data-rel=\"servicios/senaletica/\">señalética</a>, <a data-rel=\"servicios/iluminacion-decorativa/\">iluminación decorativa</a> y <a data-rel=\"servicios/rotulos/\">letras corpóreas</a>.",
    solutions: [
      { tech: "Gran formato", title: "Murales y revestimientos gráficos", text: "Impresión a medida de la pared, en vinilo o papel mural, colocada por nosotros.", specs: ["Vinilo o papel mural", "A medida de la pared", "Lo colocamos nosotros"], img: "caso-01.jpg", cap: "Mural", alt: "Mural gráfico de interior colocado a medida" },
      { tech: "Cristal", title: "Vinilo al ácido para mamparas y cristaleras", text: "Bandas, tramas, logotipos y privacidad para salas, despachos y consultas. Dejan pasar la luz y reducen la visión desde fuera.", specs: ["Mamparas y cristaleras", "Efecto arenado", "Privacidad con luz"], img: "caso-04.jpg", cap: "Vinilo al ácido", alt: "Vinilo al ácido en mampara de oficina" },
      { tech: "Relieve", title: "Letras y logos corpóreos de interior", text: "Recepciones y paredes de marca, con o sin luz, en PVC, metacrilato, composite o madera.", specs: ["PVC, metacrilato, composite o madera", "Con luz o sin luz", "Recepciones y paredes de marca"], img: "caso-03.jpg", cap: "Logo en recepción", alt: "Letras corpóreas de marca en recepción de interior" },
      { tech: "Conjunto", title: "Señalética e iluminación", text: "Placas, directorios y luz decorativa alineados con el resto del espacio.", specs: ["Placas y directorios", "Luz decorativa", "Lo montamos nosotros"], img: "plano-totem.jpg", cap: "Señalética de interior", alt: "Placas y directorio de interiorismo comercial" },
    ],
    spacesH2: "Oficinas, retail, clínicas, hostelería y hoteles",
    spaces: [
      { title: "Oficinas", img: "caso-04.jpg", alt: "Oficina con gráfica de marca y vinilo en cristalera" },
      { title: "Retail", img: "caso-01.jpg", alt: "Tienda con mural y lettering de interior" },
      { title: "Clínicas", img: "caso-03.jpg", alt: "Recepción de clínica con vinilo y logo" },
      { title: "Hostelería", img: "fachada-hero.jpg", alt: "Interior de hostelería con gráfica de marca" },
    ],
    faqH2: "Preguntas frecuentes de interiorismo comercial",
    faqs: [
      { q: "¿Puedo pediros solo unas letras o un mural?", a: "Sí. Un negocio puede encargarnos una pieza concreta: letras de recepción, un mural, vinilo en cristal u otra gráfica de interior." },
      { q: "¿También trabajáis con estudios de interiorismo?", a: "Sí. Partimos de planos, alzados o renders, revisamos medidas y materiales, y nos coordinamos con la obra." },
      { q: "¿Podéis hacer solo una parte del proyecto?", a: "Sí. Todo el conjunto gráfico o solo lo que necesites." },
      { q: "¿Quién instala?", a: "Nosotros. Si hay obra, nos coordinamos con la dirección de obra para entrar en el momento adecuado." },
    ],
    contactH2: "Cuéntanos el espacio",
    contactLead: "Una foto, un plano o una idea. Te preparamos propuesta. Si te hacen falta fichas del fabricante, mira <a data-rel=\"materiales/\">materiales y acabados</a>.",
    related: [
      { href: "servicios/laminas-solares/", anchor: "láminas de control solar" },
      { href: "servicios/senaletica/", anchor: "señalética" },
      { href: "servicios/iluminacion-decorativa/", anchor: "iluminación decorativa" },
      { href: "servicios/rotulos/", anchor: "letras corpóreas" },
      { href: "profesionales/", anchor: "cómo trabajamos con estudios" },
      { href: "materiales/", anchor: "materiales y acabados" },
    ],
    waMessage: "Hola, os escribo por interiorismo comercial / letras o mural de interior.",
  },

  "laminas-solares": {
    slug: "laminas-solares",
    variant: "types",
    breadcrumb: "Láminas solares",
    title: "Láminas solares y control solar | Vexil Alicante",
    description: "Láminas de control solar y privacidad para fachadas, oficinas y locales en Alicante. Menos calor sin cambiar el cristal. Pide tu propuesta.",
    eyebrow: "Control solar para edificios, oficinas y locales",
    h1: "Láminas solares en Alicante: control solar y privacidad",
    lead: "Colocamos láminas de control solar en fachadas acristaladas, oficinas, comercios y viviendas. Reducen el calor y el deslumbramiento, y protegen el mobiliario del sol. También hay opciones de privacidad.",
    pills: [
      { icon: "wb_sunny", title: "Control solar", sub: "Menos calor" },
      { icon: "visibility_off", title: "Privacidad", sub: "Sin que te vean desde fuera" },
      { icon: "apartment", title: "Edificios", sub: "Oficinas y locales" },
      { icon: "architecture", title: "Sobre proyecto", sub: "Estudios y obra" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver tipos de lámina",
    trust: "Colocación en oficinas, comercios, viviendas y proyectos de obra.",
    heroImg: "fachada-04.jpg",
    heroAlt: "Lámina de control solar en fachada acristalada",
    whyEyebrow: "Sobre el cristal que ya tienes",
    whyH2: "Control solar sin cambiar el cristal",
    whyLead: "Sin tocar la carpintería. Si buscas <a data-rel=\"servicios/interiorismo-comercial/\">vinilo al ácido para mamparas</a> o cristaleras, lo ejecutamos en nuestros proyectos de interiores. Si también renovamos el frente, mira <a data-rel=\"servicios/fachadas/\">renovación de fachada</a>.",
    benefits: [
      { icon: "thermostat", title: "Menos calor y deslumbramiento", text: "La lámina de control solar reduce el sol que entra y hace el interior más confortable.", tag: "Confort" },
      { icon: "visibility_off", title: "Privacidad", text: "Reflectantes, esmeriladas o translúcidas: dejan pasar la luz y limitan la visión desde fuera.", tag: "Intimidad" },
      { icon: "wb_sunny", title: "Protege el interior", text: "Ayuda a cuidar mobiliario y superficies expuestos al sol.", tag: "Protección" },
      { icon: "architecture", title: "También sobre proyecto", text: "Si eres estudio o constructora, partimos de tu proyecto y revisamos el vidrio antes de proponer la lámina.", tag: "Obra" },
    ],
    typesH2Intro: "Tipos de lámina",
    typesLead: "Control solar, privacidad o ambas en la misma fachada.",
    types: [
      {
        id: "arquitectura",
        h2: "Lámina solar arquitectónica para fachadas y oficinas",
        kicker: "Control solar",
        text: "Para edificios con mucha superficie acristalada, donde el sol calienta despachos y salas buena parte del año. Revisamos el tipo de vidrio antes de proponer la lámina adecuada.",
        specs: ["Fachadas y oficinas", "Menos calor y deslumbramiento", "Sin cambiar el vidrio"],
        img: "fachada-hero.jpg",
        alt: "Lámina solar arquitectónica en fachada de oficinas",
        faqs: [
          { q: "¿Oscurece mucho el interior?", a: "Depende del modelo: los hay más claros y más oscuros. Te ayudamos a elegir el equilibrio entre control del sol y luz natural." },
        ],
      },
      {
        id: "privacidad",
        h2: "Láminas de privacidad",
        kicker: "Sin que te vean desde fuera",
        text: "Reflectantes, esmeriladas o translúcidas: dejan pasar la luz y limitan las miradas desde fuera.",
        specs: ["Reflectante, esmerilada o translúcida", "Despachos y consultas", "Luz natural"],
        img: "caso-03.jpg",
        alt: "Lámina de privacidad en cristalera de oficina",
        faqs: [
          { q: "¿Se puede ver desde fuera?", a: "Depende del modelo y de la luz. Algunas láminas reflectantes limitan la visión desde fuera durante el día; de noche, con luz interior, el efecto puede invertirse. Las esmeriladas dan privacidad a cualquier hora." },
        ],
      },
      {
        id: "obra",
        h2: "Láminas de control solar en proyectos de obra",
        kicker: "Estudios y constructoras",
        text: "Si eres estudio o constructora, partimos de tu proyecto y revisamos el vidrio antes de proponer la lámina. <a data-rel=\"profesionales/\">Así trabajamos con estudios y constructoras</a>.",
        specs: ["Revisión del vidrio", "Coordinación de proyecto", "Ver página de profesionales"],
        img: "fachada-hero.jpg",
        alt: "Proyecto de láminas solares en obra nueva",
        faqs: [
          { q: "¿Trabajáis con el estudio o la constructora?", a: "Sí. Mira <a data-rel=\"profesionales/\">estudios y constructoras</a> para ver cómo encajamos en la obra." },
        ],
      },
    ],
    faqH2: "Preguntas frecuentes de láminas solares",
    faqs: [
      { q: "¿Se puede colocar en cualquier cristal?", a: "En la mayoría de cristales sí, pero algunos tipos de vidrio pueden sufrir tensiones térmicas con determinadas láminas. Revisamos tu cristal antes de proponerte un modelo." },
      { q: "¿Se coloca por dentro o por fuera?", a: "Depende del tipo de lámina y del cristal. Lo más habitual es colocarla por el interior, pero te indicamos la mejor opción en cada caso." },
    ],
    contactH2: "¿Qué quieres resolver en el cristal?",
    contactLead: "Cuéntanos dónde está, hacia dónde da y qué necesitas: calor, reflejos o privacidad. Con unas fotos te orientamos.",
    related: [
      { href: "servicios/interiorismo-comercial/", anchor: "vinilo al ácido para mamparas" },
      { href: "servicios/fachadas/", anchor: "renovación de fachada" },
      { href: "profesionales/", anchor: "estudios y constructoras" },
      { href: "materiales/", anchor: "materiales y acabados" },
    ],
    waMessage: "Hola, os escribo por láminas solares.",
  },

  corte: {
    slug: "corte",
    breadcrumb: "Corte a medida",
    title: "Corte láser y fresado CNC a medida | Vexil Alicante",
    description: "Corte láser de metacrilato y fresado CNC de composite, PVC y madera. Una pieza o series, desde tu archivo. Pide presupuesto.",
    eyebrow: "Corte láser y fresado CNC",
    h1: "Corte láser y CNC a medida en Alicante",
    lead: "Cortamos y grabamos metacrilato con láser, y fresamos composite, PVC y madera con CNC. Tráenos tu archivo o tu idea y lo convertimos en pieza.",
    pills: [
      { icon: "flare", title: "Láser", sub: "Metacrilato" },
      { icon: "precision_manufacturing", title: "CNC", sub: "Composite, PVC, madera" },
      { icon: "category", title: "A medida", sub: "Una pieza o series" },
      { icon: "draft", title: "Tu archivo", sub: "O lo preparamos" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver qué cortamos",
    trust: "La misma maquinaria con la que fabricamos letras y placas.",
    heroImg: "hero-taller.jpg",
    heroAlt: "Corte láser y fresado CNC en el taller de Vexil",
    whyEyebrow: "Dos máquinas",
    whyH2: "Láser para metacrilato, CNC para el resto",
    whyLead: "El láser da detalle en metacrilato. El CNC fresa composite, PVC y madera. Con eso fabricamos <a data-rel=\"servicios/rotulos/\">letras corpóreas</a> y <a data-rel=\"servicios/senaletica/\">placas de metacrilato</a>.",
    benefits: [
      { icon: "flare", title: "Corte láser de metacrilato", text: "Corte y grabado para logos, placas y piezas con canto limpio.", tag: "Láser" },
      { icon: "precision_manufacturing", title: "Fresado CNC", text: "Composite, PVC y madera para letras, bandejas y piezas a medida.", tag: "CNC" },
      { icon: "inventory_2", title: "De una pieza a una serie", text: "Fabricamos una unidad o varias iguales a partir del mismo archivo.", tag: "Series" },
      { icon: "draft", title: "Partimos de tu archivo", text: "Vectorial con medidas reales, o te ayudamos a prepararlo.", tag: "Archivo" },
    ],
    solutionsH2: "Qué cortamos y fresamos",
    solutionsLead: "Metacrilato al láser. Composite, PVC y madera al CNC.",
    solutions: [
      { tech: "Láser", title: "Corte láser de metacrilato", text: "Corte y grabado de placas, logos y piezas de detalle.", specs: ["Placas, logos y detalle", "Canto limpio o grabado", "Metacrilato"], img: "plano-totem.jpg", cap: "Metacrilato al láser", alt: "Pieza de metacrilato cortada con láser" },
      { tech: "CNC", title: "Fresado CNC a medida", text: "Composite, PVC y madera para letras, bandejas y piezas de stand.", specs: ["Composite, PVC y madera", "Letras, bandejas y piezas", "Fresado a medida"], img: "hero-taller.jpg", cap: "Fresado CNC", alt: "Pieza fresada con CNC en el taller" },
      { tech: "Series", title: "Series y recambios", text: "La misma pieza, las veces que haga falta, a partir de tu archivo.", specs: ["Una pieza o varias", "Mismo archivo reutilizado"], img: "hero-taller.jpg", cap: "Serie corta", alt: "Serie de piezas cortadas a medida" },
      { tech: "Conjunto", title: "Corte integrado en el proyecto", text: "La pieza entra en un rótulo, una placa o un stand; no se entrega suelta si forma parte de un conjunto.", specs: ["Para rótulo, placa o stand", "Montaje o entrega"], img: "fachada-03.jpg", cap: "Pieza de proyecto", alt: "Letras cortadas listas para un rótulo" },
    ],
    faqH2: "Preguntas frecuentes de corte láser y CNC",
    faqs: [
      { q: "¿Qué diferencia hay entre corte CNC y corte láser?", a: "La fresadora CNC corta y talla materiales más gruesos, como composite, PVC y madera. El láser es más fino y preciso: lo usamos para cortar y grabar metacrilato." },
      { q: "¿Qué materiales podéis cortar?", a: "El láser, metacrilato. El CNC, composite, PVC y madera. Si tienes otro material, dinos cuál y te confirmamos si podemos trabajarlo." },
      { q: "¿Hacéis una sola pieza o solo series?", a: "Desde una única pieza hasta series. Cuéntanos qué necesitas y te presupuestamos." },
      { q: "¿Qué archivo necesito enviar?", a: "Un archivo vectorial (DXF, SVG, AI o PDF vectorial) con las medidas reales y los textos convertidos a curvas. Si solo tienes un boceto o una imagen, podemos ayudarte a prepararlo." },
      { q: "¿Cómo se calcula el precio?", a: "Depende del material, del tamaño, de la complejidad del corte y de la cantidad. Envía tu archivo o tu idea y te preparamos un presupuesto." },
    ],
    contactH2: "Mándanos tu archivo",
    contactLead: "En vectorial si lo tienes. Si no, te ayudamos a prepararlo.",
    related: [
      { href: "servicios/rotulos/", anchor: "letras corpóreas" },
      { href: "servicios/senaletica/", anchor: "placas de metacrilato" },
    ],
    waMessage: "Hola, os escribo por corte láser y CNC a medida.",
  },

  stands: {
    slug: "stands",
    breadcrumb: "Stands para ferias",
    title: "Stands para ferias y photocalls | Vexil Alicante",
    description: "Photocalls, tótems, letras de gran tamaño y gráfica para ferias y eventos. Diseño y producción en nuestro taller. Pide tu propuesta.",
    eyebrow: "Stands para ferias y eventos",
    h1: "Stands para ferias: photocalls, tótems y gráfica",
    lead: "Diseñamos y producimos en nuestro taller la gráfica de tu stand, photocalls, tótems y letras de gran formato. Piezas pensadas para montarse con rapidez y leerse a distancia en el recinto.",
    pills: [
      { icon: "photo_camera", title: "Photocall", sub: "Listo para foto" },
      { icon: "view_quilt", title: "Tótems", sub: "Y gráfica de pasillo" },
      { icon: "print", title: "Gran formato", sub: "Del mismo taller" },
      { icon: "event", title: "Tu fecha", sub: "Lo preparamos" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver elementos",
    trust: "Photocalls, tótems y gráfica de feria.",
    heroImg: "caso-04.jpg",
    heroAlt: "Photocall y gráfica de stand para feria producidos por Vexil",
    whyEyebrow: "Visibilidad en feria",
    whyH2: "Gráfica pensada para verse a distancia",
    whyLead: "La gráfica y las piezas grandes salen del mismo taller que las <a data-rel=\"servicios/impresion-digital/\">lonas y gran formato</a> y el <a data-rel=\"servicios/rotulos/\">neón LED</a>.",
    benefits: [
      { icon: "visibility", title: "Lectura desde el pasillo", text: "Tipografía, contraste y altura pensados para recinto ferial.", tag: "Lectura" },
      { icon: "photo_camera", title: "Photocall", text: "Fondos, logo y formato listos para foto.", tag: "Foto" },
      { icon: "print", title: "Gráfica de taller", text: "Lonas, rígidos y vinilos impresos aquí.", tag: "Producción" },
      { icon: "event", title: "Para tu fecha", text: "Partimos de la fecha del evento y preparamos las piezas.", tag: "Evento" },
    ],
    solutionsH2: "Elementos de stand que fabricamos",
    solutionsLead: "Puedes pedir el conjunto o solo el photocall.",
    solutions: [
      { tech: "Fondo", title: "Photocalls y backdrops", text: "Estructura y gráfica a medida de tu hueco, listas para foto.", specs: ["Estructura y gráfica a medida", "Listo para foto"], img: "caso-04.jpg", cap: "Photocall", alt: "Photocall de feria con gráfica a medida" },
      { tech: "Vertical", title: "Tótems y portabanners", text: "De la pieza ligera al tótem de producción propia.", specs: ["Pasillo y acceso", "Con luz o sin ella"], img: "plano-totem.jpg", cap: "Tótem", alt: "Tótem de stand para feria" },
      { tech: "Volumen", title: "Letras de gran tamaño", text: "Corpóreas de feria en PVC u otros materiales de taller, para foto y presencia.", specs: ["De mostrador a gran formato", "PVC u otros materiales", "Lacado o vinilo"], img: "caso-01.jpg", cap: "Letras de feria", alt: "Letras de gran tamaño para stand" },
      { tech: "Gráfica", title: "Gráfica del stand", text: "Paneles, lonas y cartelería con tu imagen de marca.", specs: ["Paneles, lonas y cartelería", "Diseño y producción"], img: "caso-02.jpg", cap: "Gráfica de stand", alt: "Gráfica de gran formato para stand de feria" },
    ],
    faqH2: "Preguntas frecuentes de stands",
    faqs: [
      { q: "¿Qué hacéis para stands y eventos?", a: "Photocalls, tótems, letras de gran tamaño y la gráfica del stand. Lo diseñamos y lo producimos en el taller." },
      { q: "¿Puedo reutilizar las piezas en otros eventos?", a: "Sí. Podemos diseñar elementos desmontables para que los uses en más de una feria." },
      { q: "¿Qué información necesitáis para presupuestar?", a: "Las medidas del espacio, la fecha del evento, tu logotipo y qué piezas quieres: photocall, tótems, letras o gráfica." },
      { q: "¿Podéis hacer gráficas y cartelería para el stand?", a: "Sí. Imprimimos las gráficas, los paneles y la cartelería con tu imagen de marca." },
    ],
    contactH2: "¿Cuándo es tu feria?",
    contactLead: "Dinos la fecha, las medidas del espacio y qué quieres contar. Te preparamos la propuesta.",
    related: [
      { href: "servicios/impresion-digital/", anchor: "lonas y gran formato" },
      { href: "servicios/rotulos/", anchor: "neón LED" },
    ],
    waMessage: "Hola, os escribo por stands para ferias.",
  },

  "iluminacion-decorativa": {
    slug: "iluminacion-decorativa",
    breadcrumb: "Iluminación decorativa",
    title: "Iluminación LED decorativa para locales | Vexil",
    description: "Tiras y perfiles LED, paneles retroiluminados y luz de acento para tiendas, bares y oficinas en Alicante. Coordinada con tu rótulo. Pide propuesta.",
    eyebrow: "Iluminación LED para locales",
    h1: "Iluminación decorativa LED para locales en Alicante",
    lead: "Tiras y perfiles LED, paneles retroiluminados y luz de acento para destacar un producto, una barra o una recepción. La planteamos junto al rótulo para que el local tenga una imagen coherente.",
    pills: [
      { icon: "light", title: "LED", sub: "Tiras y perfiles" },
      { icon: "highlight", title: "Acento", sub: "Producto y barra" },
      { icon: "home", title: "Interior", sub: "Tiendas, bares, oficinas" },
      { icon: "architecture", title: "Con el rótulo", sub: "Una sola imagen" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver aplicaciones",
    trust: "Luz de ambiente y de acento. Si buscas un rótulo luminoso o un neón con tu logo, míralo en Rótulos.",
    heroImg: "fachada-hero.jpg",
    heroAlt: "Iluminación decorativa LED en un local comercial",
    whyEyebrow: "Luz de ambiente",
    whyH2: "Luz para ambiente y acento, no para el cartel",
    whyLead: "Usamos la luz para destacar producto, recorrer una barra o ambientar una recepción. ¿Buscas un rótulo luminoso o un neón con tu logo? Míralo en <a data-rel=\"servicios/rotulos/\">rótulos luminosos y neón LED</a>. Si forma parte de <a data-rel=\"servicios/interiorismo-comercial/\">proyectos de interiores</a>, lo ejecutamos con el resto de partidas.",
    benefits: [
      { icon: "light_mode", title: "Ambiente del local", text: "Temperatura de color y capas de luz para retail, clínicas y hostelería.", tag: "Ambiente" },
      { icon: "highlight", title: "Acento en producto", text: "Tiras y perfiles para lineal de producto o barra.", tag: "Producto" },
      { icon: "architecture", title: "Integrada en el mueble", text: "Tiras en cornisa, huecos y estantes.", tag: "Lineal" },
      { icon: "bolt", title: "LED a medida", text: "Cortes a longitud y difusión homogénea para cada tramo.", tag: "A medida" },
    ],
    solutionsH2: "Aplicaciones de iluminación decorativa",
    solutionsLead: "Luz de espacio. El neón de logotipo y las cajas de luz de fachada están en Rótulos.",
    solutions: [
      { tech: "Perfil LED", title: "Perfiles y tiras LED a medida", text: "Cortes a longitud, esquinas y difusión homogénea para mueble o techo.", specs: ["Cornisas, estantes y barras", "Corte a longitud"], img: "caso-01.jpg", cap: "Tira LED", alt: "Perfil LED lineal en interior comercial" },
      { tech: "Acento", title: "Iluminación de producto", text: "Destacar lineal, escaparate interior o una pieza de marca.", specs: ["Acento dirigido", "Retail y exposiciones"], img: "caso-04.jpg", cap: "Luz de producto", alt: "Iluminación de acento sobre producto en tienda" },
      { tech: "Backlight", title: "Paneles retroiluminados de ambiente", text: "Superficies luminosas de interior, distintas de un rótulo de fachada.", specs: ["Recepciones y pasillos", "Ambiente, no cartel de fachada"], img: "caso-03.jpg", cap: "Panel luminoso", alt: "Panel retroiluminado de interior" },
      { tech: "Proyecto", title: "Luz junto al resto del local", text: "La planteamos con el rótulo y las partidas de interior para que todo encaje.", specs: ["Coordinada con el rótulo", "Integrada en el proyecto de interior"], img: "caso-03.jpg", cap: "Luz de proyecto", alt: "Iluminación decorativa coordinada con el local" },
    ],
    faqH2: "Preguntas frecuentes de iluminación decorativa",
    faqs: [
      { q: "¿Qué es la iluminación decorativa?", a: "Es la luz pensada para crear ambiente y destacar producto o espacios, no para leer un cartel." },
      { q: "¿Para qué espacios sirve?", a: "Para tiendas, bares, oficinas y otros locales donde la luz forma parte de la imagen." },
      { q: "¿Instaláis tiras y perfiles LED de interior?", a: "Sí. Las cortamos a medida y las instalamos en el local." },
      { q: "¿Necesito instalación eléctrica especial?", a: "La mayoría de piezas LED funcionan con un transformador a toma convencional. Si el montaje pide algo distinto, te lo indicamos en el presupuesto." },
    ],
    contactH2: "¿Qué quieres destacar?",
    contactLead: "Una barra, un escaparate, una pared de marca. Cuéntanos el espacio y te proponemos cómo iluminarlo.",
    related: [
      { href: "servicios/rotulos/", anchor: "rótulos luminosos y neón LED" },
      { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiores" },
    ],
    waMessage: "Hola, os escribo por iluminación decorativa LED.",
  },

  senaletica: {
    slug: "senaletica",
    breadcrumb: "Señalética y placas",
    title: "Señalética y placas de metacrilato | Vexil Alicante",
    description: "Placas de metacrilato, directorios y señales de orientación a medida en Alicante. Desde una placa hasta un edificio. Pide tu propuesta.",
    eyebrow: "Señalética y placas",
    h1: "Señalética y placas de metacrilato en Alicante",
    lead: "Placas de despacho, directorios, señales de orientación y carteles informativos, con la misma imagen que tu rótulo. Desde una sola placa hasta un edificio entero.",
    pills: [
      { icon: "badge", title: "Placas", sub: "Metacrilato a medida" },
      { icon: "domain", title: "Directorios", sub: "Plantas y empresas" },
      { icon: "plaque", title: "Orientación", sub: "Recorridos claros" },
      { icon: "letter_a", title: "Misma marca", sub: "Que tu rótulo" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver sistemas",
    trust: "Placas y orientación con la misma imagen que el resto del local.",
    heroImg: "plano-totem.jpg",
    heroAlt: "Directorio y placas de metacrilato de señalética Vexil",
    whyEyebrow: "También es marca",
    whyH2: "Señalética alineada con tu imagen",
    whyLead: "Es lo que leen tus visitantes cuando ya han entrado. Las placas salen del <a data-rel=\"servicios/corte/\">corte láser de metacrilato</a>; si forman parte de <a data-rel=\"servicios/interiorismo-comercial/\">proyectos de interiores</a> o de <a data-rel=\"obra-nueva/\">señalética para obra nueva</a>, lo coordinamos.",
    benefits: [
      { icon: "explore", title: "Orientación clara", text: "Recorridos claros en oficinas, clínicas, hoteles e industriales.", tag: "Orientación" },
      { icon: "badge", title: "Placas de la casa", text: "Mismo material y tipo que el rótulo principal.", tag: "Identidad" },
      { icon: "update", title: "Nombres que se actualizan", text: "Sistemas intercambiables para despachos y organigramas.", tag: "Modulares" },
      { icon: "gavel", title: "Informativas integradas", text: "Integramos las señales informativas en la misma familia gráfica.", tag: "Conjunto" },
    ],
    solutionsH2: "Sistemas de señalética",
    solutionsLead: "Del pictograma suelto al directorio de edificio.",
    solutions: [
      { tech: "Metacrilato", title: "Placas de despacho y sala", text: "Metacrilato, aluminio o composite. Fijas o con pieza intercambiable.", specs: ["Metacrilato, aluminio o composite", "Fijas o intercambiables", "Despachos, consultas y salas"], img: "plano-totem.jpg", cap: "Placa de sala", alt: "Placa de metacrilato para despacho" },
      { tech: "Modular", title: "Directorios de planta y edificio", text: "Listados de empresas o departamentos, actualizables.", specs: ["Empresas o departamentos", "Pared o tótem", "Actualizables"], img: "plano-totem.jpg", cap: "Directorio", alt: "Directorio de planta en un edificio" },
      { tech: "Pictogramas", title: "Señales de orientación", text: "Conjuntos coherentes para pasillos, parkings y naves.", specs: ["Pasillos, parkings y naves", "Pared, bandera o suelo"], img: "caso-02.jpg", cap: "Orientación", alt: "Señal de orientación en pasillo" },
      { tech: "Informativa", title: "Carteles informativos y de evacuación", text: "Cuando hay que señalizar, lo integramos al resto de la familia gráfica.", specs: ["Información y evacuación", "Misma familia gráfica"], img: "caso-02.jpg", cap: "Señal informativa", alt: "Cartel informativo de señalética de edificio" },
    ],
    faqH2: "Preguntas frecuentes de señalética",
    faqs: [
      { q: "¿Qué tipos de señalética podéis hacer?", a: "Señales de orientación, placas de puerta y despacho, directorios, carteles informativos y placas de profesional, entre otras. Se hacen a medida." },
      { q: "¿En qué materiales se fabrican las placas?", a: "Metacrilato, aluminio, PVC y composite, con impresión, corte o grabado según el diseño." },
      { q: "¿Podéis fabricar una sola placa?", a: "Sí. Hacemos desde una placa individual hasta la señalética completa de un edificio." },
      { q: "¿Sirve para exterior?", a: "Sí, con materiales adecuados para la intemperie. Dinos dónde va a colocarse." },
      { q: "¿Las señales de seguridad y evacuación cumplen normativa?", a: "La señalización de seguridad tiene requisitos específicos (tamaño, color, pictograma). Si necesitas señales de este tipo, indícanoslo desde el principio y confirma con tu técnico o mantenedor qué exige la normativa en tu caso." },
      { q: "¿Se pueden colocar sin taladrar?", a: "En muchas superficies sí, con adhesivo de montaje. Depende del peso y de la superficie." },
    ],
    contactH2: "¿Cuántas placas necesitas?",
    contactLead: "Una o cien. Cuéntanos el espacio y te proponemos una familia gráfica coherente.",
    related: [
      { href: "servicios/corte/", anchor: "corte láser de metacrilato" },
      { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiores" },
      { href: "obra-nueva/", anchor: "señalética para obra nueva" },
      { href: "profesionales/", anchor: "señalética para obra nueva" },
    ],
    waMessage: "Hola, os escribo por señalética y placas de metacrilato.",
  },
};

export const extraPages = {
  materiales: {
    slug: "materiales",
    path: "materiales/",
    breadcrumb: "Materiales",
    title: "Materiales y acabados para rotulación | Vexil Alicante",
    description: "Composite, metacrilato, vinilos y láminas solares: con qué trabajamos y dónde encaja cada uno. Si te hace falta la ficha del fabricante, te la mandamos.",
    eyebrow: "Con qué trabajamos",
    h1: "Materiales y acabados para rotulación y señalética",
    lead: "Composite, metacrilato, vinilos, PVC y láminas: qué usamos y para qué. Si tu proyecto pide la ficha del fabricante, te la enviamos.",
    pills: [
      { icon: "layers", title: "Composite", sub: "Fachadas y rígidos" },
      { icon: "flare", title: "Metacrilato", sub: "Letras y placas" },
      { icon: "print", title: "Vinilos", sub: "Impresión, corte, ácido" },
      { icon: "wb_sunny", title: "Láminas", sub: "Solar y privacidad" },
    ],
    ctaPrimary: "Consulta un material",
    ctaSecondary: "Ver familias",
    trust: "Trabajamos con estos acabados. Si necesitas la ficha del fabricante, te la enviamos.",
    heroImg: "fachada-01.jpg",
    heroAlt: "Muestrario de materiales de rotulación en el taller de Vexil",
    whyEyebrow: "Muestrario",
    whyH2: "Familias de material",
    whyLead: "Una referencia rápida. Desde aquí puedes ir al servicio donde se usa cada familia.",
    benefits: [
      { icon: "layers", title: "Composite de aluminio", text: "Revestimientos de fachada y soportes rígidos. Ver Fachadas.", tag: "Fachadas" },
      { icon: "flare", title: "Metacrilato", text: "Letras, placas y piezas de corte láser. Ver Rótulos y Señalética.", tag: "Corte" },
      { icon: "view_quilt", title: "PVC", text: "Letras, letras de feria y piezas fresadas. Ver Corte y Stands.", tag: "CNC" },
      { icon: "print", title: "Vinilos", text: "Impresión, corte y efecto ácido. Ver Impresión e Interiores.", tag: "Gráfico" },
      { icon: "wb_sunny", title: "Láminas solares y de privacidad", text: "Control solar y privacidad sobre el cristal existente.", tag: "Cristal" },
      { icon: "light", title: "LED y neón", text: "Luminosos, neón LED y luz decorativa. Ver Rótulos e Iluminación.", tag: "Luz" },
    ],
    solutionsH2: "Dónde se usa cada material",
    solutionsLead: "Si te hace falta la ficha del fabricante para un pliego o un plano, pídenosla.",
    solutions: [
      { tech: "Fachada", title: "Composite de aluminio", text: "Para revestir el frente del local y como soporte rígido impreso.", specs: ["Exterior e interior", "Fachadas y soportes rígidos"], img: "fachada-01.jpg", cap: "Composite", alt: "Panel composite de aluminio para fachada" },
      { tech: "Letras y placas", title: "Metacrilato", text: "Corte láser y grabado para letras, placas y detalle.", specs: ["Interior y exterior según espesor", "Letras, placas y detalle"], img: "plano-totem.jpg", cap: "Metacrilato", alt: "Placa de metacrilato cortada a medida" },
      { tech: "Gráfico", title: "Vinilos de impresión, corte y ácido", text: "Según superficie: pared, cristal, vehículo o rígido.", specs: ["Impresión, corte y efecto ácido", "Pared, cristal, vehículo o rígido"], img: "fachada-04.jpg", cap: "Vinilos", alt: "Muestras de vinilo de impresión y de corte" },
      { tech: "Cristal", title: "Láminas solares y de privacidad", text: "Sobre el vidrio existente, para calor, deslumbramiento o intimidad.", specs: ["Sobre el vidrio existente", "Calor, deslumbramiento o intimidad"], img: "fachada-hero.jpg", cap: "Láminas", alt: "Lámina solar sobre cristal de fachada" },
    ],
    faqH2: "Preguntas frecuentes de materiales",
    faqs: [
      { q: "¿Me podéis enviar la ficha del fabricante?", a: "Sí. Dinos el material concreto y te mandamos lo que figura en la ficha del fabricante." },
      { q: "¿Es un catálogo de venta?", a: "No. Es una referencia para especificar. El presupuesto se hace sobre el proyecto." },
    ],
    contactH2: "¿Qué material estás mirando?",
    contactLead: "Dinos el uso y te decimos qué encaja. Si te hace falta la ficha del fabricante, te la enviamos.",
    related: [
      { href: "profesionales/", anchor: "cómo trabajamos con estudios" },
      { href: "servicios/fachadas/", anchor: "rotulación de fachadas" },
      { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiorismo comercial" },
      { href: "servicios/laminas-solares/", anchor: "láminas de control solar" },
    ],
    waMessage: "Hola, os escribo por materiales y acabados.",
  },

  franquicias: {
    slug: "franquicias",
    path: "franquicias/",
    breadcrumb: "Franquicias",
    title: "Rotulación para franquicias y cadenas | Vexil",
    description: "Aplicamos el manual de marca en cada local: rótulos, fachada, vinilos y señalética. Mismo equipo en cada apertura en Alicante. Pide propuesta.",
    eyebrow: "Franquicias y cadenas",
    h1: "Rotulación para franquicias en Alicante",
    lead: "Trabajamos a partir de tu manual de marca y lo aplicamos en cada apertura: rótulo, fachada, vinilos, interiores y señalética. Adaptamos las piezas a las medidas reales de cada local.",
    pills: [
      { icon: "storefront", title: "Manual de marca", sub: "Aplicado a cada local" },
      { icon: "hub", title: "Misma persona", sub: "En cada apertura" },
      { icon: "architecture", title: "Aperturas", sub: "Y reformas de imagen" },
      { icon: "letter_a", title: "Rótulo y fachada", sub: "El mismo criterio" },
    ],
    ctaPrimary: "Pide tu propuesta",
    ctaSecondary: "Ver qué aplicamos",
    trust: "Misma imagen en cada local.",
    heroImg: "fachada-hero.jpg",
    heroAlt: "Fachada comercial con imagen de marca aplicada de forma uniforme",
    whyEyebrow: "Por qué un solo taller",
    whyH2: "Misma imagen en cada local",
    whyLead: "Adaptamos cada pieza a la fachada y las medidas de cada local sin salirnos del manual.",
    benefits: [
      { icon: "draft", title: "Tu manual, aplicado", text: "Adaptamos cada pieza a la fachada y las medidas de cada local sin salirnos de la marca.", tag: "Manual" },
      { icon: "support_agent", title: "La misma persona en cada apertura", text: "El mismo equipo mide, fabrica y monta en cada local.", tag: "Aperturas" },
      { icon: "storefront", title: "Aperturas y reformas", text: "Para locales nuevos y para renovar los que ya tenéis.", tag: "Red" },
    ],
    solutionsH2: "Qué aplicamos en cada local",
    solutionsLead: "Según el manual: rótulos, fachada, interiores y señalética.",
    solutions: [
      { tech: "Rótulo", title: "Rótulo de cada apertura", text: "La misma familia de letras y luz, adaptada a la fachada real.", specs: ["Según el manual de marca", "Adaptado a cada fachada"], img: "fachada-03.jpg", cap: "Rótulo de cadena", alt: "Rótulo de franquicia adaptado a la fachada" },
      { tech: "Frente", title: "Fachada del local", text: "Revestimiento y escaparate con el mismo criterio en cada apertura.", specs: ["Locales nuevos o reforma", "Revestimiento y escaparate"], img: "fachada-hero.jpg", cap: "Fachada de cadena", alt: "Fachada de local de cadena rotulada" },
      { tech: "Interior", title: "Vinilos y gráfica interior", text: "Lo que el manual pide dentro, ejecutado a medida del local.", specs: ["Según el manual", "A medida del local"], img: "caso-01.jpg", cap: "Interior de cadena", alt: "Gráfica interior de un local de franquicia" },
      { tech: "Orientación", title: "Señalética de la marca", text: "Placas y directorios con la tipografía del manual.", specs: ["Tipografía del manual", "Sala, baños y recorrido"], img: "plano-totem.jpg", cap: "Señalética de cadena", alt: "Placas de señalética con imagen de franquicia" },
    ],
    faqH2: "Preguntas frecuentes de franquicias",
    faqs: [
      { q: "¿Trabajáis a partir del manual de marca?", a: "Sí. Lo aplicamos a las medidas reales de cada local y te avisamos si algo no cabe o hay que adaptarlo." },
      { q: "¿Podéis hacer varios locales?", a: "Sí. El mismo equipo fabrica y monta en cada apertura de la zona." },
    ],
    contactH2: "¿Cuántos locales tenéis en la zona?",
    contactLead: "Envíanos el manual de marca y la lista de locales y te preparamos la propuesta.",
    related: [
      { href: "profesionales/", anchor: "cómo trabajamos con estudios y constructoras" },
      { href: "servicios/rotulos/", anchor: "letras corpóreas y rótulos" },
      { href: "servicios/fachadas/", anchor: "rotulación de fachadas" },
    ],
    waMessage: "Hola, os escribo por rotulación para franquicias.",
  },

  "obra-nueva": {
    slug: "obra-nueva",
    path: "obra-nueva/",
    breadcrumb: "Obra nueva",
    title: "Carteles de obra y señalética | Vexil Alicante",
    description: "Carteles de obra, lonas y señalética para promotoras en Alicante: de la obra a la entrega. Un solo proveedor. Envíanos los planos.",
    eyebrow: "Promotoras y constructoras",
    h1: "Carteles de obra y señalética para promociones",
    lead: "Te acompañamos en dos momentos: cartel de obra y gráfica mientras se construye, y señalética, placas y rotulación de zonas comunes cuando se entrega el edificio.",
    pills: [
      { icon: "print", title: "Cartel de obra", sub: "Diseño y producción" },
      { icon: "plaque", title: "Señalética", sub: "Del edificio terminado" },
      { icon: "badge", title: "Placas", sub: "Portal, plantas, garaje" },
      { icon: "architecture", title: "Un proveedor", sub: "De la obra a la entrega" },
    ],
    ctaPrimary: "Envíanos los planos",
    ctaSecondary: "Ver partidas",
    trust: "Cartel de obra y señalética de entrega.",
    heroImg: "caso-02.jpg",
    heroAlt: "Cartel de obra y gráfica de promoción producidos por Vexil",
    whyEyebrow: "De la obra a las llaves",
    whyH2: "Dos momentos de rotulación en una promoción",
    whyLead: "El contenido obligatorio del cartel lo aporta la promotora; nosotros lo diseñamos, lo producimos y lo colocamos.",
    benefits: [
      { icon: "print", title: "Carteles de obra", text: "Impresión de gran formato en nuestro taller y montaje en obra. El contenido obligatorio del cartel lo aporta la promotora; nosotros lo diseñamos, lo producimos y lo colocamos.", tag: "Durante la obra" },
      { icon: "plaque", title: "Señalética del edificio: portal, plantas, garaje y zonas comunes", text: "Placas de portal, numeración de plantas y puertas, directorios y señales de garaje, con la misma imagen que la promoción.", tag: "En la entrega" },
    ],
    solutionsH2: "Partidas de obra nueva",
    solutionsLead: "Cartelería de obra e impresión de gran formato, y señalética de entrega.",
    solutions: [
      { tech: "Durante la obra", title: "Carteles de obra", text: "Impresión de gran formato en nuestro taller y montaje en obra. El contenido obligatorio del cartel lo aporta la promotora; nosotros lo diseñamos, lo producimos y lo colocamos.", specs: ["Diseño, producción y colocación", "Gran formato de taller"], img: "caso-02.jpg", cap: "Cartel de obra", alt: "Cartel de obra de una promoción inmobiliaria" },
      { tech: "En la entrega", title: "Señalética del edificio: portal, plantas, garaje y zonas comunes", text: "Placas de portal, numeración de plantas y puertas, directorios y señales de garaje, con la misma imagen que la promoción.", specs: ["Portal, plantas, garaje y comunes", "Misma imagen que la promoción"], img: "plano-totem.jpg", cap: "Señalética de entrega", alt: "Señalética de portal y plantas en edificio nuevo" },
    ],
    faqH2: "Preguntas frecuentes de obra nueva",
    faqs: [
      { q: "¿El contenido del cartel de obra lo ponéis vosotros?", a: "El contenido obligatorio lo aporta la promotora. Nosotros lo diseñamos, lo producimos y lo colocamos." },
      { q: "¿Hacéis también la señalética del edificio terminado?", a: "Sí. Portal, plantas, garaje y zonas comunes, con la imagen de la promoción." },
    ],
    contactH2: "Envíanos los planos de la promoción",
    contactLead: "Te preparamos la propuesta para la obra y para la entrega.",
    related: [
      { href: "profesionales/", anchor: "cómo trabajamos con constructoras" },
      { href: "servicios/impresion-digital/", anchor: "impresión de gran formato" },
      { href: "servicios/senaletica/", anchor: "señalética" },
    ],
    waMessage: "Hola, os escribo por carteles de obra y señalética de promoción.",
  },
};

export const profesionales = {
  slug: "profesionales",
  path: "profesionales/",
  breadcrumb: "Profesionales",
  title: "Rotulación para estudios, constructoras y rotulistas | Vexil",
  description: "Fabricamos rótulos, fachadas y señalética para arquitectos, constructoras, rotulistas y montadores. También en marca blanca.",
  eyebrow: "Para estudios, constructoras, rotulistas y montadores",
  h1: "Rotulación para estudios, constructoras y rotulistas",
  lead: "Trabajamos con arquitectos, interioristas y constructoras en obra, y con rotulistas y montadores que necesitan producción en marca blanca. Tú llevas al cliente; nosotros te lo fabricamos.",
  pills: [
    { icon: "architecture", title: "Estudios y obra", sub: "Desde planos" },
    { icon: "layers", title: "Marca blanca", sub: "Para rotulistas" },
    { icon: "handyman", title: "Montadores", sub: "Pieza lista para instalar" },
    { icon: "draft", title: "Materiales", sub: "Te ayudamos a elegir" },
  ],
  ctaPrimary: "Envíanos un proyecto",
  ctaSecondary: "Ver para quién trabajamos",
  trust: "Marca blanca para rotulistas. Fabricación para obra.",
  heroImg: "plano-totem.jpg",
  heroAlt: "Proyecto de rotulación y señalética para profesionales del sector",
  whyEyebrow: "Para quién",
  whyH2: "Estudios, obra y rotulistas",
  whyLead: "Un taller para tu proyecto de obra y para producir bajo tu marca. Mira también <a data-rel=\"materiales/\">materiales y acabados</a>, <a data-rel=\"franquicias/\">franquicias</a> y <a data-rel=\"obra-nueva/\">obra nueva</a>.",
  benefits: [
    { icon: "architecture", title: "Estudios de arquitectura", text: "Del plano a la pieza instalada, respetando el diseño.", tag: "Arquitectura" },
    { icon: "chair", title: "Interioristas", text: "Murales, cristales, luz y señalética con el mismo criterio que el resto del espacio. Ver <a data-rel=\"servicios/interiorismo-comercial/\">interiorismo comercial</a>.", tag: "Interiorismo" },
    { icon: "apartment", title: "Constructoras y promotoras", text: "Rótulos, carteles de obra y señalética del edificio. Ver <a data-rel=\"obra-nueva/\">obra nueva</a>.", tag: "Obra" },
    { icon: "hub", title: "Rotulistas y montadores", text: "Te fabricamos en marca blanca: letras, placas, paneles y gráfica listos para que tú montes o entregues a tu cliente.", tag: "Marca blanca" },
  ],
  solutionsH2: "Cómo encajamos en tu trabajo",
  solutionsLead: "Obra para estudios y constructoras, o producción en marca blanca para rotulistas y montadores.",
  solutions: [
    { tech: "Arquitectura", title: "Del plano a la pieza instalada", text: "Leemos alzados, proponemos material y montamos coordinados con la obra.", specs: ["Desde tus planos", "Rótulo y fachada", "Montaje coordinado con la obra"], img: "fachada-hero.jpg", cap: "Proyecto de fachada", alt: "Fachada de proyecto ejecutada por Vexil" },
    { tech: "Interiorismo", title: "Vinilos, murales, luz y señalética", text: "Ejecutamos las partidas gráficas del proyecto de interior.", specs: ["Vinilos, murales, luz y señalética", "Coordinados con la obra"], img: "caso-01.jpg", cap: "Interior", alt: "Partida gráfica de un proyecto de interiorismo" },
    { tech: "Constructora", title: "Rótulos y señalética de la obra", text: "Cartel, placas y orientación del edificio.", specs: ["Durante la obra y en la entrega", "Cartel, placas y orientación"], img: "caso-02.jpg", cap: "Obra", alt: "Rotulación de obra para constructora" },
    { tech: "Marca blanca", title: "Producción para rotulistas y montadores", text: "Te fabricamos letras, placas, paneles e impresión con tu marca o sin la nuestra. Listo para montar o para entregar a tu cliente.", specs: ["Con tu marca o sin la nuestra", "Pieza lista para montar"], img: "hero-taller.jpg", cap: "Marca blanca", alt: "Producción de rótulos en marca blanca en el taller de Vexil" },
    { tech: "Materiales", title: "Materiales y acabados", text: "Te ayudamos a elegir el material. Si tu proyecto pide la ficha del fabricante, te la mandamos.", specs: ["Te ayudamos a elegir", "Fichas de fabricante si las pides"], img: "fachada-01.jpg", cap: "Acabados", alt: "Acabados de rotulación para especificar en proyecto" },
  ],
  faqH2: "Preguntas frecuentes para profesionales",
  faqs: [
    { q: "¿Partís de planos?", a: "Sí. Con planos, alzados o renders revisamos medidas y materiales, y te avisamos si algo hay que ajustar para fabricarlo." },
    { q: "¿Trabajáis con rotulistas y montadores de rótulos?", a: "Sí. Te fabricamos en marca blanca y te entregamos la pieza lista para montar o para tu cliente." },
    { q: "¿Qué es la marca blanca?", a: "Fabricamos nosotros y el cliente final no ve la marca Vexil. Tú mantienes la relación comercial." },
    { q: "¿Podéis hacer solo una parte?", a: "Sí. Rótulo, fachada, vinilos, láminas, señalética o solo fabricación." },
    { q: "¿Quién instala?", a: "En obra podemos instalar nosotros, coordinados con la dirección de obra. Con rotulistas y montadores, lo habitual es entregarte la pieza lista." },
    { q: "¿Tenéis muestrario de materiales?", a: "Sí. En Materiales verás con qué trabajamos. Si necesitas la ficha del fabricante, te la enviamos." },
  ],
  contactH2: "Envíanos tu próximo encargo",
  contactLead: "Planos, archivo de producción o un pedido de marca blanca. Con eso te preparamos una propuesta.",
  related: [
    { href: "servicios/fachadas/", anchor: "fachadas comerciales" },
    { href: "servicios/interiorismo-comercial/", anchor: "interiorismo comercial" },
    { href: "servicios/laminas-solares/", anchor: "láminas solares" },
    { href: "servicios/senaletica/", anchor: "señalética" },
    { href: "servicios/rotulos/", anchor: "letras corpóreas y rótulos" },
    { href: "servicios/corte/", anchor: "corte láser y CNC" },
    { href: "materiales/", anchor: "materiales y acabados" },
    { href: "franquicias/", anchor: "franquicias y cadenas" },
    { href: "obra-nueva/", anchor: "obra nueva" },
  ],
  waMessage: "Hola, os escribo desde un estudio / constructora / rotulista por un proyecto o producción en marca blanca.",
};

export const nosotros = {
  slug: "nosotros",
  path: "nosotros/",
  breadcrumb: "Nosotros",
  title: "Empresa de rotulación en El Campello | Vexil",
  description: "Empresa de rotulación en El Campello: diseño, fabricación e instalación de rótulos, fachadas e interiores en el área de Alicante.",
  eyebrow: "Nosotros",
  h1: "Empresa de rotulación en El Campello",
  lead: "Vexil es una empresa de rotulación con taller propio en El Campello. Diseño, impresión, fabricación e instalación bajo el mismo techo. Puedes pedirnos el proyecto entero o solo una pieza.",
  pills: [
    { icon: "precision_manufacturing", title: "Taller propio", sub: "CNC, láser e impresión" },
    { icon: "support_agent", title: "Te orientamos", sub: "Material, tamaño y luz" },
    { icon: "handyman", title: "Todo o una pieza", sub: "Montamos o entregamos" },
  ],
  ctaPrimary: "Hablar con el taller",
  ctaSecondary: "Ver con qué trabajamos",
  trust: "Diseño, taller e instalación",
  heroImg: "hero-taller.jpg",
  heroAlt: "Taller de rotulación Vexil en El Campello",
  whyEyebrow: "Quiénes somos",
  whyH2: "Cómo trabajamos",
  whyLead: "Miramos el encargo, te proponemos qué tiene sentido y lo fabricamos aquí. El proyecto entero o solo una pieza.",
  benefits: [
    { icon: "precision_manufacturing", title: "Producción en taller", text: "CNC, láser e impresión. Lo que acordamos, te lo fabricamos.", tag: "Taller" },
    { icon: "support_agent", title: "Te orientamos", text: "Material, tamaño y luz según el espacio y el presupuesto.", tag: "Orientación" },
    { icon: "handshake", title: "Hablas con el taller", text: "Quien te atiende es quien fabrica y monta, o quien te deja la pieza lista.", tag: "Equipo" },
  ],
  solutionsH2: "Con qué trabajamos",
  solutionsLead: "Las líneas de taller con las que resolvemos la mayoría de encargos.",
  solutions: [
    { tech: "CNC", title: "Mesa CNC", text: "Corte y fresado de composite, PVC y madera para letras, bandejas y piezas a medida.", specs: ["Composite, PVC y madera", "Letras, bandejas y piezas"], img: "hero-taller.jpg", cap: "CNC de taller", alt: "Fresadora CNC del taller de Vexil" },
    { tech: "Láser", title: "Láser de detalle", text: "Corte y grabado de metacrilato para logos, placas y series cortas.", specs: ["Placas y logos", "Canto limpio o grabado"], img: "plano-totem.jpg", cap: "Láser", alt: "Corte láser de metacrilato en el taller" },
    { tech: "Gran formato", title: "Impresión de gran formato", text: "Vinilos, lonas y gráficos a escala de fachada, vehículo o stand.", specs: ["Vinilo, lona y rígido", "Fachada, flota o evento"], img: "hero-taller.jpg", cap: "Impresión", alt: "Impresora de gran formato en el taller de Vexil" },
    { tech: "LED", title: "Iluminación de rótulo y espacio", text: "Cajas de luz, neón LED y perfiles para el rótulo y el local.", specs: ["Caja de luz, neón LED y perfil", "Nuevo y reparación"], img: "fachada-02.jpg", cap: "LED", alt: "Rótulo con iluminación LED fabricado en taller" },
  ],
  faqH2: "Preguntas frecuentes sobre Vexil",
  faqs: [
    { q: "¿Qué es Vexil?", a: "Una empresa de rotulación en El Campello: diseñamos, fabricamos e instalamos rótulos, fachadas e interiores para negocios del área de Alicante." },
    { q: "¿Solo hacéis proyectos completos?", a: "No. Podemos llevar el proceso entero o solo una partida: fabricación, instalación o un servicio concreto dentro de una obra." },
    { q: "¿Dónde estáis?", a: "Nuestro taller está en Avda. Pla de Messell, 1, Nave D2, El Campello. Trabajamos en Alicante, San Juan, San Vicente, Mutxamel, Jijona, Villajoyosa y Benidorm." },
    { q: "¿Trabajáis con estudios y constructoras?", a: "Sí. También con rotulistas y montadores en marca blanca. En Profesionales explicamos cómo encajamos en cada caso." },
    { q: "¿Cómo se pide presupuesto?", a: "Por el formulario, WhatsApp o 616 048 109. Con fotos, medidas o archivo basta." },
  ],
  contactH2: "Pásate por el taller o escríbenos",
  contactLead: "Escríbenos o llama al 616 048 109. Te proponemos alcance, sistema, materiales y presupuesto.",
  related: [
    { href: "profesionales/", anchor: "estudios, constructoras, rotulistas y montadores" },
    { href: "servicios/rotulos/", anchor: "rótulos para negocios" },
  ],
  waMessage: "Hola, os escribo para conocer el taller y pedir presupuesto.",
};

export const legalPages = {
  "aviso-legal": {
    slug: "aviso-legal",
    path: "aviso-legal/",
    title: "Aviso legal | Vexil",
    h1: "Aviso legal",
    description: "Aviso legal del sitio web de Vexil, empresa de rotulación en El Campello.",
  },
  privacidad: {
    slug: "privacidad",
    path: "privacidad/",
    title: "Política de privacidad | Vexil",
    h1: "Política de privacidad",
    description: "Cómo trata Vexil los datos que nos envías por el formulario, el teléfono o WhatsApp.",
  },
  cookies: {
    slug: "cookies",
    path: "cookies/",
    title: "Política de cookies | Vexil",
    h1: "Política de cookies",
    description: "Información sobre cookies y medición en el sitio web de Vexil.",
  },
};

export const thanksPage = {
  slug: "gracias",
  path: "gracias/",
  title: "Hemos recibido tu mensaje | Vexil",
  h1: "Mensaje enviado",
  description: "Hemos recibido tu solicitud de presupuesto. Te responderemos lo antes posible.",
  lead: "Gracias. Revisamos lo que nos has enviado y te respondemos con una propuesta a medida.",
};

export const homeCatalog = navServices.map((s) => ({ ...s }));
