export const site = {
  name: "Vexil",
  origin: "https://waltersele.github.io/vexil",
  // Web3Forms: si está vacío, el formulario abre WhatsApp con los campos.
  formAccessKey: "",
  // GA4: si está vacío no se carga analítica ni el banner de cookies.
  gaId: "",
};

export const contact = {
  name: "Vexil",
  email: "proyectos@vexil.es",
  phoneDisplay: "616 048 109",
  phoneTel: "+34616048109",
  whatsappNumber: "34616048109",
  addressLocality: "El Campello",
  addressRegion: "Alicante",
  addressCountry: "ES",
  streetAddress: "Avda Pla de Messell, 1, Nave D2",
  postalCode: "03560",
  nif: "48564088W",
  areaServed: ["El Campello", "Alicante", "San Juan", "San Vicente", "Mutxamel", "Jijona", "Villajoyosa", "Benidorm"],
};

export const nextStepText =
  "Cuéntanos qué necesitas con unas fotos y medidas aproximadas. Te proponemos la mejor solución y un presupuesto a medida.";

export const navServices = [
  { slug: "fachadas", name: "Fachadas comerciales", short: "Rótulo y revestimiento", icon: "apartment" },
  { slug: "rotulos", name: "Letras corpóreas y rótulos", short: "Corpóreos, luminosos y neón", icon: "signpost" },
  { slug: "impresion-digital", name: "Impresión digital", short: "Lonas y vinilos", icon: "print" },
  { slug: "vehiculos", name: "Rotulación de vehículos", short: "Furgonetas y coches", icon: "local_shipping" },
  { slug: "interiorismo-comercial", name: "Interiorismo comercial", short: "Ejecución para estudios", icon: "chair" },
  { slug: "laminas-solares", name: "Láminas solares", short: "Control solar y privacidad", icon: "wb_sunny" },
  { slug: "corte", name: "Corte a medida", short: "Láser y CNC", icon: "precision_manufacturing" },
  { slug: "stands", name: "Stands para ferias", short: "Photocalls y gráfica", icon: "view_quilt" },
  { slug: "iluminacion-decorativa", name: "Iluminación decorativa", short: "LED para locales", icon: "light" },
  { slug: "senaletica", name: "Señalética y placas", short: "Metacrilato y orientación", icon: "alt_route" },
];

export const redirects = [
  { from: "servicios/lamina-solar", to: "servicios/laminas-solares/" },
  { from: "servicios/interiores", to: "servicios/interiorismo-comercial/" },
];

export const home = {
  title: "Rótulos y rotulación para negocios en Alicante · Vexil",
  description: "Letras corpóreas, rótulos luminosos, fachadas y vinilos para negocios en Alicante. Lo diseñamos, lo fabricamos en nuestro taller y lo montamos.",
  eyebrow: "Empresa de rotulación en Alicante",
  h1: "Rótulos para negocios que se ven desde la calle",
  lead: "Letras corpóreas, rótulos luminosos, fachadas, vinilos y señalética. Te asesoramos, lo fabricamos en nuestro taller de El Campello y lo dejamos montado.",
  ctaPrimary: "Pedir presupuesto",
  ctaSecondary: "Ver servicios",
  trust: "Diseño · Fabricación propia · Montaje",
  heroImg: "hero-taller.jpg",
  heroAlt: "Taller de Vexil en El Campello: fabricación de rótulos y rotulación",
  servicesEyebrow: "Qué hacemos",
  servicesH2: "Del rótulo de la puerta a la fachada completa",
  servicesLead:
    "Empieza por una pieza o confíanos el proyecto entero. Nosotros nos encargamos de que todo encaje: materiales, luz y montaje. También hacemos <a href=\"servicios/rotulos/\">letras corpóreas y rótulos luminosos</a>, <a href=\"servicios/fachadas/\">rotulación de fachadas</a>, <a href=\"servicios/laminas-solares/\">láminas de control solar</a> y <a href=\"servicios/interiorismo-comercial/\">proyectos de interiorismo comercial</a>.",
  whyEyebrow: "Confianza",
  whyH2: "Un solo equipo, de la idea al montaje",
  whyLead: "Hablas siempre con las mismas personas: quien te asesora es quien fabrica y quien monta. Sin intermediarios ni sorpresas por el camino.",
  whyImg: "plano-totem.jpg",
  whyImgAlt: "Plano de tótem y señalética preparado en el taller de Vexil",
  benefits: [
    { icon: "precision_manufacturing", title: "Hecho en nuestro taller", text: "Diseñamos, cortamos, imprimimos y montamos nosotros." },
    { icon: "verified", title: "Pensado para durar", text: "Elegimos cada material según el sol, la humedad y el uso que va a tener." },
    { icon: "support_agent", title: "Asesoramiento", text: "Te orientamos en material, tamaño e iluminación según tu local." },
    { icon: "handyman", title: "Montaje propio", text: "Lo instalamos nosotros y acordamos contigo el mejor momento para no frenar tu negocio." },
  ],
  contactEyebrow: "Presupuesto sin compromiso",
  contactH2: "Cuéntanos qué quieres rotular",
  contactLead: "Mándanos una foto del local, tu logotipo o un boceto. Te respondemos con una propuesta y un precio a medida.",
  faqH2: "Preguntas frecuentes",
  faqs: [
    { q: "¿Qué servicios de rotulación ofrece Vexil?", a: "Diseñamos, fabricamos y montamos rótulos, fachadas comerciales, vinilos, impresión digital, señalética, stands e iluminación decorativa. También cortamos y grabamos piezas a medida con CNC y láser." },
    { q: "¿En qué zonas trabajáis?", a: "Nuestra base está en El Campello y trabajamos en Alicante, San Juan, San Vicente, El Campello, Mutxamel, Jijona, Villajoyosa y Benidorm. Si tu proyecto está fuera de esta zona, cuéntanoslo y lo estudiamos." },
    { q: "¿Cómo puedo pedir presupuesto?", a: "Escríbenos por WhatsApp o por el formulario con lo que necesitas: qué quieres rotular, dónde y, si puedes, unas fotos y medidas aproximadas. Con eso te preparamos una propuesta." },
    { q: "¿Hacéis también el diseño del rótulo o solo la fabricación?", a: "Hacemos las dos cosas. Puedes traernos tu logotipo y diseño listos para producción, o diseñamos el rótulo contigo antes de fabricarlo y montarlo." },
    { q: "¿Cuánto cuesta un rótulo para un negocio?", a: "Depende del tipo, el tamaño, los materiales, si lleva luz y si incluye montaje. Por eso cada presupuesto es a medida: envíanos fotos y medidas aproximadas y te lo preparamos sin compromiso." },
    { q: "¿Trabajáis con particulares o solo con empresas?", a: "Con ambos. Rotulamos negocios y también hacemos trabajos para particulares, desde un vinilo decorativo hasta un rótulo que quieras instalar tú." },
  ],
  related: [
    { href: "servicios/rotulos/", anchor: "letras corpóreas y rótulos luminosos" },
    { href: "servicios/fachadas/", anchor: "rotulación de fachadas" },
    { href: "servicios/laminas-solares/", anchor: "láminas de control solar" },
    { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiorismo comercial" },
    { href: "profesionales/", anchor: "trabajamos con estudios y constructoras" },
  ],
  waMessage: "Hola, os escribo para pedir presupuesto de rotulación.",
};

export const services = {
  fachadas: {
    slug: "fachadas",
    breadcrumb: "Fachadas comerciales",
    title: "Rotulación de fachadas y revestimiento de composite | Vexil Alicante",
    description: "Renovamos la fachada de tu local: revestimiento de composite, letras corpóreas, iluminación y vinilos. Un solo equipo del diseño al montaje.",
    eyebrow: "Rotulación de fachadas",
    h1: "Rotulación de fachadas comerciales: rótulo y revestimiento en un solo proyecto",
    lead: "Renovamos la fachada de tu negocio de principio a fin: revestimiento de composite, letras corpóreas, iluminación y vinilos en el escaparate. Un solo equipo y un solo presupuesto.",
    pills: [
      { icon: "storefront", title: "Proyecto completo", sub: "Rótulo y revestimiento" },
      { icon: "layers", title: "Composite", sub: "Aluminio a medida" },
      { icon: "light", title: "Iluminación", sub: "Si el local lo pide" },
      { icon: "handyman", title: "Montaje propio", sub: "Acordamos el momento" },
    ],
    ctaPrimary: "Pedir presupuesto de fachada",
    ctaSecondary: "Ver qué podemos hacer",
    trust: "Diseño, fabricación y montaje de fachadas comerciales. Taller en El Campello.",
    heroImg: "fachada-hero.jpg",
    heroAlt: "Fachada comercial rotulada por Vexil con revestimiento y letras corpóreas",
    whyEyebrow: "Beneficios",
    whyH2: "Qué gana tu negocio con una fachada nueva",
    whyLead: "La fachada es lo primero que ve quien pasa por tu calle. La diseñamos como un conjunto.",
    benefits: [
      { icon: "visibility", title: "Se te ve antes", text: "Una fachada clara y bien iluminada destaca en la calle.", tag: "Visibilidad" },
      { icon: "verified", title: "Transmite confianza", text: "El cliente juzga el negocio antes de entrar.", tag: "Imagen" },
      { icon: "layers", title: "Tapa lo que no quieres que se vea", text: "Cajas de persiana, cableado o paredes castigadas.", tag: "Acabado limpio" },
      { icon: "architecture", title: "Todo encaja", text: "Rótulo, revestimiento y escaparate se diseñan juntos.", tag: "Un solo criterio" },
    ],
    solutionsH2: "Qué podemos hacer en tu fachada",
    solutionsLead: "Combinamos revestimiento, letras y vinilos según el local. También <a data-rel=\"servicios/rotulos/\">letras corpóreas</a>, <a data-rel=\"servicios/laminas-solares/\">láminas solares en escaparates y cristaleras</a> y <a data-rel=\"servicios/impresion-digital/\">vinilos de escaparate</a>.",
    solutions: [
      { tech: "Composite de aluminio", title: "Revestimiento en panel composite", text: "Bandejas a medida para renovar el frente del local y ocultar lo que no quieres que se vea.", a: "Acabados", av: "Mate, brillo o metalizado", b: "Uso", bv: "Fachadas de local y nave", img: "fachada-01.jpg", cap: "Revestimiento de composite", alt: "Revestimiento de fachada en composite de aluminio" },
      { tech: "Letras e iluminación", title: "Rótulo integrado en la fachada", text: "Letras corpóreas y cajas de luz pensadas con el revestimiento, no como una pieza suelta.", a: "Opciones", av: "Con luz o sin luz", b: "Enlace", bv: "Letras corpóreas", img: "fachada-02.jpg", cap: "Rótulo y fachada juntos", alt: "Rótulo luminoso integrado en una fachada comercial" },
      { tech: "Relieve", title: "Letras corpóreas sobre el frente", text: "Corte en el taller y montaje sobre composite, ladrillo o panel.", a: "Materiales", av: "Aluminio, PVC o metacrilato", b: "Luz", bv: "Frontal, halo o sin luz", img: "fachada-03.jpg", cap: "Letras en relieve", alt: "Letras corpóreas en relieve sobre fachada" },
      { tech: "Cristalera", title: "Vinilos de escaparate y cristaleras", text: "Microperforado, efecto arenado y vinilo de corte para lunas y accesos.", a: "Función", av: "Marca y privacidad", b: "Colocación", bv: "Si quieres, también la hacemos", img: "fachada-04.jpg", cap: "Vinilo en cristalera", alt: "Vinilo de escaparate en la cristalera de un local" },
    ],
    faqH2: "Preguntas frecuentes sobre la renovación de fachadas",
    faqs: [
      { q: "¿Qué incluye la rotulación de una fachada comercial?", a: "Puede incluir el rótulo principal, banderolas, rotulación de escaparates y puerta, revestimientos de fachada y la iluminación. Lo diseñamos como un conjunto para que el local tenga una imagen coherente y se vea bien de día y de noche." },
      { q: "¿Podéis hacerlo todo, del diseño al montaje?", a: "Sí. Nos ocupamos del diseño, la fabricación y el montaje, para que no tengas que coordinar a varios proveedores." },
      { q: "¿Puedo combinar varios materiales en la fachada?", a: "Sí. Es habitual combinar, por ejemplo, letras corpóreas, paneles composite, vinilo en cristales e iluminación. Te proponemos la combinación que mejor encaje con tu marca y tu presupuesto." },
      { q: "¿Qué necesito para que me hagáis un presupuesto?", a: "Fotos de la fachada actual con el entorno, medidas aproximadas y tu logotipo. Si nos cuentas qué quieres cambiar, te decimos si hace falta visita para tomar medidas." },
    ],
    contactH2: "¿Quieres saber cómo quedaría la fachada de tu negocio?",
    contactLead: "Envíanos una foto del frontal y tu logotipo. Te preparamos una propuesta y un presupuesto a medida.",
    related: [
      { href: "servicios/rotulos/", anchor: "letras corpóreas" },
      { href: "servicios/laminas-solares/", anchor: "láminas solares en escaparates y cristaleras" },
      { href: "servicios/impresion-digital/", anchor: "vinilos de escaparate" },
      { href: "profesionales/", anchor: "proyectos de obra" },
      { href: "franquicias/", anchor: "rotulación para franquicias" },
    ],
    waMessage: "Hola, os escribo por rotulación de fachadas.",
  },

  rotulos: {
    slug: "rotulos",
    variant: "types",
    breadcrumb: "Letras corpóreas y rótulos",
    title: "Letras corpóreas y rótulos luminosos para negocios | Vexil Alicante",
    description: "Letras corpóreas, rótulos luminosos y neón LED a medida para tu negocio. Los fabricamos en nuestro taller, los montamos y reparamos los que ya tienes.",
    eyebrow: "Rótulos a medida",
    h1: "Rótulos para negocios: letras corpóreas, luminosos y neón LED",
    lead: "El rótulo es lo primero que ve tu cliente. Te ayudamos a elegir el que mejor funciona en tu fachada, lo fabricamos en nuestro taller y lo montamos. Y si el que tienes ha dejado de lucir, también lo reparamos.",
    pills: [
      { icon: "signpost", title: "A medida", sub: "Según tu fachada" },
      { icon: "light", title: "Con o sin luz", sub: "Luminosos y neón LED" },
      { icon: "build", title: "Mantenimiento", sub: "También reparamos" },
      { icon: "handyman", title: "Montaje propio", sub: "En tu local" },
    ],
    ctaPrimary: "Pedir presupuesto de rótulos",
    ctaSecondary: "Ver tipos de rótulo",
    trust: "Diseño, fabricación, instalación y reparación de rótulos.",
    heroImg: "fachada-03.jpg",
    heroAlt: "Letras corpóreas fabricadas en el taller de Vexil",
    whyEyebrow: "El rótulo correcto",
    whyH2: "Cada fachada pide un rótulo distinto",
    whyLead: "Elegimos tipo, tamaño y luz según desde dónde te van a ver. Si también renovamos el frente, mira <a data-rel=\"servicios/fachadas/\">rótulo y revestimiento de fachada</a>.",
    benefits: [
      { icon: "hub", title: "Un solo taller", text: "Corpóreas, neón, luminosos y vinilo salen del mismo equipo.", tag: "Fabricación propia" },
      { icon: "visibility", title: "Se lee de día y de noche", text: "Elegimos tamaño, contraste y luz pensando en desde dónde te van a ver.", tag: "Visibilidad" },
      { icon: "architecture", title: "Integrado en tu local", text: "Lo fijamos al soporte que tengas: fachada, panel o cristal.", tag: "Montaje" },
      { icon: "savings", title: "Sin intermediarios", text: "Hablas con quien lo fabrica y quien lo monta.", tag: "Un interlocutor" },
    ],
    typesH2Intro: "Tipos de rótulo",
    typesLead: "Elige por cómo se ve de día, si necesita luz y dónde se fija.",
    types: [
      {
        id: "corporeos",
        h2: "Letras corpóreas",
        kicker: "Relieve 3D",
        text: "Letras y logos en volumen, recortados uno a uno, que se colocan sobre la fachada o sobre un panel. Con o sin iluminación.",
        specs: ["PVC, metacrilato, aluminio o composite", "Con luz o sin luz", "Sobre fachada o sobre panel"],
        img: "fachada-03.jpg",
        alt: "Letras corpóreas en relieve para fachada de negocio",
        faqs: [
          { q: "¿Qué son las letras corpóreas?", a: "Son letras y logos en volumen, cortados a medida y fijados a la fachada o a un panel. Dan relieve y se leen bien de cerca y de lejos." },
          { q: "¿Pueden llevar luz?", a: "Sí. Pueden ir sin luz, con luz frontal o con halo. Te proponemos la opción que mejor se lea en tu calle." },
        ],
      },
      {
        id: "luminosos",
        h2: "Rótulos y carteles luminosos",
        kicker: "Cajas de luz LED",
        text: "Rótulos luminosos con iluminación LED: cajones con cara iluminada, banderolas y letras iluminadas. Te decimos cuál encaja según tu fachada y tu presupuesto.",
        specs: ["Cajones, banderolas y letras iluminadas", "Iluminación LED", "Según fachada y presupuesto"],
        img: "fachada-02.jpg",
        alt: "Rótulo luminoso LED en fachada comercial",
        faqs: [
          { q: "¿Qué tipos de rótulo luminoso hacéis?", a: "Cajones de luz, banderolas y letras iluminadas. Elegimos el sistema según el tamaño de la fachada y cómo quieres que se vea de noche." },
          { q: "¿Consumen mucho?", a: "Usamos iluminación LED. En el presupuesto te indicamos el sistema concreto para tu pieza." },
        ],
      },
      {
        id: "neon",
        h2: "Rótulos neón LED",
        kicker: "Neón LED flexible",
        text: "Neón LED flexible a medida con tu logotipo, una frase o un dibujo sencillo. Cuanto más simple es el trazo, mejor se ve el resultado.",
        specs: ["Neón LED flexible", "Logotipo, frase o dibujo", "Interior o exterior, según modelo"],
        img: "fachada-02.jpg",
        alt: "Rótulo de neón LED con logotipo",
        faqs: [
          { q: "¿Hacéis neón con el logo de mi negocio?", a: "Sí. Recortamos el trazo de tu logotipo o de una frase. Los trazos simples se leen mejor." },
          { q: "¿Vale para interior y exterior?", a: "Según el modelo. Te decimos cuál encaja en tu local." },
        ],
      },
      {
        id: "sin-iluminacion",
        h2: "Rótulos sin iluminación",
        kicker: "Corte y vinilo",
        text: "La opción más sencilla cuando el local abre sobre todo de día o no quieres instalación eléctrica. Composite, PVC, aluminio, metacrilato o vinilo sobre soporte rígido.",
        specs: ["Composite, PVC, aluminio, metacrilato o vinilo", "Sin instalación eléctrica", "Imagen cuidada y duradera"],
        img: "fachada-04.jpg",
        alt: "Rótulo sin iluminación en composite y vinilo",
        faqs: [
          { q: "¿Cuándo conviene un rótulo sin luz?", a: "Cuando el local abre de día, cuando no quieres obra eléctrica o cuando el presupuesto pide una pieza clara y bien cortada." },
        ],
      },
      {
        id: "mantenimiento",
        h2: "Mantenimiento y reparación",
        kicker: "Rótulos existentes",
        text: "Revisamos y reparamos rótulos, los hayamos instalado nosotros o no. LED, transformadores, piezas sueltas, cableado y desgaste por sol o humedad.",
        specs: ["Revisión y reparación", "También si no es nuestro", "Fotos y descripción de la avería"],
        img: "hero-taller.jpg",
        alt: "Reparación de rótulos en el taller de Vexil",
        faqs: [
          { q: "¿Reparáis rótulos que no habéis fabricado vosotros?", a: "Sí. Con fotos y una descripción de la avería te decimos qué se puede hacer." },
        ],
      },
    ],
    faqH2: "Preguntas frecuentes de rótulos",
    faqs: [
      { q: "¿Qué tipo de rótulo me conviene?", a: "Depende de la fachada, de si abres de noche y de cómo quieres que se lea tu marca. Te proponemos letras corpóreas, un luminoso, neón LED o una pieza sin luz." },
      { q: "¿También hacéis el montaje?", a: "Sí. Lo fabricamos y lo instalamos. Si solo quieres la pieza, también." },
      { q: "¿Podéis cortar las letras en el taller?", a: "Sí. El <a data-rel=\"servicios/corte/\">corte láser y CNC</a> es el mismo con el que fabricamos letras y placas." },
    ],
    contactH2: "¿Quieres un rótulo que se lea desde la calle?",
    contactLead: "Envía fotos de la fachada y tu logotipo. Te proponemos el tipo de rótulo y un presupuesto a medida.",
    related: [
      { href: "servicios/fachadas/", anchor: "rótulo y revestimiento de fachada" },
      { href: "servicios/iluminacion-decorativa/", anchor: "iluminación decorativa del local" },
      { href: "servicios/corte/", anchor: "corte láser y CNC" },
      { href: "franquicias/", anchor: "rotulación para franquicias" },
    ],
    waMessage: "Hola, os escribo por letras corpóreas y rótulos.",
  },

  "impresion-digital": {
    slug: "impresion-digital",
    breadcrumb: "Impresión digital",
    title: "Impresión de gran formato y lonas publicitarias | Vexil Alicante",
    description: "Lonas publicitarias, vinilos adhesivos, microperforado y paneles rígidos impresos en nuestro taller. Elegimos el material según dónde va y lo colocamos.",
    eyebrow: "Gran formato de taller",
    h1: "Impresión de gran formato: lonas publicitarias, vinilos y carteles",
    lead: "Imprimimos en nuestro taller lonas, vinilos adhesivos, microperforado y paneles rígidos. Elegimos el material según dónde va a ir y, si quieres, también lo colocamos.",
    pills: [
      { icon: "print", title: "Taller propio", sub: "Imprimimos aquí" },
      { icon: "wb_sunny", title: "Interior y exterior", sub: "Según el material" },
      { icon: "layers", title: "Vinilos y lonas", sub: "A la medida" },
      { icon: "handyman", title: "Colocación", sub: "Si la necesitas" },
    ],
    ctaPrimary: "Pedir presupuesto de impresión",
    ctaSecondary: "Ver materiales",
    trust: "Impresión de gran formato en El Campello. Colocación si la pides.",
    heroImg: "fachada-04.jpg",
    heroAlt: "Impresión de gran formato y vinilos en el taller de Vexil",
    whyEyebrow: "Material correcto",
    whyH2: "Imprimir bien es elegir bien el material",
    whyLead: "No es lo mismo un vinilo de escaparate que una lona de valla o un mural de pared. Si el trabajo forma parte de un <a data-rel=\"servicios/interiorismo-comercial/\">proyecto de interiorismo</a>, de <a data-rel=\"servicios/stands/\">gráfica para stands</a> o de <a data-rel=\"servicios/vehiculos/\">vinilos para coche y furgoneta</a>, lo encajamos.",
    benefits: [
      { icon: "palette", title: "Color de marca", text: "Cuidamos que el color de tu marca salga como debe.", tag: "Color" },
      { icon: "wb_sunny", title: "Según dónde va", text: "Elegimos vinilo, lona o rígido según sol, humedad y uso.", tag: "Material" },
      { icon: "photo_size_select_large", title: "Gran formato", text: "Lonas, testeros, escaparates y paneles a la medida que necesitas.", tag: "Escala" },
      { icon: "handyman", title: "Colocación profesional", text: "El mismo equipo puede aplicar el vinilo o la lona en el local.", tag: "Montaje" },
    ],
    solutionsH2: "Qué imprimimos",
    solutionsLead: "Lonas, vinilos, microperforado y rígidos. También vinilos decorativos a medida.",
    solutions: [
      { tech: "Vinilo adhesivo", title: "Vinilos adhesivos de interior y exterior", text: "Corte, fondos impresos y laminados mate o brillo según el uso.", a: "Uso", av: "Paredes, composite, aluminio", b: "Acabado", bv: "Mate o brillo", img: "fachada-04.jpg", cap: "Vinilo adhesivo", alt: "Vinilo adhesivo impreso para pared y escaparate" },
      { tech: "Lona", title: "Lonas publicitarias", text: "Gran formato con ollados y refuerzos para fachadas y vallas. También backlight para cajas de luz.", a: "Acabado", av: "Ollados y soldadura", b: "Formato", bv: "Fachadas y eventos", img: "fachada-02.jpg", cap: "Lona de gran formato", alt: "Lona publicitaria de gran formato" },
      { tech: "Microperforado", title: "Vinilo de luna y microperforado", text: "Se ve desde dentro hacia la calle, con gráfica por fuera. Para escaparates y lunas.", a: "Visión", av: "Desde dentro hacia fuera", b: "Uso", bv: "Escaparates y lunas", img: "fachada-01.jpg", cap: "Microperforado", alt: "Vinilo microperforado en luna o escaparate" },
      { tech: "Rígido", title: "Paneles rígidos y carteles", text: "Foam, composite y canvas cortados a medida, listos para colgar o instalar.", a: "Base", av: "Foam, composite, canvas", b: "Acabado", bv: "Corte a medida", img: "caso-01.jpg", cap: "Panel rígido", alt: "Panel rígido impreso para interior" },
      { tech: "Pared", title: "Vinilos decorativos y murales impresos a medida", text: "Imprimimos vinilos decorativos y murales a la medida de tu pared, para negocios y viviendas. Elegimos el vinilo según la superficie y, si quieres, también lo colocamos.", a: "A medida", av: "Según tu pared", b: "Colocación", bv: "Opcional", img: "caso-01.jpg", cap: "Mural a medida", alt: "Mural de vinilo decorativo impreso a medida" },
    ],
    faqH2: "Preguntas frecuentes de impresión digital",
    faqs: [
      { q: "¿Qué puedo imprimir?", a: "Adhesivos y pegatinas, vinilos para escaparates y paredes, cartelería y otros soportes de gran formato. Si tienes una idea que no encaja en esta lista, pregúntanos." },
      { q: "¿Qué tipos de vinilo utilizáis?", a: "Trabajamos varios: monomérico (una opción económica para uso promocional y de corta o media duración), polimérico (pensado para larga duración), transparente y de alta adherencia para superficies difíciles. Te recomendamos el más adecuado según dónde vaya a ir colocado." },
      { q: "¿Los adhesivos se pueden laminar?", a: "Sí. El laminado protege la impresión y alarga su vida, y se ofrece en acabado brillo o mate." },
      { q: "¿Puedo pedir adhesivos con la forma de mi diseño?", a: "Sí, se pueden cortar por la silueta del dibujo, además de con formas sencillas como recta, redondeada, circular u ovalada." },
      { q: "¿Hay un pedido mínimo?", a: "En adhesivos, el pedido mínimo es de 1 m². Cuantos más metros pides, mayor es el descuento por volumen." },
      { q: "¿Los precios incluyen IVA?", a: "Nuestras tarifas se indican sin IVA; a ellas se aplica el 21 % de IVA." },
      { q: "¿Se puede quitar el vinilo sin dañar la pared?", a: "Depende de la superficie y del vinilo utilizado. Sobre paredes pintadas en buen estado suele poder retirarse, pero no podemos asegurarlo en todos los casos, así que lo valoramos contigo antes de empezar." },
      { q: "¿Servís para decorar una vivienda?", a: "Sí. Imprimimos vinilos decorativos y murales a medida también para particulares. Si es un <a data-rel=\"servicios/interiorismo-comercial/\">proyecto de interiorismo</a> de un estudio, mira cómo trabajamos con planos." },
      { q: "¿Qué archivo tengo que enviaros?", a: "Lo ideal es un PDF o un archivo vectorial (AI o SVG) con los textos convertidos a curvas. Si solo tienes una imagen, cuéntanoslo y te decimos si tiene calidad suficiente para el tamaño que necesitas." },
    ],
    contactH2: "¿Tienes un arte o una medida y quieres precio?",
    contactLead: "Envía el archivo o las medidas aproximadas. Te preparamos un presupuesto a medida.",
    related: [
      { href: "servicios/interiorismo-comercial/", anchor: "proyecto de interiorismo" },
      { href: "servicios/stands/", anchor: "gráfica para stands" },
      { href: "servicios/vehiculos/", anchor: "vinilos para coche y furgoneta" },
      { href: "obra-nueva/", anchor: "carteles de obra" },
    ],
    waMessage: "Hola, os escribo por lonas e impresión de gran formato.",
  },

  vehiculos: {
    slug: "vehiculos",
    breadcrumb: "Rotulación de vehículos",
    title: "Rotulación de furgonetas y vinilos para coche | Vexil Alicante",
    description: "Rotulación de furgonetas y coches: logo, teléfono, web, franjas y textos en vinilo fundido. Diseñamos contigo y lo colocamos en nuestro taller.",
    eyebrow: "Rotulación de furgonetas y coches",
    h1: "Rotulación de furgonetas: logo, teléfono y web en vinilo",
    lead: "Rotulamos furgonetas de empresa y personalizamos coches: logo, teléfono, web, franjas y textos en puertas, laterales, capó o luneta. Usamos vinilo fundido, que se adapta a las curvas de la carrocería. No hacemos forrado completo ni cambio de color.",
    pills: [
      { icon: "local_shipping", title: "Furgonetas", sub: "Logo, teléfono y web" },
      { icon: "directions_car", title: "Coches", sub: "Franjas y detalles" },
      { icon: "verified", title: "Vinilo fundido", sub: "Se adapta a la carrocería" },
      { icon: "design_services", title: "Tu diseño o el nuestro", sub: "Lo revisamos contigo" },
    ],
    ctaPrimary: "Pedir presupuesto de vehículo",
    ctaSecondary: "Ver qué rotulamos",
    trust: "Vinilo fundido para flotas y particulares. Colocación en taller.",
    heroImg: "hero-taller.jpg",
    heroAlt: "Rotulación de furgoneta con vinilo fundido en el taller de Vexil",
    whyEyebrow: "Personalización y flota",
    whyH2: "Tu furgoneta también es un rótulo",
    whyLead: "Cuéntanos el modelo y qué datos quieres que se lean. El <a data-rel=\"servicios/impresion-digital/\">vinilo impreso</a> sale del mismo taller.",
    benefits: [
      { icon: "brush", title: "Tu idea o la nuestra", text: "Puedes traer tu diseño o lo creamos contigo. Lo ideal es un archivo vectorial o una imagen nítida.", tag: "Diseño" },
      { icon: "layers", title: "Vinilo fundido", text: "Se adapta a las formas del vehículo. La duración depende del sol y del cuidado.", tag: "Material" },
      { icon: "format_paint", title: "Retirada cuidadosa", text: "Si la pintura está en buen estado y el vinilo se retira bien, no debería dañarse. Lo revisamos antes.", tag: "Pintura" },
      { icon: "local_car_wash", title: "Cómo mantenerlo", text: "Evita el agua a presión muy cerca de los bordes y usa productos neutros.", tag: "Cuidado" },
    ],
    solutionsH2: "Qué rotulamos en el vehículo",
    solutionsLead: "Flotas de empresa y personalización por zonas. No cubrimos el vehículo entero ni cambiamos el color.",
    solutions: [
      { tech: "Flota", title: "Furgoneta de empresa", text: "Logo, teléfono, web y textos en laterales y puertas, para que se lean en ciudad.", a: "Datos", av: "Marca y contacto", b: "Material", bv: "Vinilo fundido", img: "caso-02.jpg", cap: "Furgoneta de empresa", alt: "Furgoneta rotulada con logo y datos de contacto" },
      { tech: "Corte o impresión", title: "Logotipos y textos", text: "Nombre, teléfono, web o el dibujo que quieras, en puertas, laterales o luna.", a: "Archivo", av: "Vector o imagen nítida", b: "Colocación", bv: "Donde mejor se lea", img: "hero-taller.jpg", cap: "Logo y textos", alt: "Logotipo en vinilo sobre puerta de vehículo" },
      { tech: "Detalle", title: "Franjas y acentos", text: "Líneas, formas y acentos en laterales, capó o zócalo, recortados a medida.", a: "Uso", av: "Turismos y furgones", b: "Material", bv: "Vinilo fundido", img: "caso-01.jpg", cap: "Franjas a medida", alt: "Franjas de vinilo en el lateral de un coche" },
      { tech: "Luna", title: "Detalles en luneta", text: "Textos o gráficos en la luna cuando el diseño y la visibilidad lo permiten.", a: "Visibilidad", av: "La valoramos antes", b: "Diseño", bv: "A medida", img: "fachada-04.jpg", cap: "Luneta", alt: "Texto en vinilo sobre luneta de vehículo" },
    ],
    faqH2: "Preguntas frecuentes de rotulación de vehículos",
    faqs: [
      { q: "¿Rotuláis furgonetas de empresa?", a: "Sí. Logo, teléfono, web y textos en laterales y puertas. Cuéntanos el modelo y qué datos quieres que se vean." },
      { q: "¿Hacéis forrado completo o cambio de color?", a: "No. Nos centramos en personalización y rotulación parcial: franjas, logos y textos." },
      { q: "¿Qué vinilo utilizáis?", a: "Vinilo fundido, pensado para adaptarse a las formas del vehículo. Su duración depende de la exposición al sol y de cómo lo cuides." },
      { q: "¿Puedo llevar mi propio diseño?", a: "Sí. Puedes traer tu diseño o lo creamos contigo." },
      { q: "¿Se estropea la pintura al quitar el vinilo?", a: "Si la pintura está en buen estado y el vinilo se retira correctamente, no debería dañarse. Si hay repintados o golpes, lo revisamos antes." },
    ],
    contactH2: "¿Quieres rotular tu furgoneta o tu coche?",
    contactLead: "Envía modelo, fotos y la idea o el archivo. Te preparamos un presupuesto a medida.",
    related: [{ href: "servicios/impresion-digital/", anchor: "impresión de vinilo" }],
    waMessage: "Hola, os escribo por rotulación de furgonetas.",
  },

  "interiorismo-comercial": {
    slug: "interiorismo-comercial",
    breadcrumb: "Interiorismo comercial",
    title: "Interiorismo comercial: ejecución de proyectos para estudios | Vexil Alicante",
    description: "Ejecutamos proyectos de interiorismo comercial: murales, vinilo al ácido, letras corpóreas, señalética e iluminación según los planos de tu estudio.",
    eyebrow: "Para estudios y constructoras",
    h1: "Decoración de interiores comerciales: ejecutamos lo que tu estudio ha proyectado",
    lead: "Trabajamos para estudios de interiorismo, arquitectos y constructoras. Partimos de tus planos y del manual de marca del cliente, y fabricamos e instalamos todo lo gráfico del proyecto: murales, cristales, letras corpóreas, señalética e iluminación decorativa.",
    pills: [
      { icon: "architecture", title: "Desde planos", sub: "Alzados y renders" },
      { icon: "layers", title: "Partidas gráficas", sub: "Las que necesites" },
      { icon: "chair", title: "Interior", sub: "Oficinas, retail, clínicas" },
      { icon: "handyman", title: "Instalamos", sub: "Coordinados con la obra" },
    ],
    ctaPrimary: "Enviar un proyecto",
    ctaSecondary: "Ver qué ejecutamos",
    trust: "Ejecución gráfica para estudios. Taller en El Campello.",
    heroImg: "caso-01.jpg",
    heroAlt: "Interior comercial con mural y lettering ejecutado por Vexil",
    whyEyebrow: "Cómo trabajamos",
    whyH2: "Del plano a la pieza instalada",
    whyLead: "Nos pasas planos, alzados o renders. Revisamos contigo materiales y medidas, lo fabricamos en nuestro taller y lo instalamos coordinados con la obra. Un solo interlocutor para todas las partidas gráficas. Mira también <a data-rel=\"profesionales/\">cómo trabajamos con estudios</a>.",
    benefits: [
      { icon: "print", title: "Murales y revestimientos gráficos", text: "Impresión a medida del alzado, en vinilo o papel mural, colocada por nosotros.", tag: "Murales" },
      { icon: "window", title: "Vinilo al ácido", text: "Bandas, tramas, logotipos y privacidad en salas de reuniones, despachos y consultas.", tag: "Cristal" },
      { icon: "signpost", title: "Letras y logos corpóreos de interior", text: "Recepciones y paredes de marca, con o sin luz, cortados en nuestro taller.", tag: "Relieve" },
      { icon: "alt_route", title: "Señalética e iluminación del proyecto", text: "Placas, directorios y luz decorativa con el mismo criterio que el resto del espacio.", tag: "Conjunto" },
    ],
    solutionsH2: "Qué ejecutamos en un proyecto de interiores",
    solutionsLead: "Todas las partidas gráficas o solo las que necesites. También <a data-rel=\"servicios/laminas-solares/\">láminas de control solar</a>, <a data-rel=\"servicios/senaletica/\">señalética del proyecto</a>, <a data-rel=\"servicios/iluminacion-decorativa/\">iluminación decorativa</a> y <a data-rel=\"servicios/rotulos/\">letras corpóreas de interior</a>.",
    solutions: [
      { tech: "Gran formato", title: "Murales y revestimientos gráficos", text: "Impresión a medida del alzado, en vinilo o papel mural, colocada por nosotros.", a: "Partida", av: "Paredes y alzados", b: "Colocación", bv: "Nuestra", img: "caso-01.jpg", cap: "Mural de proyecto", alt: "Mural gráfico de interior colocado a medida" },
      { tech: "Cristal", title: "Vinilo al ácido para mamparas y cristaleras", text: "Bandas, tramas, logotipos y privacidad en salas de reuniones, despachos y consultas.", a: "Uso", av: "Mamparas y cristaleras", b: "Acabado", bv: "Efecto arenado", img: "fachada-04.jpg", cap: "Vinilo al ácido", alt: "Vinilo al ácido en mampara de oficina" },
      { tech: "Relieve", title: "Letras y logos corpóreos de interior", text: "Recepciones y paredes de marca, con o sin luz, cortados en nuestro taller.", a: "Material", av: "PVC, metacrilato, composite", b: "Luz", bv: "Opcional", img: "fachada-03.jpg", cap: "Logo de recepción", alt: "Letras corpóreas de interior en recepción" },
      { tech: "Conjunto", title: "Señalética e iluminación del proyecto", text: "Placas, directorios y luz decorativa con el mismo criterio que el resto del espacio.", a: "Criterio", av: "El del proyecto", b: "Obra", bv: "Coordinados", img: "plano-totem.jpg", cap: "Señalética de interior", alt: "Placas y directorio de interiorismo comercial" },
    ],
    spacesH2: "Oficinas, retail, clínicas, hostelería y hoteles",
    spaces: [
      { title: "Oficinas", img: "caso-04.jpg", alt: "Oficina con gráfica de marca y vinilo en cristalera" },
      { title: "Retail", img: "caso-01.jpg", alt: "Tienda con mural y lettering de interior" },
      { title: "Clínicas", img: "caso-03.jpg", alt: "Recepción de clínica con vinilo y logo" },
      { title: "Hostelería", img: "fachada-hero.jpg", alt: "Interior de hostelería con gráfica de marca" },
    ],
    faqH2: "Preguntas frecuentes de interiorismo comercial",
    faqs: [
      { q: "¿Trabajáis a partir de planos o renders?", a: "Sí. Con planos, alzados o renders revisamos medidas y materiales, y te avisamos si algo necesita ajustarse para fabricarlo." },
      { q: "¿Podéis ejecutar solo una parte del proyecto?", a: "Sí. Puedes encargarnos todas las partidas gráficas o solo las que necesites." },
      { q: "¿Quién instala?", a: "Nosotros. Coordinamos la instalación con la dirección de obra para entrar en el momento adecuado." },
      { q: "¿Hacéis vinilos decorativos para particulares?", a: "Los vinilos decorativos y murales para vivienda están en Impresión digital. Esta página es para proyectos de estudio." },
    ],
    contactH2: "¿Tienes un proyecto de interiores que ejecutar?",
    contactLead: "Envíanos planos, alzados o renders y te preparamos una propuesta por partidas.",
    related: [
      { href: "servicios/laminas-solares/", anchor: "láminas de control solar" },
      { href: "servicios/senaletica/", anchor: "señalética del proyecto" },
      { href: "servicios/iluminacion-decorativa/", anchor: "iluminación decorativa" },
      { href: "servicios/rotulos/", anchor: "letras corpóreas de interior" },
      { href: "profesionales/", anchor: "cómo trabajamos con estudios" },
      { href: "materiales/", anchor: "materiales y acabados" },
    ],
    waMessage: "Hola, os escribo por un proyecto de interiorismo comercial.",
  },

  "laminas-solares": {
    slug: "laminas-solares",
    variant: "types",
    breadcrumb: "Láminas solares",
    title: "Láminas solares y de control solar para edificios | Vexil Alicante",
    description: "Láminas de control solar para fachadas acristaladas, oficinas y locales: menos calor y deslumbramiento sin cambiar el cristal. También láminas de privacidad.",
    eyebrow: "Control solar y privacidad",
    h1: "Láminas solares para edificios, oficinas y locales: menos calor sin cambiar el cristal",
    lead: "Colocamos láminas de control solar en fachadas acristaladas, oficinas, comercios y viviendas. Reducen el calor y el deslumbramiento, protegen del sol el mobiliario y, si lo necesitas, dan privacidad. Trabajamos también sobre proyecto, con estudios y constructoras.",
    pills: [
      { icon: "wb_sunny", title: "Control solar", sub: "Menos calor" },
      { icon: "visibility_off", title: "Privacidad", sub: "Sin que te vean desde fuera" },
      { icon: "apartment", title: "Edificios", sub: "Oficinas y locales" },
      { icon: "architecture", title: "Sobre proyecto", sub: "Estudios y obra" },
    ],
    ctaPrimary: "Pedir presupuesto de láminas solares",
    ctaSecondary: "Ver tipos de lámina",
    trust: "Colocación en oficinas, comercios, viviendas y proyectos de obra.",
    heroImg: "fachada-04.jpg",
    heroAlt: "Lámina de control solar en fachada acristalada",
    whyEyebrow: "Sobre el cristal que ya tienes",
    whyH2: "Resuelve el calor y el deslumbramiento sobre el cristal que ya tienes",
    whyLead: "Sin cambiar la carpintería. Si buscas <a data-rel=\"servicios/interiorismo-comercial/\">vinilo al ácido para mamparas</a> o una <a data-rel=\"servicios/fachadas/\">renovación de fachada</a>, esas páginas encajan mejor.",
    benefits: [
      { icon: "thermostat", title: "Menos calor y deslumbramiento", text: "La lámina de control solar reduce el sol que entra y hace el interior más habitable.", tag: "Confort" },
      { icon: "visibility_off", title: "Privacidad", text: "Láminas reflectantes, esmeriladas y translúcidas para que no te vean desde fuera.", tag: "Intimidad" },
      { icon: "wb_sunny", title: "Protege el interior", text: "Ayuda a cuidar mobiliario y superficies expuestos al sol.", tag: "Protección" },
      { icon: "architecture", title: "También sobre proyecto", text: "Partimos del tipo de vidrio y del criterio del estudio o la constructora.", tag: "Obra" },
    ],
    typesH2Intro: "Tipos de lámina",
    typesLead: "Control solar, privacidad o las dos en la misma fachada.",
    types: [
      {
        id: "arquitectura",
        h2: "Lámina solar arquitectónica para fachadas y oficinas",
        kicker: "Control solar",
        text: "Para fachadas acristaladas, oficinas y locales. Reduce calor y deslumbramiento sin cambiar el cristal.",
        specs: ["Fachadas y oficinas", "Menos calor y deslumbramiento", "Sin cambiar el vidrio"],
        img: "fachada-hero.jpg",
        alt: "Lámina solar arquitectónica en fachada de oficinas",
        faqs: [
          { q: "¿Oscurece mucho el interior?", a: "Depende del modelo: los hay más claros y más oscuros. Te ayudamos a elegir el equilibrio entre control del sol y luz natural." },
        ],
      },
      {
        id: "privacidad",
        h2: "Láminas de privacidad: reflectantes, esmeriladas y translúcidas",
        kicker: "Sin que te vean desde fuera",
        text: "Privacidad en despachos, salas y consultas. El efecto depende del modelo y de la luz.",
        specs: ["Reflectante, esmerilada o translúcida", "Despachos y consultas", "Luz natural"],
        img: "caso-03.jpg",
        alt: "Lámina de privacidad en cristalera de oficina",
        faqs: [
          { q: "¿Se puede ver desde fuera?", a: "Depende del modelo y de la luz. Algunas láminas reflectantes limitan la visión desde fuera durante el día; de noche, con luz interior, el efecto puede invertirse. Las esmeriladas dan privacidad a cualquier hora." },
        ],
      },
      {
        id: "obra",
        h2: "Láminas de control solar en proyectos de obra",
        kicker: "Estudios y constructoras",
        text: "Si eres estudio o constructora, partimos de tu proyecto y revisamos el tipo de vidrio antes de proponer la lámina.",
        specs: ["Revisión del vidrio", "Coordinación de proyecto", "Ver página de profesionales"],
        img: "fachada-hero.jpg",
        alt: "Proyecto de láminas solares en obra nueva",
        faqs: [
          { q: "¿Trabajáis con el estudio o la constructora?", a: "Sí. Mira <a data-rel=\"profesionales/\">estudios y constructoras</a> para ver cómo encajamos en la obra." },
        ],
      },
    ],
    faqH2: "Preguntas frecuentes de láminas solares",
    faqs: [
      { q: "¿Qué es la lámina solar?", a: "Es una lámina que se adhiere al cristal para reducir el calor y el deslumbramiento que entran por las ventanas. También puede aportar privacidad, según el modelo." },
      { q: "¿Se puede colocar en cualquier cristal?", a: "En la mayoría de cristales sí, pero algunos tipos de vidrio pueden sufrir tensiones térmicas con determinadas láminas. Revisamos tu cristal antes de proponerte un modelo." },
      { q: "¿Se coloca por dentro o por fuera?", a: "Depende del tipo de lámina y del cristal. Lo más habitual es colocarla por el interior, pero te indicamos la mejor opción en cada caso." },
      { q: "¿Se puede quitar?", a: "Sí, se puede retirar. Con el tiempo el adhesivo puede dejar restos, que se eliminan con el producto adecuado." },
      { q: "¿Cómo se limpia un cristal con lámina?", a: "Con un paño suave y un producto neutro, sin estropajos ni productos abrasivos. Se recomienda esperar unos días tras la colocación antes de la primera limpieza." },
    ],
    contactH2: "¿Fachada acristalada o demasiado sol en el local?",
    contactLead: "Envía fotos del cristal y, si la sabes, la orientación. Te proponemos la lámina y un presupuesto a medida.",
    related: [
      { href: "servicios/interiorismo-comercial/", anchor: "vinilo al ácido para mamparas" },
      { href: "servicios/fachadas/", anchor: "renovación de fachada" },
      { href: "profesionales/", anchor: "estudios y constructoras" },
      { href: "materiales/", anchor: "materiales y acabados" },
    ],
    waMessage: "Hola, os escribo por láminas solares.",
  },

  corte: {
    slug: "corte",
    breadcrumb: "Corte a medida",
    title: "Corte láser de metacrilato y fresado CNC a medida | Vexil Alicante",
    description: "Cortamos y grabamos metacrilato con láser y fresamos composite, PVC y madera con CNC. Desde una sola pieza hasta series, a partir de tu archivo.",
    eyebrow: "Láser y CNC",
    h1: "Corte láser y fresado CNC a medida: de una pieza a una serie",
    lead: "Cortamos y grabamos metacrilato con láser, y fresamos composite, PVC y madera con CNC. Partimos de tu archivo o te ayudamos a prepararlo.",
    pills: [
      { icon: "flare", title: "Láser", sub: "Metacrilato" },
      { icon: "precision_manufacturing", title: "CNC", sub: "Composite, PVC, madera" },
      { icon: "category", title: "A medida", sub: "Una pieza o series" },
      { icon: "draft", title: "Tu archivo", sub: "O lo preparamos" },
    ],
    ctaPrimary: "Pedir presupuesto de corte",
    ctaSecondary: "Ver qué cortamos",
    trust: "La misma maquinaria con la que fabricamos letras y placas.",
    heroImg: "hero-taller.jpg",
    heroAlt: "Corte láser y fresado CNC en el taller de Vexil",
    whyEyebrow: "Dos máquinas",
    whyH2: "Dos máquinas para que cada pieza salga con el acabado que necesita",
    whyLead: "El láser da detalle en metacrilato. El CNC fresa composite, PVC y madera. Con eso fabricamos <a data-rel=\"servicios/rotulos/\">letras corpóreas</a> y <a data-rel=\"servicios/senaletica/\">placas de metacrilato</a>.",
    benefits: [
      { icon: "flare", title: "Corte láser de metacrilato", text: "Corte y grabado para logos, placas y piezas con canto limpio.", tag: "Láser" },
      { icon: "precision_manufacturing", title: "Fresado CNC", text: "Composite, PVC y madera para letras, bandejas y piezas a medida.", tag: "CNC" },
      { icon: "inventory_2", title: "De una pieza a una serie", text: "Fabricamos una unidad o varias iguales a partir del mismo archivo.", tag: "Series" },
      { icon: "draft", title: "Partimos de tu archivo", text: "Vectorial con medidas reales, o te ayudamos a prepararlo.", tag: "Archivo" },
    ],
    solutionsH2: "Qué cortamos y fresamos",
    solutionsLead: "Metacrilato al láser. Composite, PVC y madera al CNC.",
    solutions: [
      { tech: "Láser", title: "Corte láser de metacrilato", text: "Corte y grabado de placas, logos y piezas de detalle.", a: "Ideal para", av: "Placas y logos", b: "Acabado", bv: "Canto limpio / grabado", img: "plano-totem.jpg", cap: "Metacrilato al láser", alt: "Pieza de metacrilato cortada con láser" },
      { tech: "CNC", title: "Fresado CNC a medida", text: "Composite, PVC y madera para letras, bandejas y piezas de stand.", a: "Ideal para", av: "Corpóreas y bandejas", b: "Material", bv: "Composite, PVC, madera", img: "hero-taller.jpg", cap: "Fresado CNC", alt: "Pieza fresada con CNC en el taller" },
      { tech: "Series", title: "Series y recambios", text: "La misma pieza, las veces que haga falta, a partir de tu archivo.", a: "Cantidad", av: "Una o varias", b: "Archivo", bv: "Se reutiliza", img: "fachada-01.jpg", cap: "Serie corta", alt: "Serie de piezas cortadas a medida" },
      { tech: "Conjunto", title: "Corte integrado en el proyecto", text: "La pieza entra en un rótulo, una placa o un stand, no se queda suelta.", a: "Siguiente paso", av: "Montaje o entrega", b: "Proyecto", bv: "Un solo taller", img: "fachada-03.jpg", cap: "Pieza de proyecto", alt: "Letras cortadas listas para un rótulo" },
    ],
    faqH2: "Preguntas frecuentes de corte láser y CNC",
    faqs: [
      { q: "¿Qué diferencia hay entre corte CNC y corte láser?", a: "La fresadora CNC corta y talla materiales más gruesos, como composite, PVC y madera. El láser es más fino y preciso: lo usamos para cortar y grabar metacrilato." },
      { q: "¿Qué materiales podéis cortar?", a: "El láser, metacrilato. El CNC, composite, PVC y madera. Si tienes otro material, dinos cuál y te confirmamos si podemos trabajarlo." },
      { q: "¿Hacéis una sola pieza o solo series?", a: "Desde una única pieza hasta series. Cuéntanos qué necesitas y te presupuestamos." },
      { q: "¿Qué archivo necesito enviar?", a: "Un archivo vectorial (DXF, SVG, AI o PDF vectorial) con las medidas reales y los textos convertidos a curvas. Si solo tienes un boceto o una imagen, podemos ayudarte a prepararlo." },
      { q: "¿Cómo se calcula el precio?", a: "Depende del material, del tamaño, de la complejidad del corte y de la cantidad. Envía tu archivo o tu idea y te preparamos un presupuesto." },
    ],
    contactH2: "¿Tienes un archivo o una medida?",
    contactLead: "Escríbenos con el material y las medidas. Te decimos láser, CNC o ambos, y el precio.",
    related: [
      { href: "servicios/rotulos/", anchor: "letras corpóreas" },
      { href: "servicios/senaletica/", anchor: "placas de metacrilato" },
    ],
    waMessage: "Hola, os escribo por corte láser y CNC a medida.",
  },

  stands: {
    slug: "stands",
    breadcrumb: "Stands para ferias",
    title: "Stands para ferias y photocalls a medida | Vexil Alicante",
    description: "Photocalls, tótems, letras de gran tamaño y gráfica para ferias y eventos. Lo diseñamos, lo producimos en nuestro taller y lo preparamos para tu fecha.",
    eyebrow: "Ferias y eventos",
    h1: "Stands para ferias y eventos: photocalls, tótems y gráfica a medida",
    lead: "Photocalls, tótems, letras de gran tamaño y toda la gráfica de tu stand, producidos en nuestro taller. Pensado para montarse rápido y verse desde el pasillo.",
    pills: [
      { icon: "photo_camera", title: "Photocall", sub: "Listo para foto" },
      { icon: "view_quilt", title: "Tótems", sub: "Y gráfica de pasillo" },
      { icon: "print", title: "Gran formato", sub: "Del mismo taller" },
      { icon: "event", title: "Tu fecha", sub: "Lo preparamos" },
    ],
    ctaPrimary: "Pedir presupuesto de stand",
    ctaSecondary: "Ver elementos",
    trust: "Photocalls, tótems y gráfica de feria producidos en El Campello.",
    heroImg: "caso-04.jpg",
    heroAlt: "Photocall y gráfica de stand para feria producidos por Vexil",
    whyEyebrow: "Se ve de lejos",
    whyH2: "En una feria, se recuerdan los stands que se ven de lejos",
    whyLead: "La gráfica y las piezas grandes salen del mismo taller que las <a data-rel=\"servicios/impresion-digital/\">lonas y gran formato</a> y el <a data-rel=\"servicios/rotulos/\">neón LED</a>.",
    benefits: [
      { icon: "visibility", title: "Se ve desde el pasillo", text: "Tipografía, contraste y altura pensados para recinto ferial.", tag: "Lectura" },
      { icon: "photo_camera", title: "Photocall de verdad", text: "Fondos, logo y formato listos para foto.", tag: "Foto" },
      { icon: "print", title: "Gráfica de taller", text: "Lonas, rígidos y vinilos impresos aquí.", tag: "Producción" },
      { icon: "event", title: "Para tu fecha", text: "Partimos de la fecha del evento y preparamos las piezas a tiempo.", tag: "Plazo del evento" },
    ],
    solutionsH2: "Elementos de stand que fabricamos",
    solutionsLead: "Puedes pedir el conjunto o solo el photocall.",
    solutions: [
      { tech: "Fondo", title: "Photocalls y backdrops", text: "Estructura y gráfica a medida de tu hueco, listas para foto.", a: "Formato", av: "A medida", b: "Gráfico", bv: "Gran formato propio", img: "caso-04.jpg", cap: "Photocall", alt: "Photocall de feria con gráfica a medida" },
      { tech: "Vertical", title: "Tótems y portabanners", text: "De la pieza ligera al tótem de producción propia.", a: "Uso", av: "Pasillo y acceso", b: "Luz", bv: "Según el diseño", img: "plano-totem.jpg", cap: "Tótem", alt: "Tótem de stand para feria" },
      { tech: "Volumen", title: "Letras de gran tamaño", text: "Corpóreas de feria en PVC u otros materiales de taller, para foto y presencia.", a: "Escala", av: "De mostrador a gran formato", b: "Acabado", bv: "Lacado o vinilo", img: "fachada-03.jpg", cap: "Letras de feria", alt: "Letras de gran tamaño para stand" },
      { tech: "Gráfica", title: "Gráfica del stand", text: "Paneles, lonas y cartelería con tu imagen de marca.", a: "Incluye", av: "Diseño y producción", b: "Taller", bv: "Un solo proveedor gráfico", img: "caso-02.jpg", cap: "Gráfica de stand", alt: "Gráfica de gran formato para stand de feria" },
    ],
    faqH2: "Preguntas frecuentes de stands",
    faqs: [
      { q: "¿Qué hacéis para stands y eventos?", a: "Photocalls, tótems, letras de gran tamaño y la gráfica del stand. Lo diseñamos y lo producimos en el taller." },
      { q: "¿Puedo reutilizar las piezas en otros eventos?", a: "Sí. Podemos diseñar elementos desmontables para que los uses en más de una feria." },
      { q: "¿Qué información necesitáis para presupuestar?", a: "Las medidas del espacio, la fecha del evento, tu logotipo y qué piezas quieres: photocall, tótems, letras o gráfica." },
      { q: "¿Podéis hacer gráficas y cartelería para el stand?", a: "Sí. Imprimimos las gráficas, los paneles y la cartelería con tu imagen de marca." },
    ],
    contactH2: "¿Tienes fecha de feria?",
    contactLead: "Dinos recinto, metros y fecha. Te proponemos las piezas y un presupuesto a medida.",
    related: [
      { href: "servicios/impresion-digital/", anchor: "lonas y gran formato" },
      { href: "servicios/rotulos/", anchor: "neón LED" },
    ],
    waMessage: "Hola, os escribo por stands para ferias.",
  },

  "iluminacion-decorativa": {
    slug: "iluminacion-decorativa",
    breadcrumb: "Iluminación decorativa",
    title: "Iluminación LED decorativa para locales | Vexil Alicante",
    description: "Tiras y perfiles LED, paneles retroiluminados y luz de acento para tiendas, bares y oficinas. Diseñada junto a tu rótulo para que todo el local encaje.",
    eyebrow: "Luz de espacio",
    h1: "Iluminación decorativa LED para tiendas, bares y oficinas",
    lead: "Tiras y perfiles LED, paneles retroiluminados y luz de acento para destacar tu producto, una barra o una recepción. La planteamos junto al rótulo para que el local tenga una sola imagen.",
    pills: [
      { icon: "light", title: "LED", sub: "Tiras y perfiles" },
      { icon: "highlight", title: "Acento", sub: "Producto y barra" },
      { icon: "home", title: "Interior", sub: "Tiendas, bares, oficinas" },
      { icon: "architecture", title: "Con el rótulo", sub: "Una sola imagen" },
    ],
    ctaPrimary: "Pedir presupuesto de iluminación",
    ctaSecondary: "Ver aplicaciones",
    trust: "Luz de ambiente y de acento. Si buscas un rótulo luminoso o un neón con tu logo, míralo en Rótulos.",
    heroImg: "fachada-hero.jpg",
    heroAlt: "Iluminación decorativa LED en un local comercial",
    whyEyebrow: "Luz, no cartel",
    whyH2: "Un rótulo se lee. La iluminación decorativa se siente.",
    whyLead: "Usamos la luz para destacar producto, recorrer una barra o dar calor a una recepción. ¿Buscas un <a data-rel=\"servicios/rotulos/\">rótulo luminoso o un neón LED</a>? Está en Rótulos. Si forma parte de <a data-rel=\"servicios/interiorismo-comercial/\">proyectos de interiores</a>, lo ejecutamos con el resto de partidas.",
    benefits: [
      { icon: "light_mode", title: "El local se percibe mejor", text: "Temperatura de color y capas de luz para retail, clínicas y hostelería.", tag: "Ambiente" },
      { icon: "highlight", title: "Acento donde vende", text: "Tiras y perfiles para lineal de producto o barra.", tag: "Producto" },
      { icon: "architecture", title: "Subraya el espacio", text: "Tiras en cornisa, huecos y estantes, integradas en el mueble.", tag: "Lineal" },
      { icon: "bolt", title: "LED a medida", text: "Cortes a longitud y difusión homogénea para cada tramo.", tag: "A medida" },
    ],
    solutionsH2: "Aplicaciones de iluminación decorativa",
    solutionsLead: "Luz de espacio. El neón de logotipo y las cajas de luz de fachada están en Rótulos.",
    solutions: [
      { tech: "Perfil LED", title: "Perfiles y tiras LED a medida", text: "Cortes a longitud, esquinas y difusión homogénea para mueble o techo.", a: "Uso", av: "Cornisas, estantes, barras", b: "Control", bv: "Según la pieza", img: "fachada-hero.jpg", cap: "Tira LED", alt: "Perfil LED lineal en interior comercial" },
      { tech: "Acento", title: "Iluminación de producto", text: "Destacar lineal, escaparate interior o una pieza de marca.", a: "Efecto", av: "Acento dirigido", b: "Interior", bv: "Retail y exposiciones", img: "caso-01.jpg", cap: "Luz de producto", alt: "Iluminación de acento sobre producto en tienda" },
      { tech: "Backlight", title: "Paneles retroiluminados de ambiente", text: "Superficies luminosas de interior, distintas de un rótulo de fachada.", a: "Uso", av: "Recepciones y pasillos", b: "Nota", bv: "El cartel luminoso está en Rótulos", img: "fachada-02.jpg", cap: "Panel luminoso", alt: "Panel retroiluminado de interior" },
      { tech: "Proyecto", title: "Luz junto al resto del local", text: "La planteamos con el rótulo y las partidas de interior para que todo encaje.", a: "Rótulos", av: "Neón y luminosos", b: "Interior", bv: "Proyectos de interiores", img: "caso-03.jpg", cap: "Luz de proyecto", alt: "Iluminación decorativa coordinada con el local" },
    ],
    faqH2: "Preguntas frecuentes de iluminación decorativa",
    faqs: [
      { q: "¿Qué es la iluminación decorativa?", a: "Es la luz pensada para crear ambiente y destacar producto o espacios, no para leer un cartel." },
      { q: "¿Para qué espacios sirve?", a: "Para tiendas, bares, oficinas y otros locales donde la luz forma parte de la imagen." },
      { q: "¿Instaláis tiras y perfiles LED de interior?", a: "Sí. Las cortamos a medida y las instalamos en el local." },
      { q: "¿Necesito instalación eléctrica especial?", a: "La mayoría de piezas LED funcionan con un transformador a toma convencional. Si el montaje pide algo distinto, te lo indicamos en el presupuesto." },
    ],
    contactH2: "¿Quieres iluminar el espacio?",
    contactLead: "Envía fotos del local y dinos si ya tienes rótulo. Te proponemos perfiles y un presupuesto a medida.",
    related: [
      { href: "servicios/rotulos/", anchor: "rótulos luminosos y neón LED" },
      { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiores" },
    ],
    waMessage: "Hola, os escribo por iluminación decorativa LED.",
  },

  senaletica: {
    slug: "senaletica",
    breadcrumb: "Señalética y placas",
    title: "Señalética y placas de metacrilato a medida | Vexil Alicante",
    description: "Placas de metacrilato para despachos, directorios, señales de orientación y carteles informativos con la imagen de tu marca. Desde una placa a un edificio.",
    eyebrow: "Orientación e identidad",
    h1: "Señalética y placas de metacrilato para que cada visitante encuentre su sitio",
    lead: "Placas de despacho, directorios, señales de orientación y carteles informativos, con la misma imagen que tu rótulo. Desde una sola placa hasta la señalética completa de un edificio.",
    pills: [
      { icon: "badge", title: "Placas", sub: "Metacrilato a medida" },
      { icon: "domain", title: "Directorios", sub: "Plantas y empresas" },
      { icon: "alt_route", title: "Orientación", sub: "Recorridos claros" },
      { icon: "signpost", title: "Misma marca", sub: "Que tu rótulo" },
    ],
    ctaPrimary: "Pedir presupuesto de señalética",
    ctaSecondary: "Ver sistemas",
    trust: "Placas y orientación con la misma imagen que el resto del local.",
    heroImg: "plano-totem.jpg",
    heroAlt: "Directorio y placas de metacrilato de señalética Vexil",
    whyEyebrow: "También es marca",
    whyH2: "La señalética también es imagen de marca",
    whyLead: "Unificamos materiales y tipografía con tu identidad. Las placas salen del <a data-rel=\"servicios/corte/\">corte láser de metacrilato</a>; si forman parte de <a data-rel=\"servicios/interiorismo-comercial/\">proyectos de interiores</a> o de <a data-rel=\"obra-nueva/\">señalética para obra nueva</a>, lo coordinamos.",
    benefits: [
      { icon: "explore", title: "El visitante no se pierde", text: "Recorridos claros en oficinas, clínicas, hoteles e industriales.", tag: "Orientación" },
      { icon: "badge", title: "Placas de la casa", text: "Mismo material y tipo que el rótulo principal.", tag: "Identidad" },
      { icon: "update", title: "Nombres que se actualizan", text: "Sistemas intercambiables para despachos y organigramas.", tag: "Modulares" },
      { icon: "gavel", title: "Lo informativo, bien resuelto", text: "Integramos las señales informativas en la misma familia gráfica.", tag: "Conjunto" },
    ],
    solutionsH2: "Sistemas de señalética",
    solutionsLead: "Del pictograma suelto al directorio de edificio.",
    solutions: [
      { tech: "Metacrilato", title: "Placas de despacho y sala", text: "Metacrilato, aluminio o composite. Fijas o con pieza intercambiable.", a: "Uso", av: "Despachos, consultas, salas", b: "Cambio", bv: "Inserto si lo pides", img: "plano-totem.jpg", cap: "Placa de sala", alt: "Placa de metacrilato para despacho" },
      { tech: "Modular", title: "Directorios de planta y edificio", text: "Listados de empresas o departamentos, actualizables.", a: "Formato", av: "Pared o tótem", b: "Marca", bv: "Tipografía del manual", img: "fachada-01.jpg", cap: "Directorio", alt: "Directorio de planta en un edificio" },
      { tech: "Pictogramas", title: "Señales de orientación", text: "Conjuntos coherentes para pasillos, parkings y naves.", a: "Lectura", av: "A distancia de pasillo", b: "Soporte", bv: "Pared, bandera, suelo", img: "caso-03.jpg", cap: "Orientación", alt: "Señal de orientación en pasillo" },
      { tech: "Informativa", title: "Carteles informativos y de evacuación", text: "Cuando hay que señalizar, lo integramos al resto de la familia gráfica.", a: "Tipo", av: "Información y evacuación", b: "Estética", bv: "Alineada con la marca", img: "caso-02.jpg", cap: "Señal informativa", alt: "Cartel informativo de señalética de edificio" },
    ],
    faqH2: "Preguntas frecuentes de señalética",
    faqs: [
      { q: "¿Qué tipos de señalética podéis hacer?", a: "Señales de orientación, placas de puerta y despacho, directorios, carteles informativos y placas de profesional, entre otras. Se hacen a medida." },
      { q: "¿En qué materiales se fabrican las placas?", a: "Metacrilato, aluminio, PVC y composite, con impresión, corte o grabado según el diseño." },
      { q: "¿Podéis fabricar una sola placa?", a: "Sí. Hacemos desde una placa individual hasta la señalética completa de un edificio." },
      { q: "¿Sirve para exterior?", a: "Sí, con materiales adecuados para la intemperie. Dinos dónde va a colocarse." },
      { q: "¿Las señales de seguridad y evacuación cumplen normativa?", a: "La señalización de seguridad tiene requisitos específicos (tamaño, color, pictograma). Si necesitas señales de este tipo, indícanoslo desde el principio y confirma con tu técnico o mantenedor qué exige la normativa en tu caso." },
      { q: "¿Se pueden colocar sin taladrar?", a: "En muchas superficies sí, con adhesivo de montaje. Depende del peso y de la superficie." },
    ],
    contactH2: "¿Necesitas placas, directorio o un recorrido entero?",
    contactLead: "Envía plano o listado de salas. Te proponemos el sistema y un presupuesto a medida.",
    related: [
      { href: "servicios/corte/", anchor: "corte láser de metacrilato" },
      { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiores" },
      { href: "obra-nueva/", anchor: "señalética para obra nueva" },
      { href: "profesionales/", anchor: "señalética para obra nueva" },
    ],
    waMessage: "Hola, os escribo por señalética y placas de metacrilato.",
  },
};

export const extraPages = {
  materiales: {
    slug: "materiales",
    path: "materiales/",
    breadcrumb: "Materiales",
    title: "Materiales y acabados para rotulación y señalética | Vexil Alicante",
    description: "Composite, metacrilato, vinilos y láminas solares: acabados y usos para especificar rótulos, fachadas e interiores en tus proyectos.",
    eyebrow: "Para especificar proyecto",
    h1: "Materiales y acabados para tus proyectos",
    lead: "Los materiales con los que trabajamos, qué acabados tienen y dónde funciona mejor cada uno. Si necesitas la ficha técnica de alguno para tu proyecto, pídenosla.",
    pills: [
      { icon: "layers", title: "Composite", sub: "Fachadas y rígidos" },
      { icon: "flare", title: "Metacrilato", sub: "Letras y placas" },
      { icon: "print", title: "Vinilos", sub: "Impresión, corte, ácido" },
      { icon: "wb_sunny", title: "Láminas", sub: "Solar y privacidad" },
    ],
    ctaPrimary: "Pedir una ficha técnica",
    ctaSecondary: "Ver familias",
    trust: "Solo acabados que trabajamos. Datos de ficha del fabricante bajo petición.",
    heroImg: "fachada-01.jpg",
    heroAlt: "Muestrario de materiales de rotulación en el taller de Vexil",
    whyEyebrow: "Muestrario",
    whyH2: "Familias de material para especificar",
    whyLead: "Una referencia para estudios. Desde aquí puedes ir al servicio donde se usa cada familia.",
    benefits: [
      { icon: "layers", title: "Composite de aluminio", text: "Revestimientos de fachada y soportes rígidos. Ver Fachadas.", tag: "Fachadas" },
      { icon: "flare", title: "Metacrilato", text: "Letras, placas y piezas de corte láser. Ver Rótulos y Señalética.", tag: "Corte" },
      { icon: "view_quilt", title: "PVC", text: "Letras, letras de feria y piezas fresadas. Ver Corte y Stands.", tag: "CNC" },
      { icon: "print", title: "Vinilos", text: "Impresión, corte y efecto ácido. Ver Impresión e Interiores.", tag: "Gráfico" },
      { icon: "wb_sunny", title: "Láminas solares y de privacidad", text: "Control solar y privacidad sobre el cristal existente.", tag: "Cristal" },
      { icon: "light", title: "LED y neón", text: "Luminosos, neón LED y luz decorativa. Ver Rótulos e Iluminación.", tag: "Luz" },
    ],
    solutionsH2: "Dónde se usa cada material",
    solutionsLead: "Pide la ficha técnica si la necesitas para un pliego o un plano.",
    solutions: [
      { tech: "Fachada", title: "Composite de aluminio", text: "Para revestir el frente del local y como soporte rígido impreso.", a: "Uso", av: "Exterior e interior", b: "Servicio", bv: "Fachadas", img: "fachada-01.jpg", cap: "Composite", alt: "Panel composite de aluminio para fachada" },
      { tech: "Letras y placas", title: "Metacrilato", text: "Corte láser y grabado para letras, placas y detalle.", a: "Uso", av: "Interior y exterior según espesor", b: "Servicio", bv: "Rótulos y señalética", img: "plano-totem.jpg", cap: "Metacrilato", alt: "Placa de metacrilato cortada a medida" },
      { tech: "Gráfico", title: "Vinilos de impresión, corte y ácido", text: "Según superficie: pared, cristal, vehículo o rígido.", a: "Uso", av: "Según el vinilo", b: "Servicio", bv: "Impresión e interiores", img: "fachada-04.jpg", cap: "Vinilos", alt: "Muestras de vinilo de impresión y de corte" },
      { tech: "Cristal", title: "Láminas solares y de privacidad", text: "Sobre el vidrio existente, para calor, deslumbramiento o intimidad.", a: "Uso", av: "Fachadas y oficinas", b: "Servicio", bv: "Láminas solares", img: "fachada-hero.jpg", cap: "Láminas", alt: "Lámina solar sobre cristal de fachada" },
    ],
    faqH2: "Preguntas frecuentes de materiales",
    faqs: [
      { q: "¿Podéis enviar la ficha técnica?", a: "Sí. Pídenosla para el material concreto de tu proyecto. Solo enviamos datos que constan en la ficha del fabricante." },
      { q: "¿Es un catálogo de venta?", a: "No. Es una referencia para especificar. El presupuesto se hace sobre el proyecto." },
    ],
    contactH2: "¿Necesitas una ficha técnica para tu proyecto?",
    contactLead: "Dinos el material y el uso. Te enviamos la ficha o te proponemos el acabado que encaja.",
    related: [
      { href: "profesionales/", anchor: "cómo trabajamos con estudios" },
      { href: "servicios/fachadas/", anchor: "rotulación de fachadas" },
      { href: "servicios/interiorismo-comercial/", anchor: "proyectos de interiorismo comercial" },
      { href: "servicios/laminas-solares/", anchor: "láminas de control solar" },
    ],
    waMessage: "Hola, os escribo para pedir una ficha técnica de materiales.",
  },

  franquicias: {
    slug: "franquicias",
    path: "franquicias/",
    breadcrumb: "Franquicias",
    title: "Rotulación para franquicias y cadenas | Vexil Alicante",
    description: "Aplicamos la imagen de tu franquicia en cada local: rótulos, fachada, vinilos y señalética según tu manual de marca, con el mismo equipo en cada apertura.",
    eyebrow: "Cadenas y aperturas",
    h1: "Rotulación para franquicias y cadenas: la misma imagen en cada local",
    lead: "Si abres o renuevas locales con una misma imagen, te interesa un proveedor que ya la conozca. Trabajamos a partir de tu manual de marca y lo aplicamos igual en cada apertura: rótulo, fachada, vinilos, interiores y señalética.",
    pills: [
      { icon: "storefront", title: "Manual de marca", sub: "Aplicado a cada local" },
      { icon: "hub", title: "Un interlocutor", sub: "En cada apertura" },
      { icon: "architecture", title: "Aperturas", sub: "Y reformas de imagen" },
      { icon: "signpost", title: "Rótulo y fachada", sub: "El mismo criterio" },
    ],
    ctaPrimary: "Hablar de vuestra red",
    ctaSecondary: "Ver qué aplicamos",
    trust: "Misma imagen en cada local. Taller en El Campello.",
    heroImg: "fachada-hero.jpg",
    heroAlt: "Fachada comercial con imagen de marca aplicada de forma uniforme",
    whyEyebrow: "Por qué un solo taller",
    whyH2: "La misma imagen, local a local",
    whyLead: "Adaptamos cada pieza a la fachada y las medidas de cada local sin salirnos del manual.",
    benefits: [
      { icon: "draft", title: "Tu manual, aplicado", text: "Adaptamos cada pieza a la fachada y las medidas de cada local sin salirnos de la imagen de la marca.", tag: "Manual" },
      { icon: "support_agent", title: "Un solo interlocutor", text: "El mismo equipo mide, fabrica y monta en cada local.", tag: "Aperturas" },
      { icon: "storefront", title: "Aperturas y reformas", text: "Tanto para locales nuevos como para renovar los que ya tenéis.", tag: "Red" },
      { icon: "architecture", title: "Todas las partidas gráficas", text: "Rótulo, fachada, vinilos, interiores y señalética con el mismo criterio.", tag: "Conjunto" },
    ],
    solutionsH2: "Qué aplicamos en cada local",
    solutionsLead: "Según el manual: rótulos, fachada, interiores y señalética.",
    solutions: [
      { tech: "Rótulo", title: "Rótulo de cada apertura", text: "La misma familia de letras y luz, adaptada a la fachada real.", a: "Base", av: "Manual de marca", b: "Servicio", bv: "Rótulos", img: "fachada-03.jpg", cap: "Rótulo de cadena", alt: "Rótulo de franquicia adaptado a la fachada" },
      { tech: "Frente", title: "Fachada del local", text: "Revestimiento y escaparate con el mismo criterio en cada apertura.", a: "Uso", av: "Locales nuevos o reforma", b: "Servicio", bv: "Fachadas", img: "fachada-hero.jpg", cap: "Fachada de cadena", alt: "Fachada de local de cadena rotulada" },
      { tech: "Interior", title: "Vinilos y gráfica interior", text: "Lo que el manual pide dentro, ejecutado a medida del local.", a: "Partida", av: "La del manual", b: "Servicio", bv: "Interiores", img: "caso-01.jpg", cap: "Interior de cadena", alt: "Gráfica interior de un local de franquicia" },
      { tech: "Orientación", title: "Señalética de la marca", text: "Placas y directorios con la tipografía del manual.", a: "Uso", av: "Sala, baños, recorrido", b: "Servicio", bv: "Señalética", img: "plano-totem.jpg", cap: "Señalética de cadena", alt: "Placas de señalética con imagen de franquicia" },
    ],
    faqH2: "Preguntas frecuentes de franquicias",
    faqs: [
      { q: "¿Trabajáis a partir del manual de marca?", a: "Sí. Lo aplicamos a las medidas reales de cada local y te avisamos si algo no cabe o hay que adaptarlo." },
      { q: "¿Podéis hacer varios locales?", a: "Sí. El mismo equipo fabrica y monta en cada apertura de la zona." },
    ],
    contactH2: "¿Cuántos locales tenéis en la zona?",
    contactLead: "Cuéntanos la red y envíanos el manual de marca. Te preparamos una propuesta.",
    related: [
      { href: "profesionales/", anchor: "cómo trabajamos con estudios y constructoras" },
      { href: "servicios/rotulos/", anchor: "letras corpóreas y rótulos" },
      { href: "servicios/fachadas/", anchor: "rotulación de fachadas" },
    ],
    waMessage: "Hola, os escribo por rotulación para franquicias.",
  },

  "obra-nueva": {
    slug: "obra-nueva",
    path: "obra-nueva/",
    breadcrumb: "Obra nueva",
    title: "Carteles de obra y señalética para promotoras | Vexil Alicante",
    description: "Carteles de obra para promociones y la señalética y las placas del edificio terminado. Un solo proveedor de la obra a la entrega.",
    eyebrow: "Promotoras y constructoras",
    h1: "Rotulación para promotoras y constructoras: del cartel de obra a la entrega de llaves",
    lead: "Acompañamos la promoción de principio a fin: cartel de obra mientras se construye, y señalética, placas y rotulación de zonas comunes cuando se entrega.",
    pills: [
      { icon: "print", title: "Cartel de obra", sub: "Diseño y producción" },
      { icon: "alt_route", title: "Señalética", sub: "Del edificio terminado" },
      { icon: "badge", title: "Placas", sub: "Portal, plantas, garaje" },
      { icon: "architecture", title: "Un proveedor", sub: "De la obra a la entrega" },
    ],
    ctaPrimary: "Enviar planos de la promoción",
    ctaSecondary: "Ver partidas",
    trust: "Cartel de obra y señalética de entrega. Taller en El Campello.",
    heroImg: "caso-02.jpg",
    heroAlt: "Cartel de obra y gráfica de promoción producidos por Vexil",
    whyEyebrow: "De la obra a las llaves",
    whyH2: "Una promoción, dos momentos de rotulación",
    whyLead: "El contenido obligatorio del cartel lo facilita la promotora; nosotros lo diseñamos, lo producimos y lo colocamos.",
    benefits: [
      { icon: "print", title: "Carteles de obra", text: "Impresión de gran formato en nuestro taller y montaje en obra.", tag: "Durante la obra" },
      { icon: "signpost", title: "Imagen de la promoción", text: "Diseñamos el cartel con los datos que nos pasa la promotora.", tag: "Contenido" },
      { icon: "alt_route", title: "Señalética del edificio", text: "Portal, plantas, garaje y zonas comunes, con la misma imagen.", tag: "En la entrega" },
      { icon: "badge", title: "Placas y numeración", text: "Placas de portal, numeración de plantas y puertas, directorios y señales de garaje.", tag: "Identificación" },
    ],
    solutionsH2: "Partidas de obra nueva",
    solutionsLead: "Cartelería de obra e impresión de gran formato, y señalética de entrega.",
    solutions: [
      { tech: "Durante la obra", title: "Carteles de obra", text: "Impresión de gran formato en nuestro taller y montaje en obra. El contenido obligatorio lo facilita la promotora.", a: "Incluye", av: "Diseño, producción y colocación", b: "Servicio", bv: "Impresión digital", img: "caso-02.jpg", cap: "Cartel de obra", alt: "Cartel de obra de una promoción inmobiliaria" },
      { tech: "En la entrega", title: "Señalética del edificio", text: "Placas de portal, numeración de plantas y puertas, directorios y señales de garaje, con la misma imagen que la promoción.", a: "Zonas", av: "Portal, plantas, garaje, comunes", b: "Servicio", bv: "Señalética", img: "plano-totem.jpg", cap: "Señalética de entrega", alt: "Señalética de portal y plantas en edificio nuevo" },
    ],
    faqH2: "Preguntas frecuentes de obra nueva",
    faqs: [
      { q: "¿El contenido del cartel de obra lo ponéis vosotros?", a: "El contenido obligatorio lo facilita la promotora. Nosotros lo diseñamos, lo producimos y lo colocamos." },
      { q: "¿Hacéis también la señalética del edificio terminado?", a: "Sí. Portal, plantas, garaje y zonas comunes, con la imagen de la promoción." },
    ],
    contactH2: "¿Tienes una promoción en marcha?",
    contactLead: "Envíanos los planos de la promoción y te preparamos la propuesta.",
    related: [
      { href: "profesionales/", anchor: "cómo trabajamos con constructoras" },
      { href: "servicios/impresion-digital/", anchor: "impresión de gran formato" },
      { href: "servicios/senaletica/", anchor: "señalética" },
    ],
    waMessage: "Hola, os escribo por carteles de obra y señalética de promoción.",
  },
};

export const profesionales = {
  slug: "profesionales",
  path: "profesionales/",
  breadcrumb: "Profesionales",
  title: "Rotulación para arquitectos, interioristas y constructoras | Vexil",
  description: "Resolvemos rótulos, fachadas, señalética y vinilos dentro de tus proyectos. Partimos de tus planos, proponemos materiales y nos coordinamos con la obra.",
  eyebrow: "Estudios y constructoras",
  h1: "Rotulación y señalética para tus proyectos de arquitectura e interiorismo",
  lead: "Trabajamos con estudios, interioristas y constructoras que necesitan resolver rótulo, fachada, señalética o vinilos dentro de un proyecto. Partimos de tus planos, te proponemos materiales y nos coordinamos con la obra.",
  pills: [
    { icon: "architecture", title: "Desde planos", sub: "Alzados y renders" },
    { icon: "layers", title: "Una partida", sub: "Todo lo que lleva marca" },
    { icon: "handyman", title: "Obra", sub: "Nos coordinamos" },
    { icon: "draft", title: "Materiales", sub: "Te proponemos" },
  ],
  ctaPrimary: "Enviar un proyecto",
  ctaSecondary: "Ver para quién trabajamos",
  trust: "Rótulo, fachada, señalética y vinilos dentro de tu proyecto.",
  heroImg: "plano-totem.jpg",
  heroAlt: "Proyecto de rotulación y señalética para un estudio de arquitectura",
  whyEyebrow: "Una partida",
  whyH2: "Una sola partida para todo lo que lleva marca",
  whyLead: "Un interlocutor para rótulo, fachada, señalética y vinilos.",
  benefits: [
    { icon: "architecture", title: "Estudios de arquitectura", text: "Del plano a la pieza instalada: rótulo, fachada y cristal.", tag: "Arquitectura" },
    { icon: "chair", title: "Interioristas", text: "Vinilos, murales, luz y señalética con el mismo criterio.", tag: "Interiorismo" },
    { icon: "apartment", title: "Constructoras", text: "Una partida cerrada para rótulos y señalética de la obra.", tag: "Obra" },
    { icon: "support_agent", title: "Un interlocutor", text: "Quien te asesora es quien fabrica y quien monta.", tag: "Taller" },
  ],
  solutionsH2: "Cómo encajamos en tu proyecto",
  solutionsLead: "Partidas concretas de fachada, interiores, láminas, señalética y rótulos.",
  solutions: [
    { tech: "Arquitectura", title: "Del plano a la pieza instalada", text: "Leemos alzados, proponemos material y montamos coordinados con la obra.", a: "Partida", av: "Rótulo y fachada", b: "Base", bv: "Tus planos", img: "fachada-hero.jpg", cap: "Proyecto de fachada", alt: "Fachada de proyecto ejecutada por Vexil" },
    { tech: "Interiorismo", title: "Vinilos, murales, luz y señalética", text: "Ejecutamos las partidas gráficas del proyecto de interior.", a: "Partida", av: "La que el plano pida", b: "Obra", bv: "Coordinados", img: "caso-01.jpg", cap: "Partida de interior", alt: "Partida gráfica de un proyecto de interiorismo" },
    { tech: "Constructora", title: "Rótulos y señalética de la obra", text: "Una partida para el edificio: cartel, placas y orientación.", a: "Momentos", av: "Obra y entrega", b: "Más", bv: "Página de obra nueva", img: "caso-02.jpg", cap: "Partida de obra", alt: "Rotulación de obra para constructora" },
    { tech: "Especificación", title: "Materiales y acabados", text: "Te proponemos el material y, si la necesitas, la ficha técnica.", a: "Referencia", av: "Página de materiales", b: "Uso", bv: "Pliego y plano", img: "fachada-01.jpg", cap: "Acabados", alt: "Acabados de rotulación para especificar en proyecto" },
  ],
  faqH2: "Preguntas frecuentes para profesionales",
  faqs: [
    { q: "¿Partís de planos?", a: "Sí. Con planos, alzados o renders revisamos medidas y materiales, y te avisamos si algo hay que ajustar para fabricarlo." },
    { q: "¿Podéis ejecutar solo una partida?", a: "Sí. Rótulo, fachada, vinilos, láminas o señalética: las que el proyecto pida." },
    { q: "¿Quién instala?", a: "Nosotros, coordinados con la dirección de obra." },
    { q: "¿Tenéis un muestrario?", a: "Sí. En Materiales verás familias y usos. La ficha técnica se pide para el material concreto." },
  ],
  contactH2: "¿Tienes un proyecto que necesita rótulo o señalética?",
  contactLead: "Envíanos planos o un listado de partidas. Te proponemos materiales y un presupuesto a medida.",
  related: [
    { href: "servicios/fachadas/", anchor: "fachadas comerciales" },
    { href: "servicios/interiorismo-comercial/", anchor: "interiorismo comercial" },
    { href: "servicios/laminas-solares/", anchor: "láminas solares" },
    { href: "servicios/senaletica/", anchor: "señalética" },
    { href: "servicios/rotulos/", anchor: "letras corpóreas y rótulos" },
    { href: "materiales/", anchor: "materiales y acabados" },
  ],
  waMessage: "Hola, os escribo desde un estudio / constructora por un proyecto.",
};

export const nosotros = {
  slug: "nosotros",
  path: "nosotros/",
  breadcrumb: "Nosotros",
  title: "Quiénes somos: taller de rotulación en El Campello | Vexil",
  description: "Vexil es un taller de rotulación en El Campello. Diseñamos, imprimimos, fabricamos y montamos rótulos, fachadas y vinilos para negocios de la zona de Alicante.",
  eyebrow: "Taller de rotulación",
  h1: "Diseñamos, fabricamos y montamos. Sin intermediarios.",
  lead: "Vexil une dos oficios en un mismo taller de El Campello: el diseño y la impresión, y la fabricación y el montaje. Tenemos las máquinas en casa, así que cada trabajo pasa por nuestras manos de principio a fin.",
  pills: [
    { icon: "precision_manufacturing", title: "Taller propio", sub: "Máquinas en casa" },
    { icon: "support_agent", title: "Asesoramiento", sub: "Material, tamaño y luz" },
    { icon: "handyman", title: "Montaje", sub: "Lo instalamos nosotros" },
    { icon: "print", title: "Impresión", sub: "Gran formato propio" },
  ],
  ctaPrimary: "Hablar con el taller",
  ctaSecondary: "Ver con qué trabajamos",
  trust: "Taller propio · Asesoramiento · Montaje",
  heroImg: "hero-taller.jpg",
  heroAlt: "Taller de rotulación Vexil en El Campello",
  whyEyebrow: "Quiénes somos",
  whyH2: "Qué nos diferencia",
  whyLead: "No vendemos catálogo suelto. Valoramos el encargo, proponemos el sistema que conviene y lo producimos aquí.",
  benefits: [
    { icon: "precision_manufacturing", title: "Máquinas en casa", text: "CNC, láser, impresión de gran formato e iluminación LED. Controlamos corte, gráfico y luz desde el mismo taller.", tag: "Taller" },
    { icon: "support_agent", title: "Asesoramos siempre", text: "Material, tamaño y luz: te decimos qué conviene a tu local y a tu calle.", tag: "Criterio" },
    { icon: "handshake", title: "Hablas con quien lo hace", text: "Quien te asesora es quien fabrica y quien monta.", tag: "Un equipo" },
    { icon: "groups", title: "Negocios y proyectos", text: "Trabajamos el encargo del comercio y las partidas de estudios, arquitectos y constructoras.", tag: "Para quién" },
  ],
  solutionsH2: "Con qué trabajamos",
  solutionsLead: "Las líneas de taller con las que resolvemos la mayoría de encargos.",
  solutions: [
    { tech: "CNC", title: "Mesa CNC", text: "Corte y fresado de composite, PVC y madera para letras, bandejas y piezas a medida.", a: "Materiales", av: "Composite, PVC, madera", b: "Uso", bv: "Fachada, placa, pieza", img: "hero-taller.jpg", cap: "CNC de taller", alt: "Fresadora CNC del taller de Vexil" },
    { tech: "Láser", title: "Láser de detalle", text: "Corte y grabado de metacrilato para logos, placas y series cortas.", a: "Ideal para", av: "Placas y logos", b: "Acabado", bv: "Canto limpio / grabado", img: "plano-totem.jpg", cap: "Láser", alt: "Corte láser de metacrilato en el taller" },
    { tech: "Gran formato", title: "Impresión de gran formato", text: "Vinilos, lonas y gráficos a escala de fachada, vehículo o stand.", a: "Soportes", av: "Vinilo, lona, rígido", b: "Uso", bv: "Fachada, flota, evento", img: "fachada-04.jpg", cap: "Impresión", alt: "Impresora de gran formato en el taller de Vexil" },
    { tech: "LED", title: "Iluminación de rótulo y espacio", text: "Cajas de luz, neón LED y perfiles para el rótulo y el local.", a: "Sistemas", av: "Caja de luz, neón LED, perfil", b: "Servicio", bv: "Nuevo y reparación", img: "fachada-02.jpg", cap: "LED", alt: "Rótulo con iluminación LED fabricado en taller" },
  ],
  faqH2: "Preguntas frecuentes sobre Vexil",
  faqs: [
    { q: "¿Qué es Vexil?", a: "Un taller de rotulación en El Campello: diseñamos, fabricamos y montamos rótulos, fachadas y vinilos para negocios de la zona de Alicante." },
    { q: "¿Dónde estáis?", a: "Nuestro taller está en El Campello y trabajamos en Alicante, San Juan, San Vicente, Mutxamel, Jijona, Villajoyosa y Benidorm." },
    { q: "¿Trabajáis con estudios y constructoras?", a: "Sí. En Profesionales explicamos cómo encajamos en un proyecto." },
    { q: "¿Cómo se pide presupuesto?", a: "Por el formulario, WhatsApp o 616 048 109. Con fotos, medidas o archivo basta." },
  ],
  contactH2: "¿Quieres que el taller valore tu encargo?",
  contactLead: "Escríbenos o llama al 616 048 109. Te decimos sistema, material y un presupuesto a medida.",
  related: [
    { href: "profesionales/", anchor: "estudios, arquitectos y constructoras" },
    { href: "servicios/rotulos/", anchor: "rótulos para negocios" },
  ],
  waMessage: "Hola, os escribo para conocer el taller y pedir presupuesto.",
};

export const legalPages = {
  "aviso-legal": {
    slug: "aviso-legal",
    path: "aviso-legal/",
    title: "Aviso legal | Vexil",
    h1: "Aviso legal",
    description: "Aviso legal del sitio web de Vexil, taller de rotulación en El Campello.",
  },
  privacidad: {
    slug: "privacidad",
    path: "privacidad/",
    title: "Política de privacidad | Vexil",
    h1: "Política de privacidad",
    description: "Cómo trata Vexil los datos que nos envías por el formulario, el teléfono o WhatsApp.",
  },
  cookies: {
    slug: "cookies",
    path: "cookies/",
    title: "Política de cookies | Vexil",
    h1: "Política de cookies",
    description: "Información sobre cookies y medición en el sitio web de Vexil.",
  },
};

export const thanksPage = {
  slug: "gracias",
  path: "gracias/",
  title: "Hemos recibido tu mensaje | Vexil",
  h1: "Mensaje enviado",
  description: "Hemos recibido tu solicitud de presupuesto. Te responderemos lo antes posible.",
  lead: "Gracias. Revisamos lo que nos has enviado y te respondemos con una propuesta a medida.",
};

export const homeCatalog = navServices.map((s) => ({ ...s }));
